README.md
The link wasn't properly formatted
_Brief explanation of why these changes are/are not backwards compatible. Feel free to remove for trivial, backwards compatible changes._
=> Fix docs.celo.org link in README

consensus/istanbul/backend/announce.go, consensus/istanbul/backend/backend.go
During `handleIstAnnounce`, a `lastAnnounceGossiped` map is used to only regossip messages from a sender after some time from their previous message. However, since there were no locks used, concurrent map writes occurred.
This pr adds rw locks around map reads and writes.
- Fixes #368 
Yes, since just added locks
=> Add locks to lastAnnounceGossiped

.circleci/config.yml
The BLS PR https://github.com/celo-org/celo-blockchain/pull/326 pointed the CI to a specific branch in order to pass tests.
=> Points CI back to master

vendor/github.com/celo-org/bls-zexe/go/bls_darwin.go, vendor/vendor.json
bls-zexe wasn't properly defining the linkage in MacOS.
=> Fixes Geth compilation on MacOS

consensus/istanbul/backend/engine.go
Currently, the Istanbul engine only fails with a generic error. Added logging for the specific case where the quorum size is not big enough.
Tested against integration which had an older quorum size logic and currently the local node fails to sync with integration.
=> Istanbul: adds minimum quorum violation logging

.circleci/config.yml, p2p/discv5/node_test.go, p2p/enode/urlv4_test.go
Earlier, `yarn` would build walletkit in the post install step.
That has been removed in celo-monorepo, therefore, build walletkit and some other packages
explicitly to avoid https://circleci.com/gh/celo-org/celo-blockchain/7304
Also fixes a failing unit test (cause due to change in error string from golang).
Circle CI execution will test this
Fixes https://github.com/celo-org/celo-monorepo/issues/616
=> [CircleCI] Build walletkit explicitly & fix test

Dockerfile
Using layer caching, whenever a non-`vendor/` change is made, Docker builds are sped up from ~8.5 minutes to ~1.5 minutes. This only recompiles rust dependencies when there's a change in the `vendor` directory
Built with & without, `geth attach`'d on both versions that were built
=> Only rebuild rust in Docker with vendor changes

cmd/geth/chaincmd.go, cmd/utils/flags.go, consensus/clique/clique.go, core/chain_indexer.go, eth/backend.go, eth/downloader/downloader.go, eth/downloader/modes.go, les/backend.go, les/fetcher.go, les/sync.go, light/lightchain.go, mobile/geth.go, params/config.go
Remove references to Celo latest sync mode
`make -j geth && make -j lint`
- Addresses https://github.com/celo-org/celo-monorepo/issues/596
Removes `CeloLatestsync` mode.
=> [cleanup]Remove references to Celo latest sync mode

cloudbuild-android.yaml
Generated by `echo {npm_token} | gcloud kms encrypt .... | base64`. Needed for updating the geth client for testing BLS changes on integration. I also created a new corresponding cloud build trigger
Cloud Build worked & created a new npm package
=> Update previously revoked encrypted npm token

eth/config.go
`eth/backend.go` rejects configs where `LightPeers >= MaxPeers`.
https://github.com/celo-org/celo-blockchain/pull/395 broke our tests/maybe geth and this fixes it.
Tests should be passing now.
N/A
N/A
N/A
=> Fixes LightPeers equal to MaxPeers

cmd/puppeth/genesis_test.go, cmd/puppeth/testdata/stureby_parity.json, params/protocol_params.go
As per [EIP-170](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-170.md), the size of deployed contracts is limited by a constant parameter to avoid a quadratic vulnerability.
We can increase the constant without reintroducing the vulnerability - all that matters is that the constant remains reasonably small.
We've been running into bytecode limits while developing the core Celo contracts that implement on-chain governance. This PR doubles the limit to ease smart contract development.
Deployed a smart contract that I'm working on on a separate branch that went over the old bytecode limit.
- Fixes celo-monorepo#378, obviates celo-monorepo#379
Could potentially be backwards incompatible on a network on which there appeared a transaction attempting to deploy a contract that was too …
=> Double contract bytecode limit

Makefile
Currently, if the Makefile detects an existing NDK, it forces the user to delete the NDK directory. This conflicts with both a normal user workflow and how the Google Cloud Build workflow works.
Locally, seeing the following workflows work fine:
* Deleting the NDK directory.
* Removing the LLVM toolchain.
* Building with an existing appropriate NDK.
Improves some error messages in the Makefile.
=> Makefile: makes android workflow accept existing appropriate NDKs properly

contract_comm/currency/currency.go
There is an existing bug in the logic around converting and comparing two denominations of different currencies within geth.  Basically, when geth was reading the exchange rates from the smart contracts, it erroneously switched the numerator and denominator around.
Specifically, it should be using this format:
<asset we’re pegging to> / Celo Gold 
instead of 
Celo Gold / <asset we’re pegging to> 
Ran celo dollar gas currency e2e tests.
Ran geth's unit tests.
Is backward compatible.
=> fixed geth's reading of exchange rates

core/state_transition.go, params/protocol_params.go
Set the max gas for intrinsic smart contracts calls to double the charged gas.
Note that we plan to modify geth to read these values from a smart contract.
Ran the unit tests.
Is backward compatible.  Specifically, the charged intrinsic gas is not changed.
=> set max gas to double of the charged gas for the 'intrinsic' smart contract calls

.circleci/config.yml, consensus/istanbul/core/testbackend_test.go, consensus/istanbul/core/types_test.go, consensus/istanbul/errors.go, consensus/istanbul/types.go
Ensure we check the address of the validator signing a message with the value at `msg.Address` 
New unit tests.
- Fixes celo-labs#107
Yes
=> Check message address against signature

consensus/istanbul/config.go, consensus/istanbul/core/core.go
* reduce default istanbul round change timeout from 10s to 3s 
* limit exponential backoff to 5 rounds, so backoff at round=5 is 3+2**4 = 35 secs
* add the blockperiod on to the timeout for the first round of every sequence 
By running a testnet and e2e tests.
Yes
=> Reduce istanbul default timeout, cap exp backoff

consensus/istanbul/backend/announce.go, consensus/istanbul/backend/engine.go, consensus/istanbul/core/handler.go, contract_comm/evm.go, contract_comm/random/random.go, core/state_transition.go, core/vm/evm.go
This decreases the logging intensity for a few expected situations. The first is when geth tries to get the the registry contract, but the contract is not yet deployed. This will output a lot of `error` level logs when a node begins syncing-- this is because geth will try to get the registry contract when processing a block, and there will always be a series of blocks that were mined before the registry contract was deployed. I decreased these logs the to `debug` level.
There were 2 other `error` level logs to do with Istanbul that I changed from `error` -> `warning`. The first is when an error occurs when upserting a validator enode entry (which can happen when an old announce message is received-- there was a comment on discord about this). The second is when handling an istanbul …
=> Sanitize logs

.circleci/config.yml, Dockerfile.alltools, cmd/bootnode/main.go, cmd/geth/main.go, cmd/geth/usage.go, cmd/utils/flags.go, consensus/istanbul/backend/announce.go, consensus/istanbul/backend/engine.go, consensus/istanbul/backend/handler.go, consensus/istanbul/config.go, consensus/istanbul/core/core.go, consensus/istanbul/core/handler.go, consensus/istanbul/core/testbackend_test.go, consensus/istanbul/core/types_test.go, consensus/istanbul/errors.go, consensus/istanbul/types.go, contract_comm/evm.go, contract_comm/random/random.go, core/state_transition.go, core/tx_list.go, core/vm/contracts.go, core/vm/contracts_test.go, core/vm/errors.go, core/vm/evm.go, node/config.go, p2p/discv5/udp.go, p2p/server.go, params/bootnodes.go
After a lengthly research; in order to detect the correct place where to  log, my findings were
1) Needs to be done **After** the block has been finalized. So, we react upon looking at the parent block, not the block that is being mined. That way we know it's finalized.
2) Needs to happen at the end/beginning of each epoch, that when the election is run
3) 
worker listens to newBlocks, and call the mainLoop (writes to newWorkCh),
mainLoop on `newWorkCh` call consensus `NewChainHead`
```go
case req := <-w.newWorkCh:
if h, ok := w.engine.(consensus.Handler); ok {
h.NewChainHead()
}
w.commitNewWork(req.interrupt, req.noempty, req.timestamp)
```
`NewChainHead` checks if the last block (already mined) was the last epoch block; and that's where we can log
```go
func (sb *Backend) NewChainHead() …
```
=> Log validator result elections

p2p/server.go
`ntab` is `nil` when `--nodiscover` is passed to geth, causing a seg fault
Ran without the fix and `--nodiscover`, saw the error, then ran again with the fix to ensure the error went away
n/a
n/a
This is backwards compatible
=> Fix discoverTableInfo when discovery is disabled

consensus/istanbul/backend/engine.go, contract_comm/evm.go
When syncing with alfajoresstaging from master I saw a couple more over-extreme errors/warnings when importing blocks before contracts had been deployed. I moved these down to the `Debug` level, just like in #495 
Synced with the changes & saw the error/warnings go away
n/a
- Fixes #356 
This is backwards compatible
=> Sanitize more logs

core/state_transition.go, core/tx_pool.go, miner/worker.go
This PR modifies the tx pool so that it will verify that submitted txns' price is greater than or equal to the current gpm.
* Unit tests ran
* Added an e2e test to verify that a txn w/ too low of a gasprice is invalidated by the txpool.
None
- Fixes #502 
Will not add txns that have a txn gas price < current gas price minimum
=> txpool invalidate txns for txs with gasPrice less than gpm

.circleci/config.yml
celo-monorepo now uses node 10
CI
=> ci: use node 10

consensus/istanbul/utils.go, eth/backend.go, ethstats/ethstats.go
Export epoch information (size and blocks remaining) to celostats
tested against integration testnet with https://github.com/diminator/ethstats-server/pull/1/files
Made `GetNumberWithinEpoch` public
- Fixes #463
=> [wip] expose epochSize and blocks remaining

Dockerfile.celo-node
I pushed a new version of `us.gcr.io/celo-testnet/celo-node:alfajoresstaging` and `us.gcr.io/celo-testnet/celo-node:alfajores` that uses the correct geth version that's currently deployed
The version is currently what's on alfajores/alfajoresstaging & they're working well
n/a
n/a
not backwards compatible
=> Update celo-node dockerfile geth commit for alfajores/alfajoresstaging

.circleci/config.yml, contract_comm/gasprice_minimum/gasprice_minimum.go, core/state_transition.go, les/api_backend.go
Instead of sending gas fees to "feeRecipient" and "infraestructureFund" we send them to "feeRecipient" and the "proposer".
The proposer, it's also the coinbase for the node.
e2e
- Fixes #455
=> Send txFee to proposer not to infrastructure fund

core/state_transition.go
Log gas currency as well as the amount of gas provided in case a transaction
is failing due to the "out of gas" error.
Trivial change, therefore, tested with `make lint && make -j geth`
=> Log provided gas if transaction fails due to low gas

cmd/geth/main.go, cmd/geth/usage.go, cmd/utils/flags.go, consensus/istanbul/backend/backend.go, consensus/istanbul/backend/handler.go, consensus/istanbul/config.go, consensus/istanbul/validator.go, consensus/istanbul/validator/default.go, consensus/istanbul/validator/default_test.go, consensus/istanbul/validator/selectors.go, consensus/istanbul/validator/selectors_test.go, contract_comm/random/random.go
Prior to this PR the proposers are selected round robin with the order determined by the storage order, which is roughly equal to the order in which the validators are added.
This PR adds shuffled round robin proposer policy, which uses the randomness from the last block of each epoch to create a shuffle order to use for the round robin during that epoch.
- Proposer selector tested in unit tests in `consensus/istanbul/validator`
Refactored a few pieces of `consensus/istanbul/validator` code including extracting the ProposerSelector methods to a new `selectors.go`
- Fixes https://github.com/celo-org/celo-blockchain/issues/530
Validators running shuffled round robin will not be compatible with validators running round robin mode.
=> Create shuffled round robin proposer selector and use it by default

cmd/puppeth/testdata/stureby_parity.json, params/protocol_params.go
Follows lead of https://github.com/celo-org/celo-blockchain/pull/421 to allow for more Governance contract features.
Partner PR in mono: https://github.com/celo-org/celo-monorepo/pull/613
See #421
=> Increase bytecode limit to 2^16

.circleci/config.yml
CI was moved to a specific branch in https://github.com/celo-org/celo-blockchain/pull/556. This brings it back.
=> CI: brings back to master

consensus/istanbul/backend/backend.go, consensus/istanbul/backend/engine.go
If cache creation fails while creating a backend for the consensus engine, log and panic instead of continuing without error. The only failure condition based on the current code is if the cache size, which is constant, is changed to be less than zero, but it is always good practice to handle errors.
Rename `recents` to `recentSnapshots`
- Fixes https://github.com/celo-org/celo-blockchain/issues/586
Fully backwards compatible
=> Panic on cache creation failure when creating a new backend for consensus

consensus/istanbul/backend/announce.go, consensus/istanbul/backend/backend.go, consensus/istanbul/backend/handler.go, consensus/istanbul/backend/val_enode_share.go, consensus/istanbul/core/commit.go, consensus/istanbul/core/commit_test.go, consensus/istanbul/core/core.go, consensus/istanbul/core/handler_test.go, consensus/istanbul/core/prepare.go, consensus/istanbul/core/prepare_test.go, consensus/istanbul/core/preprepare_test.go, consensus/istanbul/core/roundchange.go, consensus/istanbul/core/testbackend_test.go, consensus/istanbul/core/types_test.go, consensus/istanbul/types.go
This is a follow up PR for this one:  https://github.com/celo-org/celo-blockchain/pull/515
It has the following changes:
1) Created a new subject type `CommittedSubject` that is used for commit messages.  This type contains a subject and a commitedSeal for it.  The `CommittedSeal` field that original was in the Istanbul `Message` type is moved to the new type.  @kobigurk - I would really appreciate it if you could take a glance at this.
2) Created a new istanbul submessage type `ForwardMessage` that is used by proxied validators to instruct the proxy forward it's consensus messages.
* Ran geth unit tests
* Ran e2e proxy test
Is not backward compatible.
=> refactor istanbul message

.circleci/config.yml, consensus/istanbul/core/errors.go, consensus/istanbul/core/prepare.go, consensus/istanbul/core/prepare_test.go, consensus/istanbul/core/preprepare_test.go, consensus/istanbul/core/roundchange_test.go, consensus/istanbul/core/testbackend_test.go
This PR modifies the verifyPrepareCert function so that it will check that all of it's messages' views are the same.
Added unit test cases and made sure they worked.
- Fixes https://github.com/celo-org/celo-blockchain/issues/587
Is not backward compatible
=> PrepareCert view consistency check

consensus/istanbul/backend/announce.go, consensus/istanbul/backend/backend.go, consensus/istanbul/backend/engine.go, consensus/istanbul/backend/handler.go
Changes to announce message sending and caching.
1. Announce message will be sent on epoch start
2. Caching of announce message will now check if the destination addresses set has changed.
* Ran geth unit test
* Ran e2e sync test
None
Is backward compatible
=> announce message changes

consensus/istanbul/backend.go, consensus/istanbul/backend/announce.go, consensus/istanbul/backend/backend.go, consensus/istanbul/backend/internal/enodes/val_enode_db.go, consensus/istanbul/backend/internal/enodes/val_enode_db_test.go, consensus/istanbul/core/testbackend_test.go, consensus/istanbul/validator.go, consensus/istanbul/validator/default.go
Reinserts previous lock to ensure changes are atomic.
After a discussion with @kevjue; we think there's a small change of race condition when we are processing an announce message for the same node with different values. For it, we need to ensure that changes to the valEnodeTable and to the p2p server happen atomically. Hence the lock was reinserted.
Unit tests
Extract interface to hide listener logic
=> Atomically update p2p server validator peers on valEnodeTable change

consensus/istanbul/core/backlog.go, consensus/istanbul/core/commit.go, consensus/istanbul/core/commit_test.go, consensus/istanbul/core/core.go, consensus/istanbul/core/errors.go, consensus/istanbul/core/handler.go, consensus/istanbul/core/message_set.go, consensus/istanbul/core/message_set_test.go, consensus/istanbul/core/prepare.go, consensus/istanbul/core/prepare_test.go, consensus/istanbul/core/request.go, consensus/istanbul/core/request_test.go, consensus/istanbul/core/roundchange.go, consensus/istanbul/core/roundchange_test.go, consensus/istanbul/core/roundstate.go, consensus/istanbul/core/testbackend_test.go, consensus/istanbul/core/testutils_test.go, consensus/istanbul/core/types.go
Hide `RoundState` and `MessageSet` behind interface to avoid bad usage. For example, access data to read/write without the proper lock setup
unit tests
minor lint issues
=> Hide RoundState Implementation

consensus/istanbul/core/backlog.go, consensus/istanbul/core/backlog_test.go, consensus/istanbul/core/commit.go, consensus/istanbul/core/core.go, consensus/istanbul/core/handler.go, consensus/istanbul/core/prepare.go, consensus/istanbul/core/preprepare.go, consensus/istanbul/core/preprepare_test.go, consensus/istanbul/core/request.go, consensus/istanbul/core/roundchange.go, consensus/istanbul/core/roundchange_test.go, consensus/istanbul/core/roundstate.go
- Use the `newLogger` factory to create child loggers
- make newLogger private (was public)
- use c.current.View() instead of having a delegate method c.View()
- cleanup some for loops that used break/continue and nested if
ci/unit
=> Cleanup: newLogger & remove core.View()

consensus/istanbul/backend.go, consensus/istanbul/backend/backend.go, consensus/istanbul/backend/backend_test.go, consensus/istanbul/core/commit.go, consensus/istanbul/core/core.go, consensus/istanbul/core/preprepare.go, consensus/istanbul/core/preprepare_test.go, consensus/istanbul/core/roundchange_test.go, consensus/istanbul/core/testbackend_test.go, consensus/istanbul/types.go
- We don't want a new name for Block.
- The author or coinbase is the name already used. We leave proposer for
the current round proposer (which not always will be the final
author/coinbase)
- Rename ParentValidators to ParentBlockValidators
unit/ci
=> Rename LastProposal/Proposer to Block/Author

consensus/istanbul/core/backlog.go, consensus/istanbul/core/backlog_test.go
The format of the commit message's payload changed recently.  The backlog was still parsing the commit msg payload using the old format.
Unit tests.
Yes
=> Fix for backlogging of commit messages

consensus/istanbul/validator/default.go
Randomness should be copied when copying a valset
=> Copy randomness on valset copy

consensus/istanbul/core/backlog.go, consensus/istanbul/core/backlog_test.go, consensus/istanbul/core/commit.go, consensus/istanbul/core/commit_test.go, consensus/istanbul/core/core.go, consensus/istanbul/core/final_committed.go, consensus/istanbul/core/prepare.go, consensus/istanbul/core/prepare_test.go, consensus/istanbul/core/preprepare.go, consensus/istanbul/core/preprepare_test.go, consensus/istanbul/core/request.go, consensus/istanbul/core/request_test.go, consensus/istanbul/core/roundchange.go, consensus/istanbul/core/roundchange_test.go, consensus/istanbul/core/roundstate.go, consensus/istanbul/core/testbackend_test.go, consensus/istanbul/core/testutils_test.go
- c.state now lives inside RoundState
- RoundState has method for every state transition
- Use RoundState methods to Add Prepare/Commit/ParentCommit msgs
- Cleanup everywhere
- Remove unncessary construction arguments for RoundState
- Change where backlog processing is dispatched (at the beginning of a
round)
ci/unit
=> Move state inside RoundState.

contract_comm/election/election.go
This PR fixes a bug that would lead to inconsistent merkle roots when proposing and validating blocks, which prevented block production. Because the ordering of the sort determines the new ordering of the validator groups in the election, any inconsistencies in the sorting order are reflected in the state.
- Copied the datadir from a stalled validator, ran the node, saw the merkle root inconsistency. Reran with the new binary, no inconsistency.
None
=> Use stable sorting algorithm when distributing epoch rewards

consensus/istanbul/backend/backend.go, consensus/istanbul/backend/engine.go, consensus/istanbul/backend/snapshot.go, consensus/istanbul/backend/snapshot_test.go, consensus/istanbul/core/core.go, consensus/istanbul/validator.go, consensus/istanbul/validator/default.go, consensus/istanbul/validator/default_test.go, consensus/istanbul/validator/selectors.go
The holed validator set is unneeded any more because:
1. We don't limit the validator diff size, so the SNARK encoding always signs the whole validator set
2. I would do it differently now, making the holed variant local
=> Validators: Removes holed variant of validator set

core/types/block.go, miner/worker.go
This PR fixes a discrepancy between block proposal creation and block proposal verification. In the former, the block was finalized after the election was run, while in the latter, the block was finalized before the election was run. When block finalization affects the results of the election (as it sometimes will via rewards to voters), this would lead to proposals that would fail to be verified.
By running the end-to-end tests with 10 validators multiple times.
- None
Not backwards compatible
=> Always run the election after block finalization

accounts/accounts.go, accounts/keystore/keystore.go, accounts/keystore/wallet.go, accounts/usbwallet/wallet.go, cmd/geth/accountcmd.go
Needed now that these are supplied separately when registering a validator.
- Ran `account new` and `account proof-of-possession`.
=> Separate public key and signature in proof-of-possession command

consensus/istanbul/backend/pos.go, contract_comm/election/election.go
This PR fixes a bug that would lead to inconsistent merkle roots when proposing and validating blocks, which prevented block production. Because the ordering in which voters for groups receive  epoch rewards may determines the new ordering of the validator set in the election, any inconsistencies in the sorting order are reflected in the state.
- Copied the datadir from a stalled validator, ran the node, saw the merkle root inconsistency. Reran with the new binary, no inconsistency.
=> Deterministically iterate over groups when distributing epoch rewards

consensus/istanbul/backend/backend.go
This is a bug fix for dropped validator peers on new epoch.
unit test
None
=> Fix for dropped validator peers on new epoch

vendor/github.com/celo-org/bls-zexe/go/bls_ios.go, vendor/vendor.json
Adds bls_ios.go which is needed to compile celo-blockchain for iOS.
=> Vendor: update bls-zexe to include iOS bindings

accounts/accounts.go, accounts/keystore/keystore.go, accounts/keystore/wallet.go, accounts/usbwallet/wallet.go, cmd/geth/accountcmd.go
This PR allows the user to specify the address to sign for generating the BLS POP, which is necessary to allow the decoupling of the BLS and ECDSA signing keys.
- Generated a PoP this way and used it to register a validator on baklava staging.
None
=> Specify the address to be signed for BLS POP

consensus/istanbul/core/core.go
This bug meant that we never carried over `Commits` into `ParentCommits`, reducing the number of signatures that the proposer would include in the `ParentAggregatedSeal`
- Ran a validator with these changes.
=> Fix bug that prevented commits from being carried over to the next sequence

consensus/istanbul/core/backlog_test.go, consensus/istanbul/core/core.go, consensus/istanbul/core/request_test.go, consensus/istanbul/core/roundstate.go, consensus/istanbul/core/testbackend_test.go, consensus/istanbul/core/testutils_test.go
Instead of replacing c.current, we now call
c.current.StartNewRound/Sequence() to transation round or sequence.
ci/unit
=> Add StartNewRound/Sequence to RoundState

consensus/istanbul/backend/backend.go, consensus/istanbul/backend/backend_test.go, consensus/istanbul/backend/engine.go, consensus/istanbul/backend/engine_test.go, consensus/istanbul/backend/snapshot.go, consensus/istanbul/backend/snapshot_test.go, consensus/istanbul/core/backlog_test.go, consensus/istanbul/core/commit.go, consensus/istanbul/core/commit_test.go, consensus/istanbul/core/core.go, consensus/istanbul/core/handler.go, consensus/istanbul/core/message_set_test.go, consensus/istanbul/core/prepare.go, consensus/istanbul/core/prepare_test.go, consensus/istanbul/core/preprepare.go, consensus/istanbul/core/preprepare_test.go, consensus/istanbul/core/request_test.go, consensus/istanbul/core/roundchange.go, consensus/istanbul/core/roundchange_test.go, consensus/istanbul/core/roundstate.go, consensus/istanbul/core/testbackend_test.go, consensus/istanbul/core/testutils_test.go, consensus/istanbul/validator.go, consensus/istanbul/validator/default.go, consensus/istanbul/validator/default_test.go, consensus/istanbul/validator/selectors.go, consensus/istanbul/validator/selectors_test.go, consensus/istanbul/validator/validator.go
Now ValidatorSet is inmutable, meaning that remains the same for the
whole epoch. While, before ValidatorSet changed every roundChange since
it had the proposer.
Also, by doing this, we eliminate a way of changing data inside the
RoundState without calling any RoundState function.
RounState has a MessageSet which has a ValidatorSet
And on some scenarios the ValidatorSet proposer was being changed
without notifying the RoundState
unit
=> Move Proposer outside ValidatorSet

accounts/accounts.go, accounts/keystore/keystore.go, accounts/keystore/wallet.go, accounts/usbwallet/wallet.go, cmd/geth/accountcmd.go
This will allow validators to generate a proof-of-possession to authorize a signer without having to install the celocli.
- Ran the commands and compared against the CLI. Format appears to be slightly different (RSV vs VRS) but our signature parsing library should handle that for us.
None
=> Update account proof-of-possession command to work with BLS and ECDSA

consensus/istanbul/backend/pos.go, consensus/istanbul/types.go, core/blockchain.go, core/blockchain_test.go, core/rawdb/accessors_chain.go, core/rawdb/accessors_chain_test.go
There was an edge case where both the [miner](https://github.com/celo-org/celo-blockchain/blob/09a217ff58a95214cbc5189c933359707f4fdaf2/miner/worker.go#L625) and the fetcher were calling `WriteBlockWithState` for the same block height (the miner calls it directly, the fetcher inserts blocks via `InsertChain` which calls it internally). This resulted in a race where the uptime would be updated more than once in a block, which ultimately led to wrong `ScoreTally` calculations.
Our [investigation](https://console.cloud.google.com/logs/viewer?interval=NO_LIMIT&project=celo-testnet&organizationId=54829595577&minLogLevel=0&expandAll=false&timestamp=2019-11-27T05:35:03.059000140Z&customFacets=&limitCustomFacetWidth=true&scrollTimestamp=2019-11-27T05:34:58.075082770Z&advancedFilter=resource.type%3 …
=> Ensure ScoreTally gets calculated correctly

accounts/keystore/keystore.go, cmd/geth/accountcmd.go
Reverts celo-org/celo-blockchain#348
After closing https://github.com/celo-org/celo-monorepo/issues/1268, it will no longer be necessary to set the node key to the validator private key. As such, this PR will remove the command introduced to accommodate this workaround.
Related to https://github.com/celo-org/celo-monorepo/issues/1268
Depends on https://github.com/celo-org/celo-monorepo/pull/1922
=> Remove the set-node-key command

consensus/istanbul/backend/backend.go, consensus/istanbul/backend/internal/enodes/val_enode_db.go
This is a temporary fix to handle the case when a proxy or validator starts up and it's val_enode_table is persisted.  It originally wouldn't establish validator connections because the announce/val_enode_share entries are already on disk.  
This change will establish those val connections even if the entries are already on disk.
The more permanent fix is to have a separate validator conn manager goroutine that will monitor the val connections with respect to the val_enode_table (https://github.com/celo-org/celo-blockchain/issues/607).
Unit tests
None
- Fixes #662
=> create validator connections on upsert

les/peer.go, les/txrelay.go, light/txpool.go, light/txpool_test.go
If a light client is connected to a full-node who does not specify an etherbase, a panic will prevent the light client from forwarding them transactions. This panic is nonfatal, as it is recovered from in a resonable place.
Tested with a local testnet where no etherbase is specified on a full-node and transactions are forwarded.
Fully backwards compatible and only the light client needs to be changed.
=> Fix non-fatal panic on forwarding transactions without gateway fee

accounts/accounts.go, accounts/keystore/keystore.go, accounts/keystore/wallet.go, accounts/usbwallet/wallet.go, cmd/geth/accountcmd.go, consensus/istanbul/backend/pos.go
This is needed so that validators can register with validator signers. Accompanying monorepo PR:
https://github.com/celo-org/celo-monorepo/pull/1952
- Used to register a validator on baklavastaging.
_Brief explanation of why these changes are/are not backwards compatible. Feel free to remove for trivial, backwards compatible changes._
=> Print public key in ECDSA account proof-of-possession

Dockerfile.celo-node
`Dockerfile.celo-node` has the sharp edge that your need to update the commit in it or your will get unexpected results when you run it. This PR make it a requirement that you specify the commit on the command line to make it a bit harder to misuse.
=> Make celo-node Dockerfile a little less error-prone

contract_comm/election/election.go
Unclear if this fixes the bug that @mrsmkl saw which caused rewards not to be distributed.
Not tested.
=> Don't reuse variable i in pos.go

cmd/geth/accountcmd.go, contract_comm/election/election.go
This PR fixes a bug in epoch rewards distribution. By sorting in ascending order, which does not match the order of the on-chain list, we risk not perfectly reversing the array. By sorting in descending order, we are guaranteed that the order continues to match the on-chain order.  
h/t @mrsmkl for discovering this
Not tested
=> Sort validator group votes in descending order

consensus/istanbul/backend/announce.go, contract_comm/validators/validators.go, ethstats/ethstats.go
Description
Fixes a bug in which we'd fail to fetch validator info due to the wrong address being used.
Tested
Tested locally and with a tx node against baklavastaging
=> retrieve validators and signers

internal/web3ext/web3ext.go
Got some errors trying to access `istambul.addProxy`, `istambul.proxyInfo` methods. I think this is because some minnor changes from sentry -> proxy.
Trying to test on a testnet. Not working so far.
=> Rename web3 instambul proxy (old sentry) methods

cmd/utils/flags.go, consensus/istanbul/backend/engine.go, consensus/istanbul/backend/engine_test.go, consensus/istanbul/config.go, consensus/istanbul/core/commit.go, consensus/istanbul/core/core.go, consensus/istanbul/core/final_committed.go, consensus/istanbul/core/handler.go, consensus/istanbul/core/message_set.go, consensus/istanbul/core/prepare_test.go, consensus/istanbul/core/preprepare.go, consensus/istanbul/core/preprepare_test.go, consensus/istanbul/core/request.go, consensus/istanbul/core/roundchange.go, consensus/istanbul/core/roundchange_test.go, consensus/istanbul/core/roundstate.go, consensus/istanbul/core/roundstate_persist.go, consensus/istanbul/core/roundstate_test.go, consensus/istanbul/core/testbackend_test.go, consensus/istanbul/core/types.go, consensus/istanbul/types.go, consensus/istanbul/validator.go, consensus/istanbul/validator/default.go, consensus/istanbul/validator/default_test.go, consensus/istanbul/validator/validator.go
Creates a RoundStatePersistence object that will save state to levelDB on each change.
- Now all transition method returns errors on are handled by clients
- RLP encoding for some missing parts
**TODO** RLP encoding for MessageSet. Not sure how to do it for a `map`. @kevjue can you help?
ci/test
=> Persist RoundState on every transition

consensus/istanbul/core/backlog.go, consensus/istanbul/core/backlog_test.go, consensus/istanbul/core/commit.go, consensus/istanbul/core/core.go, consensus/istanbul/core/errors.go, consensus/istanbul/core/events.go, consensus/istanbul/core/handler.go, consensus/istanbul/core/prepare.go, consensus/istanbul/core/preprepare.go
Aims to replace https://github.com/celo-org/celo-blockchain/pull/517
Basically:
* Rebases #517 into latest IBFT branch changes
* the 1st commit is a squash of #517 
* The 2nd commit implements changes
Backlog Changes:
- Decouple Backlog from Core. Make it it's own type
- Make MsgBacklog a interface + a default implementation
- Backlog: extract common logic into `extractMessageView()` fn
- Backlog: separate between `cleanBacklogForSeq` and
`processBacklogForSeq`
- `processBacklogForSeq` will stop iteration when process() returns
false (optimization)
- Rename `processBacklog()` to `updateState()`. Processing the backlog
is a sideeffect of changing the currentView + State
- Clean up backlog  changes. Add inner tests.
Other changes:
- cleanup checkMessage with a "first check the view, then …
=> Buffer future messages (NEW)

contract_comm/validators/validators.go, ethstats/ethstats.go
- expose the validator.signer field for account coupling in the operator, see https://github.com/celo-org/celo-monorepo/pull/1997/ for the contract side
- `reportLatency` often errors because of handshaking with `ethstats-server` (hello-ack, ping-pong). This might throw and close the connection on initialReport as both login and initialReport are waiting for responses. This is a patch that might give a glitch in latency, but avoids new connections being made upon every login try
Not tested, best tested in staging with >50 nodes
Connections are being made and not closed due to a ping-pong hello-ack conflict:
=> expose validator.signer address and warn on latency error

cloudbuild-branchname.yaml, cloudbuild.yaml
I ran into an issue where the bootnode image could not be pulled from a VM on our production GCP project. The solution was to make the image public, which I did manually, but this makes it so images built in the future will be public.
Let it build
n/a
n/a
This will require future deployments to ensure the bootnode repo in the .env file begins with `us.`
=> Make bootnode image public

mobile/geth.go
When running geth on mobile we set validatorEnodeDbPath to `""` so we use the inmemory version of it.
Manual
=> Use inmemory valnodedb for mobile geth

eth/handler.go
This is a bug fix to prevent any peers connected via a proxy's "internal" network interface get disconnected from a max peers limit.
Reproduced the issue on my local computer without the fix.  Added the fix and verified that the proxied validator doesn't get disconnected from the proxy.
None
- Fixes https://github.com/celo-org/celo-blockchain/issues/691
=> Proxy SNBAT disconnect proxied validator from a max peers limit

miner/worker.go, miner/worker_test.go
We need to guarantee the backend will always receive the `FinalCommittedEvent` event to change the sequence, before the worker calls `backend.Prepare`. The event gets emitted via the handler's [NewWork](https://github.com/celo-org/celo-blockchain/blob/87e07a2cd532222baeae876c3d284adc506669b4/consensus/istanbul/backend/handler.go#L208) function. 
I suspect that `commitNewWork` gets called "too quickly", which results in `ParentCommits` being called before the event has been captured by the engine
Approaches:
- Add a tiny sleep in Line 450 in worker.go
- A sustainable fix would be to wait for the FinalCommittedEvent on the worker and call commitNewWork after it has been emitted.
I manually ran all E2E tests with approach (1) and there is no occurrence of the error from Line …
=> Wait T before committing new work so that the round is updated

params/protocol_params.go
Reduces the previous, extremely conservative value of 166,000 to 50,000.
Unit tests
None
- Fixes https://github.com/celo-org/celo-monorepo/issues/1443
Not backwards compatible
=> Reduce intrinsic gas cost for txs paying fees in alternative currencies

consensus/istanbul/core/core.go, consensus/istanbul/core/roundchange.go
* Remove the cap on exponential backoff for IBFT round change messages.
* Merge fix: Storage for message loop variable is reused
Integration tests. plus reverting to behavior in PBFT paper.
- Fixes #706 
Yes
=> Exp backoff for RC messages 

consensus/istanbul/core/core.go
Keep the cap on exponential backoff for phase 1 since timeouts need to be consistent.
=> Revert uncapping exp backoff for RC messages

consensus/istanbul/backend/pos.go, consensus/istanbul/core/backlog.go, consensus/istanbul/core/core.go, consensus/istanbul/core/handler.go, consensus/istanbul/core/prepare.go, consensus/istanbul/core/roundchange.go
This PR is a patch to baklava phase 1 in which round change messages from previous sequences were not properly rejected. This would ultimately lead to PREPREPAREs with invalid round change certificates, as some of the messages would be for previous sequences.
Ran on my own validator
- More logging
Compatible
=> Reject round changes messages for previous sequences, more logging

consensus/istanbul/backend/engine.go
This PR makes changes to that the val peers are refreshed on Istanbul create (specifically in backend.SetChain) for proxies and on istanbul start for standalone validators.
=> refresh val peers on start

consensus/istanbul/core/core.go, consensus/istanbul/core/roundchange.go
* If we receive a valid RC message for current seq but round earlier than our desired round, send a RC message back to the sender to speed recipent collecting F+1 and fast-forwarding to our desired round.
* Logging improvements for RCS.
Unit tests, e2e tests.
Yes.
=> RC batkatcha, RCS logging improvements

consensus/istanbul/core/core.go, consensus/istanbul/core/roundchange.go
* Remove the cap on exponential backoff for IBFT round change messages. 
* If we receive a valid RC message for current seq but round earlier than our desired round, send a RC message back to the sender to speed recipent collecting F+1 and fast-forwarding to our desired round. 
* In the exception case that sealing fails, call `waitForDesiredRound` to correctly update state rather than just send the round change message.
Unit and integration tests.
NO -- Nodes with mixed RC timeout policies cannot be mixed.
=> On receipt of earlier RC msg, send one back to initiator

cmd/utils/flags.go, consensus/consensus.go, consensus/istanbul/backend/backend.go, consensus/istanbul/backend/engine.go, eth/handler.go
This PR has changes so that the proxy and standalone validators will attempt to establish validator peers from the on-disk val enode table on startup.
1) Restarted a proxy against a stalled network and it established Validator peers on startup
2) Restarted a standalone validator against stalled network and it established Validator peers on startup
Fixes #722
=> create validator conns on startup

consensus/istanbul/backend/backend.go, ethstats/ethstats.go
Don't reference `proxyNode.peer` that could trigger `invalid memory address or nil pointer dereference`
Not tested / unable to reproduce error
improve log message on ethstats login ``
- Fixes #712
=> Fix ethstats startup error

consensus/istanbul/backend/api.go, consensus/istanbul/backend/internal/enodes/val_enode_db.go, internal/web3ext/web3ext.go
Added the rpc `istanbul.getValEnodeTable`.
Ran unit tests and e2e tests and verified the rpc worked.
None
- Fixes https://github.com/celo-org/celo-blockchain/issues/726
Yes
=> getValEnodeTable RPC

Dockerfile.celo-node
Adds a file with the enode url of the bootnode
Ran the built image, used the bootnode enode URL
n/a
Partner monorepo PR: https://github.com/celo-org/celo-monorepo/pull/2289
Backwards compatible
=> Add bootnodes to celo-node image

common/task/task.go, common/task/task_test.go, consensus/istanbul/core/core.go, consensus/istanbul/core/roundstate_db.go, consensus/istanbul/core/roundstate_db_test.go, consensus/istanbul/core/testutils_test.go
To implement this we had to change the key format on levelDB; so that
Range queries over istanbul.View are possible.
To do so, a View is serialized to a byte[] as 2 uint64 (pair sequence,
round)
Also, garbage collection is optional and is turned on using constructor
options within the newRoundStateDB()
Finally, to implement a recurrent task, a new common/task package was
created. This makes it easy to test the recurrent task logic and it can
be also used in many other places since it's a quite common patter
within geth.
**Notes for the Reviewers**: 
* pls check the view2key() serialization. It's limited to uint64 and will completely break if negative number for round/seq are used.
* on calling task.stop() this won't interrupt the current run if it's already running, nor stop() will wait …
=> Add garbage collection for RoundStateDB

consensus/istanbul/backend/engine.go, consensus/istanbul/core/core.go, consensus/istanbul/core/handler.go, consensus/istanbul/core/roundstate.go, consensus/istanbul/core/types.go, eth/downloader/downloader.go, miner/worker.go, miner/worker_test.go
This PR addresses a race condition that rarely occurs after blocks are created in round > 0, in which `Backend.Prepare()` is called before the IBFT core sequence changes, resulting in an attempt to aggregate signatures from two different blocks.
Added a sleep of 200ms and 1s in `RoundState.StartNewSequence()` and confirmed that we saw the error message in master but not in this implementation, where we succeeded and timed out, respectively.
- Revert previous attempt to fix this race condition (https://github.com/celo-org/celo-blockchain/pull/670)
- Minor changes to logging
- Fixes #758 
Compatible
=> Loop until IBFT core catches up so that signatures can be added to block

consensus/istanbul/backend/engine.go, consensus/istanbul/backend/engine_test.go
Refactor istanbul engine so that the "ParentSeal" is added to the header
in the Finalize Step, instead of the Prepare step.
It extracts logic to it's own function to make it more readable, and
switched to a style of `if err => return` instead of relying on nested
ifs.
* CI
* Refactor code
- Fixes #777
=> IBFT: Add ParentSeal on Finalize (not in Prepare)

cmd/geth/main.go, cmd/geth/usage.go, cmd/utils/flags.go, consensus/istanbul/backend/announce.go, consensus/istanbul/backend/backend.go, consensus/istanbul/backend/internal/enodes/val_enode_db.go, consensus/istanbul/backend/internal/enodes/val_enode_db_test.go, consensus/istanbul/backend/val_enodes_share.go, consensus/istanbul/backend/val_enodes_share_test.go
When the announce message is sent, it uses the sender's computer's local timestamp.  That timestamp may not necessarily always increase (e.g. NTP could make it earlier).
This change will modify the validators so that they only accept announce messages with timestamps that are within a time range of it's own local timestamp.
* Ran e2e proxy tests
* Ran geth unit tests
- Added the flag `proxy.override-announced-ip-check` to be used for the proxy e2e test
- Converted the timestamp field to be type big.Int instead of uint
Yes
=> validators SBAT handle clock drift for announce messages

consensus/istanbul/backend/handler.go
Shows exact block number in addition to validator election result in log on every epoch.
Tested on Baklava.
```
INFO [12-16|15:29:59.601] Validator Election Results               address=0x355ecA0d3C48c4b8A3359644c7c83Db01c6Ac594 elected=true number=66960
```
- Closes #762
=> Add block number to validator election log

consensus/istanbul/backend/api.go, consensus/istanbul/backend/backend.go, consensus/istanbul/core/core.go, internal/web3ext/web3ext.go
This PR makes the following changes to the Istanbul RPC API to make accessible new information about the proposer for each sequence. Additionally methods for retrieving validator set and snapshot information by hash are removed because they are equivalent to looking up the block by hash then calling the respective method with the block number because the hash is not actually used in snapshot retrieval.
* Add `GetProposer(sequence *rpc.BlockNumber, round *uint64)`
* Remove `GetValidatorsAtHash` and `GetSnapshotAtHash`
* Change `GetValidators` to return the validators that must sign the given block.
Manually testing on a testnet which `geth attach` and executing the changes RPC methods.
* Remove a mutability bug in `consensus/istanbul/core/core.go` which could result in building a block …
=> add istanbul_getProposer rpc method and remove a few others

build/ci.go
Cherry-pick https://github.com/ethereum/go-ethereum/commit/4ef5e9746b6f235d007b61a30276fe897cc9be8b to fix iOS build.
`make ios` was failing with go 1.11.3 with the following error:
```
[...]
>>> /Users/jean/src/github.com/celo-org/celo-blockchain/build/_workspace/src/github.com/ethereum/go-ethereum/build/bin/gomobile bind -ldflags -s -w --target ios --tags ios -v github.com/ethereum/go-ethereum/mobile
/Users/jean/src/github.com/celo-org/celo-blockchain/build/_workspace/src/github.com/ethereum/go-ethereum/build/bin/gomobile: go [list -e -json -compiled=true -test=false -export=false -deps=false -find=true -tags=ios,ios -- github.com/ethereum/go-ethereum/mobile]: exit status 2: cmd/go: -tags space-separated list contains comma
util.go:45: Command failed …
```
=> build: gomobile automaticall adds the ios tag, don't duplicate

consensus/istanbul/backend/handler.go, consensus/istanbul/config.go, consensus/istanbul/core/core.go, consensus/istanbul/core/events.go, consensus/istanbul/core/handler.go, consensus/istanbul/core/roundchange.go, consensus/istanbul/core/roundchange_test.go, consensus/istanbul/core/testbackend_test.go
Separates the IBFT round change timer into two: one that moves into `StateWaitingForRoundChange` and advances to to the next desired round; and one that while in  in `StateWaitingForRoundChange` periodically resends RoundChange messages for the same current desired round if the other timeout exceeds `MinResendRoundChangeTimeout`. 
Add hard-coded config options to control timeout parameters:
* `TimeoutBackoffFactor` - Timeout at subsequent rounds is: `RequestTimeout + 2**round * TimeoutBackoffFactor` (in milliseconds)
* `MinResendRoundChangeTimeout` - Minimum interval with which to resend RoundChange messages for same round
* `MaxResendRoundChangeTimeout` -Maximum interval with which to resend RoundChange messages for same round
New test in `core_test.go`.
TODO - on a fault-injection …
=> Periodically resend RoundChanges for same round 

Dockerfile, cloudbuild-branchname.yaml, consensus/istanbul/backend/backend.go, consensus/istanbul/backend/engine.go, consensus/istanbul/backend/pos.go, contract_comm/evm.go
With the goal of helping to track down issues with execution time, especially in epoch finalization, this PR adds timers to the Istanbul backend and `contract_comm` to track execution times as metrics.
* Pass `$COMMIT_SHA` to docker in cloud build from branches to ensure the `version.txt` file is populated correctly.
* Update the build instructions in `Dockerfile` to make sure `version.txt` gets populated
Manually via `geth attach` on local testnet
It is
=> Add metrics timers to block finalization and evm execution

consensus/consensustest/mockprotocol.go, consensus/istanbul/backend/announce.go, consensus/istanbul/backend/engine_test.go, miner/worker_test.go
This PR changes the frequency of when announce messages are sent.  Also, it will now send an announce message on istanbul engine start.
The exact times when the message is sent is described here:  https://github.com/celo-org/celo-blockchain/issues/790
Created a testnet and verified that the announce messages are only sent on the intended events.
None
- Fixes #790 
Yes
=> changed announce message frequency

consensus/istanbul/backend/engine.go, consensus/istanbul/core/core.go, consensus/istanbul/core/handler.go, consensus/istanbul/core/types.go, consensus/istanbul/types.go, consensus/istanbul/types_test.go, consensus/istanbul/validator.go, consensus/istanbul/validator/default.go
Side work while adding the RPC for Istanbul RoundState.
* Add `AsData()` and Json Encode/Decode
* Cleanup Methods
* Reorder methods in file
In  `istanbul/core/types.go`
* Add test for RLP encode/decode for each type
* Remove unnecessary custom RLP encode/decode functions
* Comments to separate types / interface implementations
* Add `CurrentRoundState()` to engine (will be used for the RPC)
* Remove `Sequence()` form engine. Replace with existing `CurrentView()` call
* Move getter method from `handler.go` to `core.go` where all others live
* Reorder methods in `core.go`. First public methods, then private methods.
Unit tests, CI
=> Istanbul Core Cleanup & Testing

consensus/istanbul/backend/api.go, consensus/istanbul/core/core.go, consensus/istanbul/core/message_set.go, consensus/istanbul/core/roundstate.go, consensus/istanbul/core/roundstate_save_decorator.go, consensus/istanbul/core/roundstate_test.go, consensus/istanbul/types.go, consensus/istanbul/validator.go, consensus/istanbul/validator/default.go, internal/web3ext/web3ext.go
Add RPC to query RoundState information
A few clean ups: 
* Change "self" variable to a sensible name on a few types
* Rename GetAddressesFromValidatorList to MapValidatorsToAddresses
* Remove istanbul.Validators type (almost not used)
* Tested Summary generation and Json Marshalling. 
* Need to test the actual RPC call on an living environment
=> Add RPC to query RoundState information

consensus/istanbul/validator/default.go
Add a comment to explain `MinQuorumSize` and `F`.
Yes
=> Explain Q and F

consensus/istanbul/backend/backend.go, consensus/istanbul/core/core.go, consensus/istanbul/core/handler.go, consensus/istanbul/logger.go
Implements new logger wrapper to log all messages if `round > 1` , specifically high verbosity `trace` and `debug`.
Running CI
Changed instances within `istanbul.backend.backend.go` and `istanbul.core.core.go` that were using `log.{log_level}` rather than `sb.log.{log_level}` or `c.log.{log_level}`
* Fixes #799
=> Log all levels if round > 1

cmd/geth/main.go, cmd/geth/usage.go, cmd/utils/flags.go
Adds ProxyAllowPrivateIPFlag, which specifies whether private IP is allowed for external facing proxy enodeURL.
Tested that celotool deployed testnet comes up rather than fatal "Proxy external facing enodeURL (%s) cannot be private IP.".
=> Add ProxyAllowPrivateIPFlag

core/state_transition.go, internal/ethapi/api.go
Currently gas estimation does not work for accounts with low balance, as is the case for new accounts invited to Celo with an invite code. The issue is that the binary search used for gas estimation makes an assumption that if there is an error, raising the gas limit on the transaction will fix it, or that the transaction will always fails. This assumption is broken when the gas price is non-zero and the account does not have a high enough balance to pay fees for a transaction with maximum gas. In that case there is only a window of gas values that will work, which cannot be found via binary search.
It would be easy to set the gas price to zero and run the transaction, which solves the issue mentioned above, but the gas price minimum functionality prevents the transaction from running.
1. …
=> add special state transition to allow for gas estimation

p2p/server.go
This is a cherry-pick of https://github.com/ethereum/go-ethereum/pull/20573, which fixes an issue where discovery queries would hang indefinitely if the connection was refused, resulting in future discovery queries never happening. This adds a timer to ensure discovery queries still happen every 30 seconds.
I ran without this commit and added some log messages, and saw that a discovery query to an inaccessible bootnode only happened at node startup and never again (I let it run ~10 min). I then ran with this commit and saw discovery queries to the inaccessible bootnode would occur every ~30 seconds.
n/a
n/a
This is backwards compatible with the rest of 1.9
=> p2p: ensure Server.loop is ticking even if discovery hangs

core/blockchain.go, core/blockchain_test.go
I'm seeing a weird off-by-one error in https://github.com/celo-org/celo-blockchain/pull/844, so to move on, this PR just increases the TrieInMemory Limit to exceed the epoch size for now. This is meant as a temporary solution and should be fixed with https://github.com/celo-org/celo-monorepo/issues/2625
=> Higher trie limit

consensus/istanbul/core/roundchange_test.go
Relax the `TestPeriodicRoundChanges` requirement that a block is finalized on the next around after gossip is re-enabled, to within two rounds.
For the #847 epic we want to avoid relaxations and resolutions that only make a failure less likely to occur, rather than conclusively resolved. I gathered logs of the round timeout failure case (separated by giving each validator it's own logger), which I'm attaching. (A "GossipEnabled" log has been added.)
[run28-vali0.txt](https://github.com/celo-org/celo-blockchain/files/4167640/run28-vali0.txt)
[run28-vali1.txt](https://github.com/celo-org/celo-blockchain/files/4167641/run28-vali1.txt)
[run28-vali2.txt](https://github.com/celo-org/celo-blockchain/files/4167643/run28-vali2.txt)
[run28-vali3.txt](https://github.com/celo-org/celo-blockchain/files …
=> Relax TestPeriodicRoundChanges requiring next round to within two rounds

consensus/istanbul/backend/backend.go, consensus/istanbul/backend/handler.go, consensus/istanbul/backend/handler_test.go
Proxies that receive a consensus message from a non validator now return an error. 
Added unit testing to verify that messages not signed by a validator are ignored, whereas those that are signed are properly forwarded to the proxies' validator.
Added comments to present more context on proxy setup (will be removed with multiproxy).
- Fixes #651
Yes
=> Proxies should ignore consensus messages from non validators

accounts/accounts.go, accounts/external/backend.go, accounts/keystore/wallet.go, accounts/scwallet/wallet.go, accounts/usbwallet/wallet.go, miner/worker.go
*Note*: this is merging to Tim's 1.9 branch
Geth 1.9 removed `SignHash` from the `Wallet` interface, breaking our deterministic randomness scheme used in case a validator looses their data. Since there is a network running on which it is expected that validators will upgrade from 1.8 to 1.9, we need a temporary fix that will reintroduce the same randomness generation scheme.
Ran a local testnet with 1.8 instances, restarted validator0 with current Tim's 1.9 branch and successfully reproduced the randomness issue, restarted validator0 again with this branch and successfully mined blocks.
- Fixes #859 
Fixes a backwards incompatibility introduced by `timmoreton/geth_1.9`.
=> Reintroduce Wallet.SignHash

node/defaults.go
Folks on Discord were running into an issue when starting the node where the node would refuse to start with the default MaxPeers (50) being less than the default light client MaxPeers (99).
Ran geth with default values & node started up
n/a
n/a
Yes :)
=> Increase MaxPeers to be greater than light client MaxPeers

.circleci/config.yml, Dockerfile.android, build/ci.go, go.mod, mobile/bind.go
The work here to fix mobile build (iOS/Android) was done on top of https://github.com/celo-org/celo-blockchain/pull/511
- Use Go 1.13 on mobile
- Remove bitcode patch, bitcode is now disabled in gomobile for Go < 1.14
- Fix `gosigar` build on iOS https://github.com/elastic/gosigar/compare/master...celo-org:jeanregisser/fix-ios-build
- Fix gobind build error on iOS due to different parameter names in the generated ObjC code of the `Sign` method between `Signer` and `MobileSigner`
- Don't wait for `build-geth` step to to build `ios` and `android`, this is so we don't have to wait unnecessarily when we need to debug them
- iOS and Android compile again locally and on CircleCI
- was able to sync, redeem invite, verify number, send money using geth 1.9 connected to alfajores on iOS
- Updated …
=> Fix mobile build for geth 1.9

scripts/run_geth_in_docker.sh
As discussed in  https://github.com/celo-org/celo-blockchain/issues/857, the run script used in the Docker container prevent SIGINT from being passed through correctly. This PR uses `exec` when starting geth to ensure signals are passed correctly, and to conform to the "one process per container" best practice.
Built and ran the docker container locally. Confirmed it starts, and receives SIGINT as desired.
- Fixes https://github.com/celo-org/celo-blockchain/issues/857
100%
=> Use exec in geth start script to pass signals correctly

consensus/istanbul/backend/backend.go, contract_comm/random/random.go, params/protocol_params.go
Currently, we are trying to fetch the randomness of the last epoch block to determine the validator set order (to know who is supposed to propose). However, we only store the last 128 tries by default, which causes us not to be able to retrieve the state of the epoch block, and thus not be able to fetch the randomness.
This PR suggests one solution to this problem. It actually uses the state of the current block and takes advantage of that fact that we are storing historical randomness on the contract itself. The window on baklava is 720 blocks right now, and the epoch size is 720. To avoid off-by-one error, we'll probably need to run a governance proposal to set it to something higher.
The alternate solution to this would be to increase the `TriesInMemory` default to something larger …
=> Use contract historical randomness

core/blockchain.go, core/blockchain_test.go
Reverts celo-org/celo-blockchain#845
Fixes #854
Historical randomness should now be handled by #844 and https://github.com/celo-org/celo-monorepo/pull/2685
=> Revert "Higher trie limit"

.circleci/config.yml, core/state_transition.go, go.sum, params/protocol_params.go
Tx cost payments with non-gold were changed to minimize the number of emitted events and EVM contract calls.
The CI in monorepo is currently pointing here.
- Fixes https://github.com/celo-org/celo-labs/issues/265
Not backwards compatible with old contracts.
=> Gas payment change for audit issue M02

consensus/istanbul/backend/announce.go, consensus/istanbul/backend/backend.go, consensus/istanbul/config.go, consensus/istanbul/core/core.go, contract_comm/election/election.go, params/protocol_params.go
Currently, all registered validators will broadcast their enodeURL to all other registered validators and currently elected validators.
To decrease the exposure of those enodeURLs, this PR contains changes so that the enodeURL is broadcast to the next threshold's elected validators + 10 validators that are just below the election cutoff.
* e2e CI tests.
* Ran a testnet with 10 elected validators and 30 registered validators, and verified that the enodeURL is shared with only 20 nodes.
Yes.
=> Decrease announce validator set size

.circleci/config.yml, consensus/istanbul/backend/pos.go, consensus/istanbul/core/core.go, contract_comm/epoch_rewards/epoch_rewards.go, params/protocol_params.go
Adds epoch payments to carbon offsetting partner as described in design doc.
Added e2e test for carbon offsetting partner payment.
- Part of Epic #2670 Epoch rewards implementation matches design doc
No, changes the expectation of the smart contract interface.
=> Pay epoch rewards to carbon offsetting partner

core/tx_pool.go, light/txpool.go
The frozen gold transfer check in validateTx() of tx_pool queries smart contracts for the isFrozen boolean and address whitelist. Currently, this check occurs before ensuring the transactor's balance covers the gas cost. @nategraf pointed out that this might open up a potential denial of service vector, as someone could send many transactions attempting to transfer gold without actually having the requisite gas, each of which would trigger these relatively slow reads from layer 2. This PR addresses this concern by simply rearranging the order of the checks. 
Tests for gold transfer freezing already exist in e2e transfer_tests in celo-monorepo.
None.
- None
Yes.
=> Moves frozen gold transfer check after check that transactor balance covers gas

ethstats/ethstats.go
When a node is started it will start connecting to celostats, if it connects to celostats with an locked account it will fail to connect. Therefore every nodes does two connection attempts which creates a lot of noise on celostats.
Tested by running a local testnet with celotool and celostats locally
It should not. break anything
=> fixed double connect on node start

consensus/istanbul/backend/pos.go
Currently if distributing rewards to an individual validator fails, reward distribution to other validators stops, without error. This PR changes that to log an error and continue instead.
E2e tests
- Related https://github.com/celo-org/celo-labs/issues/306
Potentially a hard-fork
=> Continue to distribute rewards if a single validator fails

accounts/usbwallet/ledger.go, accounts/usbwallet/trezor.go, accounts/usbwallet/wallet.go, cmd/geth/accountcmd.go, core/types/transaction_signing.go
Tested using a Ledger Nano S, with the `proof-of-possession` command. Test cases:
1. Signer address on a Ledger
2. Signer address in keystore
3. Signer address nowhere
=> Adds Ledger ECDSA proof of possession

core/state_transition.go, core/vm/contracts.go, params/protocol_params.go
Hopefully the precompile gas costs are now good enough. Many of them have basically no cost (calling precompiles costs anyway). The cost of verifying aggregated seals should be checked later when we have a new network running.
- Fixes #901
=> Benchmarking precompiles, setting other parameters

cmd/utils/flags.go, eth/backend.go
`FullHeaderChainAvailable` was false by default, this might have caused some erroneous behavior.
Only manual testing.
=> Set FullHeaderChainAvailable according to sync mode

contract_comm/evm.go
`contract_comm` uses a map of registered timers to record metrics for EVM calls. Prior this this PR, the map is used in a thread-unsafe way which can result in a panic if two threads make a call system call simultaneously.
When writing this function originally I overlooked the built in `metrics.Registry` which is designed for concurrent access. This PR uses the registry to avoid this issue.
e2e tests
100%
=> Use metrics registry to prevent unsafe map access

.circleci/config.yml, cmd/geth/consolecmd_test.go, cmd/geth/main.go
During the Stake Off we released a new image based on 1.9 and one of the other changes we included was to change the client identifier of `geth` to `Celo`. Although not incorrect, the capital letter does not match the other client identifiers in use, namely `celoios` and `celoandroid`. This in itself is fairly inconsequential, but does have the side effect that the directory in which chain data is stored is set based on the client identifier. This means that the directory name was capital `Celo` rather than `celo` which would be more standard on Linux filesystems where casing matters. This led to confusion from Stake Off participants.
https://github.com/celo-org/celo-blockchain/blob/f4f8cf938fb28f7571d3c77cdcad9da4d5876b78/node/node.go#L299-L316
This PR changes the default client …
=> Change clientIdentifier to "celo" from "Celo"

core/vm/eips.go
This removes EIP 1884 gas changes from the Istanbul hard fork.
=> Cancel istanbul gas changes

consensus/istanbul/backend/backend.go, consensus/istanbul/backend/handler.go, consensus/istanbul/core/core.go, consensus/istanbul/core/roundstate.go, core/blockchain.go
Add metrics to make it easier for Validators to monitor consensus progress, and when their validator is not signing blocks.
For the *parent* of the last sealed block received (i.e. this is always 2 fewer than the current consensus sequence):
* `consensus_istanbul_blocks_elected` - counts the blocks for which this validator was elected
* `consensus_istanbul_blocks_missedbyus` -  counts the blocks for which this validator was elected but not included in the child's parent seal (i.e. this block will count as "downtime") 
* `consensus_istanbul_blocks_signedbyus` -  counts the blocks for which this validator was elected and its signature was included in the seal (i.e. this validator completed consensus correctly, sent a COMMIT, its commit was received In time to make the seal of the parent …
=> Add/fix metrics for consensus and block signing 

.circleci/config.yml
https://github.com/celo-org/celo-blockchain/pull/941 relied on changes to e2e tests in https://github.com/celo-org/celo-monorepo/pull/3216. Once that PR is merged, this PR may be merged to reset CI back to pointing at `master`
=> Point CI back to monorepo master

accounts/usbwallet/wallet.go
For the proof of possession the message to be signed by the signPersonalMessage from the Ledger, should be a hash, not an address
=> [Wallet Ledger] Fix proof of possession sign

.dockerignore
Build output from geth & rust compiler are removed from the docker
context.
=> Ignore build output on Docker Context

go.sum, rpc/http.go
Found an error message like:
```
http2: Transport: cannot retry err [http2: Transport received Server's graceful shutdown GOAWAY] after Request.Body was written; define Request.GetBody to avoid this error
```
So, this PR implements GetBody
Discovered, fixed and tested while developing rosetta
=> Fix error when using http2

.circleci/config.yml
Walletkit has been removed from the monorepo, this PR fixes the `checkout-monorepo` step on CircleCI which was still referencing it.
=> Fix monorepo build now that walletkit has been removed

consensus/istanbul/backend/pos.go
Looks like this can be nil, added a check for that.
- Fixes #940
=> Added check if ReadAccumulatedEpochUptime returns nil

consensus/istanbul/core/core.go
EpochSnarkData is empty on non-epoch blocks, so no reason to aggregate it.
=> Don't aggregate epochSnarkData on non-epoch blocks

core/blockchain.go, miner/worker.go
In 16e1c70f363451b66712a99540bc03716d93c565 the side chain event handling code, which dealt with uncle blocks, was removed from `miner/worker.go` and an error was put in its place, as we did not expect that code path to ever execute. It turns out, it does execute under an innocuous race condition in which a block is inserted via the `Blockchain.insertChain` and returned to the result channel of `miner/worker.go` simultaneously. This will result in the same block being written to the database twice, which the second being considered a side chain event, but it does not cause any further issues.
As a result, this PR reduces the log level on that error to a debug statement. I refrained from removing the channel because that could have unintended consequences while a logging change along is …
=> Elevate reorg log message and suppress innocuous side chain error message

.circleci/config.yml, consensus/istanbul/backend/pos.go, contract_comm/gold_token/gold_token.go, core/vm/contracts.go, params/protocol_params.go
The rationale behind this, is the `Gold.mint()` emits an event, and thus
is traceable, while `state.AddBalance()` is not. Making it really hard
to figure out how much GoldToken was minted and to whom.
Companion PR https://github.com/celo-org/celo-monorepo/pull/3307
CI e2e
=> Use Gold.mint() instead of state.AddBalance() for epoch rewards

params/version.go
This PR updates the version number to `1.0.0-unstable` as version `0.10.0-stable` has been released and the new planned release is `1.0.0-stable`.
=> Update version to v1.0.0-unstable

CeloBlockchain.podspec
Fix missing reference to libbls_crypto causing linking errors on iOS
Compilation works again on iOS.
Yes.
=> Fix missing reference to libbls_crypto causing linking errors on iOS

core/state_transition.go, core/vm/evm.go, core/vm/instructions_test.go, core/vm/interpreter.go
Tested rosetta-validator syncs instead of getting stuck on block 103858.
=> Only run primary EVM call with tracer

consensus/istanbul/core/commit.go
Small fix for a potential issue that can really on crop up at the very start of the network.
When on the first round of consensus, sending an old commit message can cause an underflow when looking for the validators of the parent block of the current block. The parent block does not exist for the genesis block, therefore when this code path is triggered before the first commit, malicious nodes could send a commit for the n = 0 block.
Not specifically tested.
Don't commit previous sequence while on seq 0
When on the first round of consensus, sending an old commit message can
cause an underflow when looking for the validators of the parent block
of the current block. The parent block does …
=> Don't commit previous sequence while on seq 0

.github/pull_request_template.md, .mergify.yml
Change mergify config and PR template to use PR body and title in automerge commits and fix name mismatches in CI test names.
=> Update mergify to use PR title and body as commit message

accounts/accounts.go, accounts/external/backend.go, accounts/keystore/wallet.go, accounts/scwallet/wallet.go, accounts/usbwallet/ledger.go, accounts/usbwallet/trezor.go, accounts/usbwallet/wallet.go, cmd/geth/accountcmd.go
This allows users to confirm the address they receive from other commands are an address that exists on the Ledger, confirming the Ledger actually contains the address private key.
The command format is `geth account confirm-address ADDRESS`.
Tested that normal transaction sending and proofs-of-possession are not affected and that when running the confirm-address command the address is displayed on the Ledger.
This is backwards compatible.
=> Adds address confirmation to Ledger

eth/handler_test.go
The broadcastblock unit tests fails sometimes when --coverage is used.  This PR should reduce the frequency of failures.
None
Ran unit tests and CI tests.
Relates to the fixing of flaky tests effort.
Yes
=> Increase timeout for broadcastblock test

consensus/istanbul/backend/backend.go, consensus/istanbul/backend/handler.go
Add metric for number of blocks observed that are proposed by us:
```
consensus_istanbul_blocks_proposedbyus 5
```
And a metric for the validator set size:
```
consensus_istanbul_blocks_validators 4
```
Added a log message specifically when we've missed signing a block, to provide options for log-based monitoring.
Ran e2e tests.
Yes
=> Add metrics for total validators, blocks proposed

core/state_transition.go, core/vm/evm.go, core/vm/instructions_test.go, core/vm/interpreter.go
Update `distributeTxFees()` and `TobinTransfer()` to filter their EVM operations from transaction trace when debugging is enabled.  The issue is similar to https://github.com/celo-org/celo-blockchain/pull/938 but occurring at EVM depth 1 instead of depth 0.
- Cosmetically updates idiom in `debitGas()` and `creditGasFees()`.
- Updates `EVMInterpreter` to use a pointer to `evm.config` instead of copying by value. 
Unit and e2e tests.
- Fixes issue where Blockscout thinks normal transaction failed if associated Tobin tax transfer reverts.
Yes.
=> Run only primary EVM call with tracer

go.mod, go.sum
This issue https://github.com/golang/go/issues/36622 started causing crashes for us. Tested the fix with a new android build and it does not crash any more
=> Update sys lib to prevent arm64 crash

cmd/geth/main.go, cmd/geth/misccmd.go, cmd/utils/flags.go, consensus/consensus.go, consensus/istanbul/backend.go, consensus/istanbul/backend/announce.go, consensus/istanbul/backend/announce_test.go, consensus/istanbul/backend/backend.go, consensus/istanbul/backend/engine.go, consensus/istanbul/backend/gossip_cache.go, consensus/istanbul/backend/handler.go, consensus/istanbul/backend/handler_test.go, consensus/istanbul/backend/message_senders.go, consensus/istanbul/backend/peer_handler.go, consensus/istanbul/backend/val_enodes_share.go, consensus/istanbul/backend/val_enodes_share_test.go, consensus/istanbul/config.go, consensus/istanbul/core/core.go, consensus/istanbul/core/testbackend_test.go, consensus/istanbul/errors.go, consensus/istanbul/protocol.go, eth/backend.go, eth/handler.go, eth/handler_test.go, eth/helper_test.go, eth/peer.go, eth/protocol.go, ethstats/ethstats.go, internal/web3ext/web3ext.go
This PR removes the announce protocol's and establishment of proxy connection's dependency that the machines local time is greater than or equal to the network start time set in the genesis file.
Started effort in splitting up some of the `istanbul.backend`'s bulky files.  Specifically, does the following:
1. moved all of the new eth message codes into `istanbul/protocol.go` and any related utility functions
1. created new file for the gossip caches
1. created new file for the message sender functions
1. Removed the `candidates` property from the istanbul rpc api
1. Deployed a testnet with a start timestamp about half an hour in the future.  Then ensured that the validator connections were established beforehand and that the testnet started validating at the start timestamp.
2. Unit tests …
=> Remove start time dependency for announce protocol and proxy

.circleci/config.yml
Use the generated `dependency-graph.json` file from the monorepo to only build packages needed to run the e2e tests. Depends on [this](https://github.com/celo-org/celo-monorepo/pull/3876) PR because we had a missing dependency.
Ran a few builds in CI.
N/A
=> feat: only build monorepo packages needed to run e2e tests

ethclient/ethclient.go, internal/ethapi/api.go
Extends the `eth_gasPrice` rpc to optionally accept a `feeCurrency` address. 
NOTE: an empty string `feeCurrency` parameter will cause an error
None
Tested with Postman.
- Fixes #926
Should be backwards compatible with all existing javascript clients.
=> Extend existing eth_gasPrice with feeCurrency

.circleci/config.yml
Point CI back to master after merging #1045 and https://github.com/celo-org/celo-monorepo/pull/3870
=> Point CI back to celo-monorepo master

go.mod, go.sum, metrics/cpu_disabled.go, metrics/cpu_enabled.go
We're currently using a fork of `gosigar` due to an issue with building it for iOS. In the meantime there has been a change in upstream geth that fixes the issue with the dependency and allows us to stop using our fork.
The problem with the current workaround is that it affects all `darwin` builds.
The patch in question: https://github.com/ethereum/go-ethereum/commit/42e02ac03bfc4e01496d15314e94f46260d98f86
This PR just cherry-picks the patch from `geth` and removes the go.mod override.
We need to be 100% sure that this patch doesn't affect the iOS build. 
- Blocks #1073
=> Update gosigar usage

.circleci/config.yml
This is to make `yarn install` work with changes done in https://github.com/celo-org/celo-monorepo/pull/4282
which requires `rsync` tool to be installed.
None
`yarn install` works on CircleCI
None
Yes
=> Use celohq/node10-gcloud:v3

.circleci/config.yml
Some recent change to `celo-monorepo` introduced dependencies that need to be installed from github over ssh and thus we need to add and verify the github.com ssh keys in order to avoid the classic:
```bash
The authenticity of host 'github.com (140.82.113.3)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no)? 
``` 
> Props to @valer-cara for some help with the ssh-fu
=> Fix CI issue on celo-monorepo yarn install

Dockerfile.binaries, build/ci.go, cloudbuild-binaries.yaml, internal/build/env.go
This PR includes the necessary bits to setup a CI pipeline that cross-compiles all geth tools into release binaries for the platforms we want/support. Currently these are:
- ✅Linux 32bit/64bit
- ✅Darwin 32bit/64bit (~pending on #1082~ merged!)
- ✅Windows 64bit (~pending on celo-bls-go v0.1.6 release~ ~pending on #1089~ merged!)
Elements of the PR:
- `Dockerfile.binaries` for the container where cross-compilation occurs. It's based on a [fork of xgo](https://github.com/techknowlogick/xgo), and includes some back-ported mingw packages for the windows build.
- Changes to the `geth` build scripts:
- Introduce a new CI environment in `internal/build/env.go` which which can be used for Google Cloud Build.
- Create a new ci task in `build/ci.go` that bundles the binaries into well named release …
=> Setup binary release CI pipeline

.circleci/config.yml
In bash if you do: 
```bash
set -e
cmd1 | cmd2
some_other_cmd
```
The script will exit after the pipe if `cmd2` fails.
Hover if you do:
```bash
set -e
cmd1 | cmd2 && echo "Ok!"
some_other_cmd
```
The script will **not** exit anymore if `cmd2` fails but will continue running. For some reason the result of that expression doesn't trigger the `set -e`
... the more you know. 
More info on the topic [here](https://unix.stackexchange.com/questions/447519/has-anyone-tried-to-write-a-shell-that-fixes-errexit-set-e/447651#447651).
Also I had an env var in single quotes and was expecting it to be substituted 🤦
=> Remove useless echo that was causing the script to never fail

consensus/istanbul/backend/engine.go, core/blockchain.go
When DB is corrupted, removes all blocks that have no associated states.
Added a check to avoid segfault when quitting with interrupt.
Only manual testing.
- Fixes #1051
=> Remove broken blocks

core/types/block.go, internal/ethapi/api.go
While the data exists in the block body, the API did not expose it.
=> Adds epochSnarkData to getBlock API

consensus/istanbul/backend/engine.go, consensus/istanbul/backend/engine_test.go
VerifyHeaders() is used to verify new headers in batch obtained from peers.
To do the verification it uses `1..n` headers in batch to verify header
`n+1` in the batch.
The problem is that if some of if `1..n` header are invalid, it will still use them
for the verification. This can be potentially be used to attack a node's
validatorSet cache for the next epoch.
This commit fix this, by failing fast. When the first invalid header is
encountered, all subsequent headers on the batch will fail with `ErrUnknownAncestor`
Yes
Kudos to @kevjue @gakonst @mrsmkl for their help on finding and fixing this problem
=> Fix use of potentially invalid headers to verify new headers

eth/peer.go, p2p/metrics.go, p2p/peer.go, p2p/peer_test.go, p2p/server.go
Add number of active (connected) peers metrics discriminated by purpose (validator & proxy).
With this, we should be able to monitor how many validator or proxy connection a node currently has.
Refactors PurposeFlag use:
* Make it immutable, thus easier to track
* Use `Add` , `Remove` vs `Set(bool)`
* Peer now has a single purpose which is the combination of
trustedPurposes & staticPurposes
CI, manual
=> Add peer connection metrics by peer purpose

eth/peer.go, eth/protocol_test.go
Update the message on the genesis mismatch error reported when syncing to a node with a different genesis block hash to clarify which reported hash is the local, and which is the remote peer.
Unit tests
- Fixes https://github.com/celo-org/celo-monorepo/issues/4603
=> Clarify the message on the genesis mismatch error

les/metrics.go, les/serverpool.go, p2p/dial.go, p2p/discover/metrics.go, p2p/discover/v4_udp.go, p2p/metrics.go
Adds new metrics to the existing ones; with the objective of better understanding discovery. 
```
les_client_discovered
discover_ingress
discover_egress
p2p_serves_handshakes
p2p_dials_handshakes
```
No
CI
Yes
=> Adds new metrics for discovery

consensus/istanbul/backend/api.go, consensus/istanbul/validator.go, crypto/bls/bls.go, internal/web3ext/web3ext.go
The Plumo prover needs a list of the BLS public keys for epochs in order to create the witness for the proof.
=> Adds "get validator public keys" endpoint

.circleci/config.yml, consensus/istanbul/backend/handler.go, consensus/istanbul/core/handler.go
A few messages I've seen reported frequently on Discord have misleading log levels. This PR makes some small log level adjsutments for messages that are `Info` or `Error` but should be `Warning`.
=> Adjust log levels on a few common messages

eth/config.go, internal/web3ext/web3ext.go
Yesterday I used the `dumpconfig` command to generate a `config.toml` file and tried to use it to run a Geth node with `geth --config config.tml`, but got a decoder error. This PR includes a fix for the error in that flow.
* Sorted some methods in `web3ext.go` alphabetically
Ran a node locally with the generated `config.toml`
=> Fix IstanbulOverride decoding error when trying to use config.toml

core/tx_pool.go, core/tx_pool_test.go
This is a cherry pick merge of this geth upstream PR:  https://github.com/ethereum/go-ethereum/pull/21300
During load tests, we saw that txns were being very aggressively evicted from the txpool (in some cases evicted within a second of being added to it).  This caused the submitted txn to never be propagated throughout the network.  Also, based on how our load tests are designed, this bug was preventing us to saturate the block chain.
After making this change, our load tests are able to saturate the block chain.
As part of the original upstream PR, there are unit tests that verify that txns are not evicted early.  Also, our load tests is able to confirm that the txns are not evicted early (and hence can saturate the chain).
Is backwards compatible
=> Fixed the aggressive eviction of txns in txn pool

mobile/geth.go
Set NoUSB to true on mobile to remove unnecessary log lines
=> Set NoUSB to true for mobile

params/protocol_params.go
Improved legibility of Celo-specific constants. In order to avoid breaking compatiblity with upstream, non-Celo-specific params have been left as-is
Local tests. Would appreciate more manual inspection to be sure all constants are unchanged.
=> chore: parameter constant expression cleanup

params/config.go
Added the IsCelo1 function to the chain config. Future changes included in the Celo1 hard fork (name is yet to be defined) will use this to decide whether the fork is active or not.
=> Celo1 hard fork field added to config

consensus/istanbul/backend/peer_handler.go
This is a partial fix for #948.  That issue mentions that we aren't removing validators if we're not connected to them at that moment.  But there was another bug which caused `ReplaceValidatorPeers()` to not disconnect validators at all.  This PR fixes that bug.
Notes:
1. This bug only affected `ReplaceValidatorPeers()`, whereas the problem of not removing validators we're not connected to right then affects both `ReplaceValidatorPeers()` and `ClearValidatorPeers()`.
2. A full fix for #948 will require some new code in `p2p/server.go` an `p2p/dial.go`, which we probably don't have time to do before the upcoming release (and which would be best done after cherry-picking https://github.com/ethereum/go-ethereum/pull/20592 from upstream).  That's why I'm opening this PR to at least fix this …
=> Fix disconnecting unelected validators in ReplaceValidatorPeers()

consensus/istanbul/protocol.go, eth/backend.go, eth/handler.go, p2p/peer.go, p2p/server.go
https://github.com/celo-org/celo-blockchain/pull/333 introduced a concept of a protocol being primary, which means that it is not run alongside any other protocol on the connection between two nodes.  But, in its implementation, if any version of istanbul is marked as primary, all versions of istanbul are treated as primary.  This PR updates the way the primary protocol concept is implemented so that versions 64 and 65 primary (to maintain backwards compatibility), but newer versions will not be.  This will enable running future versions of istanbul alongside other protocols such as LES or a separate proxy-validator protocol if we were to break that away from istanbul.  And, at a later time when versions 64 and 65 need not be supported, we can remove the concept of primary protocol …
=> Make primary protocol concept apply to specific versions of istanbul

scripts/publish-mobile-client.sh
Update the path of `libbls_snark` for publishing the mobile client. This is trying to fix the last CI step on master.
Confirm that libbls is at the given path, but can't easily check that this works until it's merged into master.
- Fixes #1199
yes
yes
=> Update the path for libbls

p2p/dial.go, p2p/dial_test.go
In #1192, we pulled in the the new dial scheduler from upstream, but modified it to exempt static dials from the limits it put on them (which were set as `maxDialPeers` and `maxActiveDials`), because we rely on static dials for the connections between validators/proxies and their validator/proxy peers.  This PR modifies that to make them respect the `maxActiveDials` limit.  So, while static dialed connections will still be exempt from `maxDialPeers` (and therefore from `maxPeers)`, the establishing of those connections will not be allowed to push the number of active dials being attempted past its limit (whose default value was set to 50 upstream).  
Note that, prior to the new dial scheduler (i.e. in celo-blockchain 1.1.0 and earlier and in the corresponding code upstream), the …
=> Make static dials subject to the maxActiveDials limit.

ethstats/ethstats.go
The channel needs to be buffered, so that if a timeout occurs the goroutine would still be able to terminate.
Fixes a goroutine leak spotted by @zviadm.  Note that this leak is new, and was not present on v1.1.0.
Not tested directly, but build and unit tests pass.
- Fixes the issue mentioned in #1204
No effect on protocols, so no backwards compatibility concerns.
=> Fix goroutine leak in celostats login.

consensus/istanbul/proxy/proxy_engine_test.go
The TestHandleEnodeCertificateMessage proxy package unit test was failing about 1/3 of the time since it was not waiting long enough for the proxy engine's startup process.
None
Ran the failing unit tests 5 times sequentially, and it didn't fail:  `go test ./consensus/istanbul/proxy -count 5`
None
Yes
=> Fix intermittent failure of TestHandleEnodeCertificateMessage unit test

p2p/server.go
This increment was moved a few lines lower down in the function in the upstream commit, but during the conflict resolution for #1192, I missed removing it here, so it became duplicated.
This was a bad merge on my part in PR #1192, resulted in this if block being duplicated (it is present a few lines below this), which is rectified here.
Not specially tested, very clear fix of a bug.
=> Fix duplicated code from bad cherry-pick conflict resolution.

cmd/devp2p/discv4cmd.go
This flag was added in #511, but wasn't working. It is required for the `discv4` subcommands to work properly for Celo networks.
#436 added a `networkid` check to the discovery v4 protocol, making it so that nodes from different networks (e.g. mainnet vs baklava) won't discover each other.  The `devp2p discv4` command, with its various subcommands, needs to know the `networkid` it should use.  However, the CLI flag for it wasn't properly configured, so this PR fixes that.
I came across the problem when trying out the crawl subcommand as described at https://geth.ethereum.org/docs/developers/dns-discovery-setup
The following are the results of running `discv4 ping` with the enode of our mainnet v4 bootnode.
1. `master`, when passing the mainnet networkid:
```
❯ ./build/bin/devp2p discv4 …
```
=> Fix --networkid option of 'devp2p discv4' command.

consensus/istanbul/backend/handler.go
Fixes an error added in a refactor that kept an old way of receiving a message to be signed by the validator, from a proxy, to be sent to celostats
Upload a testnet with multiple escenarios of [validators, n-proxies], validators without proxies, and their celostats server.
Monitored the data and the logs of the validators, and everything was working properly.
=> Fix delegateMsg handle

internal/ethapi/api.go
Follow-up to https://github.com/celo-org/celo-blockchain/pull/1214, I found that returning the error when the transaction is not found is not the behavior expected by clients and leads to difficult to debug behavior. This fix aligns with upstream and client expectations.
Prior #1214 and this PR, `eth_getTransactionReceipt` did not work on light clients because the API implementation was checking for the given transaction in the local `rawdb` rather than using ODR, as it was doing for `eth_getTransaction`. As a result any query for a transaction that was not otherwise cached would always return `nil`. With these PRs, this is fixed so that the transaction is retrieved via ODR, as expected.
=> Fix behavior of eth_getTransactionHash for pending transactions

.circleci/config.yml, .travis.yml, Dockerfile, Dockerfile.alltools, Dockerfile.android, Dockerfile.arm64, Dockerfile.binaries, README.md, appveyor.yml, build/checksums.txt, docs/docs/_developers/devguide.md, go.mod, go.sum, p2p/discv5/node_test.go
This cherry-picks some commits from upstream, and adds some additional changes in a separate commit, to:
1. Become compatible with Go 1.14.x
2. Use the latest 1.14.x version in the CI and the dockerfiles
The idea is to then switch to v1.14.12 when it is released.
The changes from upstream are very minor:
1. Upgrading a dependency version
2. Fixing a test to work with 1.14
For now, I am creating this as a draft PR with "do not merge".  I believe what we should eventually do, rather than merge it to `release/1.1.0`, is create a new branch from it (e.g. `release/1.1.1`) and merge this PR onto that.  cc @trianglesphere 
Unit tests and e2e sync tests pass.
No significant
=> Update release/1.1.0 branch for Go 1.14.x

.circleci/config.yml, .travis.yml, Dockerfile, Dockerfile.alltools, Dockerfile.android, Dockerfile.arm64, Dockerfile.binaries, README.md, appveyor.yml, build/checksums.txt, docs/docs/_developers/devguide.md, go.mod, go.sum, p2p/discv5/node_test.go
This cherry picks the PR that was merged onto the 1.1 branch (https://github.com/celo-org/celo-blockchain/pull/1222) so that we can also use it for a 1.2.2 release off master.
* go.mod: update golang.org/x/crypto to fix a Go 1.14 race rejection
Cherry-pick conflicts:
go.mod
go.sum
* p2p/discv5: fix test on go 1.14 (#20724)
Cherry-picked to celo-blockchain
* travis, appveyor, build, Dockerfile: bump Go to 1.14.2 (#20913)
* travis, appveyor, build, Dockerfile: bump Go to 1.14.2
* travis, appveyor: force GO111MODULE=on for every build
Cherry-pick conflicts:
.travis.yml
appveyor.yml
build/checksums.txt
* Update CircleCI and dockerfiles to use Go 1.14
* Revert ios build CI config to work with Go 1.13
* Update golang download links to 1.14.12
Co-authored-by: Péter Szilágyi <peterke@gmail.com> …
=> Update for Go 1.14.x

consensus/istanbul/backend/handler.go, consensus/istanbul/proxy/proxied_validator_engine.go, consensus/istanbul/proxy/types.go
The proxied validator engine was not being notified of a new epoch, causing that engine to not be aware of any new validator set diffs, and consequently not assigning new validators to it's proxies and never connecting to them.
None
- Unit tests
- Deployed patch to a few clabs validators and verified that they started signing all of their blocks.
Yes.
=> Notify proxied validator engine of new epoch

core/vm/interpreter.go, params/config.go
1. Replace unused Celo1 fork info with `churrito` hard fork (https://forum.celo.org/t/pre-announcement-of-security-hotfix-releases-celo-blockchain-1-1-1-and-1-2-2-and-churrito-hardfork/677), and implement the EVM change.  When we cherry-pick this on top of v1.1.0, we should first cherry-pick #1173, to avoid gratuitous merge conflicts.
2. Add Donut fork info (without setting activation block numbers), for use in future PRs implementing functionality for the future Donut hard fork (until now they had been using `Celo1`, which was added before the name Donut was chosen).
3. Set Churrito activation block number for Baklava as specified in https://github.com/celo-org/celo-proposals/blob/master/CIPs/cip-0024.md, and enable churrito for dev chain (`--dev`) and the test chains (used in the …
=> Churrito hard fork

cmd/utils/flags.go
The DNS discovery code from upstream includes the URLs to use.  Since we haven't set up the nodes tree on DNS for use by DNS discovery, we have no URLs we can use for that.  I believed that having the url set to `""` was enough to disable it, because the docs say to disable it using `--discovery.dns ""`.  However, those are not equivalent, and it was leading to a crash.  So this PR modified the initialization code to work so that if you don't specify `--discovery.dns` it will behave as if you specified `--discovery.dns ""`.
This highlights a serious gap in our integration tests, that we have no test of non-light sync using discovery:
1. The e2e tests in the monorepo all use `--nodiscover`
2. `scripts/sync_test.sh` uses only lightest mode sync, but discovery isn't the same for …
=> Disable DNS discovery by default

.circleci/config.yml, .travis.yml, Dockerfile, Dockerfile.alltools, Dockerfile.android, Dockerfile.arm64, Dockerfile.binaries, README.md, appveyor.yml, build/checksums.txt, consensus/istanbul/backend/handler.go, consensus/istanbul/proxy/proxied_validator_engine.go, consensus/istanbul/proxy/types.go, core/vm/interpreter.go, docs/docs/_developers/devguide.md, go.mod, go.sum, p2p/discv5/node_test.go, params/config.go, params/version.go
Changes since 1.2.1:
* Churrito
* Fixes a bug in the proxied validator engine around epoch transitions
* Upgrades to Golang 1.14.12
This is 1.2.2-beta which sets the churrito block number for baklava, but not for the other testnets
=> Release 1.2.2-beta

.circleci/config.yml, Makefile, build/ci.go, go.mod, go.sum, scripts/publish-mobile-client.sh
The work here disables bitcode so that the build works again on iOS using go 1.14
- Had to fork gomobile to patch this, PR submitted upstream https://github.com/golang/mobile/pull/59
- Move `libbls_snark_sys` handling to the Makefile and iOS step and explain why we need it
- iOS build compiles again locally and on CircleCI
- was able to sync, send money using a local build connected to alfajores on iOS
Yes
=> Disable bitcode

.circleci/config.yml, Makefile, go.mod, go.sum, scripts/publish-mobile-client.sh
When we updated celo-blockchain to use Go 1.14.x, we left the CI ios build as is, because it was failing with an error.  This PR resolves that by:
1. Updating the ios build to use Go 1.14.x
2. (c/o @jeanregisser) Disabling bitcode for the ios build, which required creating and using a fork of https://github.com/golang/mobile (https://github.com/celo-org/mobile/tree/jeanregisser/disable-bitcode)
3. (c/o @jeanregisser) Refactoring how we include `libbls_snark_sys.a` in the build.
=> Update ios build on CI to use go 1.14.x

accounts/keystore/keystore_test.go
Cherry-pick https://github.com/ethereum/go-ethereum/pull/21703 from upstream to fix the flaky test `TestWalletNotifications`.
* Tests pass locally and in CI
- Fixes #782
No concerns, only modifies a test, unrelated to protocol.
=> Cherry-pick: accounts/keystore: fix flaky test (#21703)

les/server_handler.go
Cherry pick a PR from upstream (upstream PR 21896) which fixes a possible panic in the LES server
Manually confirmed that the panic can happen without this patch, and that this patch fixes it.
No backwards compatibility concerns.
=> [cherry-pick] les: fix GetProofsV2 bug (#21896)

cmd/geth/consolecmd_test.go, cmd/utils/flags.go, eth/config.go
This changes the `light.serve` default back to zero so that serving light clients becomes opt-in rather than opt-out.  The reason is that there are many use-cases for running a node that don't involve light clients, and only one use-case that is about serving light clients, so it makes more sense to have it opt-in to avoid people running the light server without realizing it.
* Change `light.maxpeers` default value from 99 back to 100 (the change to 99 was to work around an issue that no longer exists, see below under "Related issues")
* Fix a bug in the logic for the `lightPeers` variable in `SetP2PConfig()` (it was not respecting the default value of LightPeers, leading to incorrect values in the `Maximum peer count` log line and to `MaxPeers` not being increased when it should have …
=> Make LES server not run by default, and tweak related flags

les/server_handler.go
[cherry-pick] les: fix GetProofsV2 bug (#21896) (#1265)
Cherry pick a PR from upstream (upstream PR 21896) which fixes a possible panic in the LES server.  This is already on master.
=> Cherry-pick LES server fix to 1.1.x release branch

core/vm/interpreter.go, params/config.go, params/version.go
Release 1.1.2-beta. Back porting churrito to the 1.1 release series.
The beta release only sets the block number for baklava.
=> Release 1.1.2-beta

.circleci/config.yml
This changes them to use medium+ instead of the default medium, which should help with flaky tests where the machine is overloaded and which don't happen on dev machines since they're more powerful (e.g. #629). If the failures keep happening, we can either (a) increase further to large, (b) increase the waits in the tests, (c) make those specific tests not run using `t.Parallel()`.
=> Bump up the CI resource_class for unit tests and coverage

les/server_handler.go
[cherry-pick] les: fix GetProofsV2 bug (#21896) (#1265)
Cherry pick a PR from upstream (upstream PR 21896) which fixes a possible panic in the LES server.  This is already on master.
=> Cherry-pick LES server fix to 1.2.x release branch

consensus/istanbul/backend/handler.go
Adjust comments around block signature monitoring to make it more clear in `consensus/istanbul/backend/handler.go`
- Related #1247
=> Adjust comments around missed block metrics in Istanbul

cmd/geth/accountcmd.go
currently, running "geth --nousb account proof-of-possession $SIGNER_ADDRESS $ADDRESS_TO_SIGN" doesn't do a validity check on $ADDRESS_TO_SIGN as specified in #1119
I'm using IsHexAddress in the common/types package. Since theres no new functionality i didn't think its necessary to add a test. if I assumed wrongly ill be happy to add a couple of tests
- Fixes #1119 
really small change so definitely backwards compatible
=> Fix: account proof-of-possession should fail with invalid address

consensus/istanbul/backend/backend.go, consensus/istanbul/backend/handler.go
As described in #1248, the proxy currently reported about missed blocks for it's validator peer.
This is confusing and my mislead the node operator to believe that their proxy is misconfigured to
run as a validator.
In this PR, the metrics check is changed to only report the local address and not on the peer
validator address. As a result, these lines will not appear on the proxy (unless it actually _is_
misconfigured to run as a valdiator)
- Fixes #1248
Metrics about the validator will not longer be reported by the proxy. If a node operator was relying
on this in there monitoring setup, the metrics will be unavailable when they update.
=> Only report missed blocks by the local address

consensus/istanbul/backend/handler.go
This removes a confusing log message when metrics are disabled.
None
- Fixes #1247 
Yes
=> Don't report missed in a row if metrics are disabled

consensus/istanbul/backend/api.go, consensus/istanbul/backend/backend.go, consensus/istanbul/backend/engine.go
This should reduce problems with using data-dirs from full nodes. This will not completely eliminate the problem if a data-dir is reused from a validator.
Confirmed that full nodes don't create the replica state and that nodes configured with --mine do.
Backwards compatible
=> Only create replicaState if configured as a validator

eth/downloader/downloader.go, eth/fetcher/block_fetcher.go, eth/handler.go
Validators have reported cases where they've encountered problems with the validator or proxy nodes disconnecting from each other or from other validator peers, and their logs don't show the errors that led to disconnecting from the peers, instead showing "useless peer".
Investigation into the code involved revealed that this is due to an upstream problem in the error handling, which this PR fixes.  Full details about the bug and the fix can be found in the commit message.
This PR further ensures that calls to `pm.removePeer()` (in some cases called as as `dropPeer()`) are preceded by a warning being logged (whereas, before, some of the log statements were warnings but others were debug or trace) and slightly rewords some of the log messages.
- Automated tests pass.
- Verified that errors …
=> Fix eth peer error handling

core/vm/contracts.go
Supersedes #1276. Same code, but branch is in this repo.
Goal is to prepare for Donut integration by providing a logical integration point for the precompile PRs
- Add new Donut precompile block
- Specify addresses for new Donut precompiles
- change `celoPrecompiledContractsAddressOffset` to unexported. It appears there was no reason to export this
No tests needed, as this change produces no practical effects yet
- n/a
Changes are ineffectual as the donut precompiles are not referenced anywhere.
=> Donut precompile scaffolding.

core/vm/contracts_test.go
Update precompile tests to use the Donut precompile block. This is further scaffolding for Donut CIP integrations, and does not have any functional changes
No functional changes.
=> tests: change precompile tests to use Donut block

consensus/consensus.go, consensus/istanbul/backend/backend.go, consensus/istanbul/backend/random.go, consensus/istanbul/backend/snapshot_test.go, consensus/istanbul/backend/test_utils.go, consensus/istanbul/types.go, consensus/istanbul/utils.go, contract_comm/random/random.go, core/blockchain.go, core/rawdb/accessors_chain.go, eth/backend.go, miner/miner.go, miner/worker.go, miner/worker_test.go
The changes in this PR will make all validators have they randomness cache set before starting mining.  It does this by two ways:
1) Whenever a block is synced or finalized via the consensus engine, the node will check to see if it authored that block, and will cache the block's parent hash (which is needed to recover the block's randomness in the future).
2) Before a node starts syncing, it will check to see if its last randomness commitment (saved on the random smart contract) has a cached entry.  If not, then it will do a reverse search of the blockchain to find the last randomness's block and then cache the block's parent hash.
Refactored some of randomness logic.  Specifically
1) Moved generation of randomness logic from package `contract_comm/random` to `consensus/istanbul`.
2) …
=> random beacon cache changes

consensus/istanbul/backend/backend.go, consensus/istanbul/backend/pos.go, consensus/istanbul/types.go, consensus/istanbul/uptime/store/store.go, consensus/istanbul/uptime/uptime.go, consensus/istanbul/uptime/uptime_test.go, consensus/istanbul/uptime/window.go, consensus/istanbul/utils.go, consensus/istanbul/utils_test.go, core/blockchain.go, core/blockchain_test.go, core/rawdb/accessors_chain.go, core/rawdb/accessors_chain_test.go
Several people had trouble following current uptime scoring logic. It looks like a pool for off by one errors. This PR attempts to do some cleanup to make it more maintainable.
* Extracts the code to its own package where before code was distributed in 3+ files.
* Add Tests 
* Add godocs to functions
* Rename functions/variables to make code easier to understand
* Introduce the type `Window` which simplifies reasoning about UP blocks
* Modify the monitoringWindow and updateUptime functions so they work with the block whose signatures they intend to monitor, vs the block whose parent block signatures we want to monitor.
We can now summarize uptime computation as:
* `monitoringWindow(epoch):` Range of blocks from an epoch where UP status will be monitor. Represents also the maximum number …
=> Cleanup validator uptime computation

consensus/istanbul/core/backlog.go, consensus/istanbul/core/backlog_test.go
While investigating issues with Baklava we noticed some errors in validator logs that led us to find this logic bug which means that `.clearBacklogForSeq()` wasn't doing anything, leading `.store()` calls to eventually drop new messages: https://github.com/celo-org/celo-blockchain/blob/278176e05ac8646c1c3642d02134fd7000a5be64/consensus/istanbul/core/backlog.go#L168-L170
This PR fixes the logic bug and adds a unit test that would have detected the bug, as well as similar logic mistake in the comment for `processBacklogForSeq()`
- Before the fix, the new test fails
- After the fix, the new test passes
No backwards compatibility issues.
=> Fix bug in istanbul's backlog 'clearBacklogForSeq()'

cmd/utils/flags.go
Dev mode had stopped working in master (unless also --mine flag was specified).
Only manual testing
=> Making dev mode work again

consensus/istanbul/backend/backend.go, consensus/istanbul/utils.go, consensus/istanbul/utils_test.go, consensus/istanbul/validator.go, consensus/istanbul/validator/default.go, consensus/istanbul/validator/validator.go, contract_comm/validators/validators.go, core/vm/contracts.go, core/vm/contracts_test.go, core/vm/evm.go, crypto/bls/bls.go, eth/tracers/tracer.go, go.mod, params/config.go, params/protocol_params.go
Reverts celo-org/celo-blockchain#1250
The change on `ValidatorData` implies a break on previous `roundStateDB` storage. We revert it until it's fixed.
=> Revert "CIP-26: Get validator BLS key precompile"

consensus/istanbul/core/backlog.go, consensus/istanbul/core/backlog_test.go, params/version.go
Release 1.2.2-stable. This includes a cherry-pick of #1300 to fix a bug in the backlog.
This also is also stable for rollout to mainnet.
Yes
=> Release blockchain 1.2.2-stable

.circleci/config.yml, Dockerfile.android, Dockerfile.arm64
We have have a few places where we refer to the specific Go versions rather than 1.14.  This PR updates those to use the newest 1.14.x version (1.14.14).
Note that this includes the e2e tests in CI, but not the rest of CI (which uses the `circleci/golang:1.14` docker image which hasn't yet been updated as of now).
- celo-blockchain builds successfully with 1.14.14, including for arm64 (tested using `make ios`)
No breaking changes.  Go 1.14.13 and 1.14.14 were security patches.
=> Update golang 1.14.12 references to 1.14.14

.circleci/config.yml, cmd/utils/flags.go, consensus/consensus.go, consensus/istanbul/backend/engine.go, consensus/istanbul/backend/handler.go, consensus/istanbul/backend/pos.go, consensus/istanbul/backend/test_utils.go, consensus/istanbul/config.go, consensus/istanbul/uptime/config.go, consensus/istanbul/uptime/config_test.go, consensus/istanbul/uptime/monitor.go, consensus/istanbul/uptime/monitor_test.go, consensus/istanbul/utils.go, contract_comm/blockchain_parameters/blockchain_parameters.go, core/blockchain.go, eth/backend.go, params/config.go, params/protocol_params.go
* Implementation of [CIP-21](https://github.com/celo-org/celo-proposals/blob/master/CIPs/cip-0021.md).
* Monrepo Counterpart  https://github.com/celo-org/celo-monorepo/pull/4747
Modifies celo-blockchain to obtain `lookbackWindow` parameter from the `BlockchainParameters` smart contract. It assumes the smart contract will return the same value during an epoch.
`lookbackWindow` is used on 3 places:
1. For metrics; where the parent block signatures are analyzed.
2. For every block on `Blockchain` we obtain the `loobackWindow` asses the "upness" of each validator on that block
3. On the last block of the epoch, to compute the uptime score
Added unit tests.
**Hardfork Change**. Part of `Donut` Hardfork
=> CIP-21 Governable "lookbackWindow" parameter

consensus/istanbul/backend/announce.go
Currently encrypting encodeURL is logged with verbosity as `info`. Changed to `debug` 
none
Changed only log level  for a line for logger.
- Fixes #976 
Yes
=> backend: Updated logger level

README.md, consensus/istanbul/core/preprepare_test.go, consensus/istanbul/core/testbackend_test.go
This adds a simple benchmark for round changes and pre-prepares. It is parameterized with the validator set size
to determine the effect of increasing the set size on the time to complete a round change. 
* Adds getPreprepareMessage to testbackend
* Adds a test system with no logging
* Enables testing.B to be passed to testbackend getters
* Adds benchmarking instructions to README
=> Benchmark round changes and pre-prepares

cmd/geth/config.go, cmd/geth/main.go, cmd/utils/flags.go, core/genesis.go, eth/backend.go, eth/config.go, eth/gen_config.go, les/client.go
Add CLI flags `--override.churrito` and `--override.donut` which can be used to override the activation block numbers for the Churrito and Donut hard forks.  This could be used to set the activation on pre-existing ephemeral testnets, or in an emergency scenario where the activation block numbers have already been set and we need to postpone the fork, in which case the overrides would allow doing that using a flag rather than having to downgrade celo-blockchain.
This follows the pattern used for overrides in go-ethereum, for example with Istanbul and Muir Glacier.  The override has effect except if (it's the first time `geth` is being run && `geth init` wasn't used).  The value specified in the override isn't persisted to the database, so if you later on run geth without the override …
=> Add Churrito and Donut override flags

core/blockchain_test.go
This test from go-ethereum includes code to make the main and side-chain have difficulties as desired for the test to work.  Since for Celo the difficulty of each block is 1, that part wasn't working and the main and side-chain both had difficulty 3.  As a result, whether or not a reorg was done when the side-chain is inserted was indeterministic (see writeBlockWithState() in core/blockchain.go).  But Go's math/rand global rand object uses the seed value 1, and so you get the same sequence of values every time.  This was leading to some very confusing behavior: this test was passing as part of the overall test suite, but failing if run by itself.  This commit fixes that by making the main chain have 3 blocks, the side chain 2 blocks, and then it adds 2 more to side chain, making it 4. …
=> Fix indeterministic test TestSideLogRebirth

scripts/publish_private_docker_image.sh
Adds script to build and publish a private docker image
The image is uploaded to gcr.io/celo-testnet which is only accessible to cLabs.
=> Adds script to build and publish a private docker image

consensus/consensustest/mockprotocol.go, core/vm/context.go, core/vm/contracts.go, core/vm/evm.go, core/vm/runtime/env.go
EVM Context exposes the `consensus.Engine` which couples the engine with everyone that uses the context. This PR changes that, by only exposing the necessary functions directly on the context.
Side benefit of this, is that you don't need a full engine to create a `Context`, which is useful to fix and use the `evm` command from cmdline.
unit tests
- This is necessary work for `mycelo`
Yes
=> Refactor EVMContext to avoid depending from engine

mycelo/cluster/node.go
- Add --nodiscover flag (we're using static nodes)
- Use interrupt signal to quit geth, to prevent db corruption leading to stall on restart
Fixes a couple of problems I ran into while using mycelo testnets:
1. Since we aren't specifying either bootnodes nor `--nodiscover`, it tries to use the mainnet bootnodes.  This commit adds `--nodiscover` to prevent that
2. When quitting from validator-run, it was using a kill signal which meant the validators didn't have time to shut down cleanly.  This led to database corruption.  When starting again it would then rewind (on all validators), leading the network to stall permanently since the validators don't have the necessary state in their db.  This PR makes it instead use the interrupt signal, which lets the node shut down cleanly.
- Confirmed …
=> Small fixes for mycelo validator-run command.

cmd/mycelo/main.go, mycelo/contract/contracts.go, mycelo/env/core_contracts.go, mycelo/genesis/genesis_state.go, mycelo/loadbot/bot.go
3 small changes:
* Add `--init` to `mycelo validator-run`; to avoid a call to mycelo
* Fix load-bot: It was using the impl address instead of the proxy address
* Rename `env.XXAddressFor` functions so it's clear if you're asking for the impl or the proxy address. 
Run mycelo & loadbot
=> mycelo: Fix load bot & add --init to validator-run

cmd/mycelo/env_commands.go, mycelo/env/accounts.go
Address comments on https://github.com/celo-org/celo-blockchain/commit/fa61583f1b5779096672f2d9595e9e977f063627#
=> [mycelo] typos on env accounts cmd

cmd/mycelo/templates.go, mycelo/loadbot/bot.go
Disables gas price updating in the load test. Prior to this change the gas price was going so high that transactions cannot go through after a couple hundred full blocks
This also sends transactions in a round robin fashion (Initial attempt to fix). This is probably not strictly needed to fix the issue.
- Fixes #1400
=> Disable GPM updates during mycelo load tests

cmd/mycelo/main.go, mycelo/loadbot/bot.go
Limits the number of pending txs sent to --maxpending
This does not completely prevent a slowdown on the testnet, but it stops it
from becoming a cascading failure.
Yes
=> Adds flag to limit pending txs

consensus/istanbul/proxy/proxied_validator_engine.go
There's currently an info log that will frequently print the addresses of every validator in the validator set. This change prints the length of the validator address array in the info log, but only prints the entire array in a trace log.
See https://discord.com/channels/600834479145353243/697229909545713775/817039572968931420
n/a
Just `make geth`
n/a
yes
=> Change verbose info log

contract_comm/currency/currency.go
Properly dereference the fee currency point such that currency.Cmp short circuits when comparing non-native fee currencies.
https://colab.research.google.com/drive/1duSJnIAxUs-3U8YQeEzPGZy8xnpwgWGC#scrollTo=4MyDZZHg_eZh
Tested with all cUSD and a mix of cUSD and CELO fee currencies.
- Partial fix of https://github.com/celo-org/celo-labs/issues/837
Yes.
=> Short circuit in currency compare

mycelo/cluster/node.go
Split extra flags on whitespace and then pass the array.
This enables passing multiple extra flags through to geth.
=> Split extra flags on whitespace

cmd/clef/README.md, cmd/clef/main.go, cmd/geth/chaincmd.go, cmd/geth/main.go, cmd/geth/usage.go, cmd/utils/flags.go, core/chain_makers.go, docs/docs/_interface/Command-Line-Options.md, node/config.go, signer/core/api.go, signer/core/api_test.go
All celo-blockchain flags should either function as they do in upstream geth, or be removed.
This is to reduce confusion for external devs familiar with upstream geth.
Certain flags are removed in this PR.
--fakepow
--pcscdpath
Examed following commands:
`geth import`
`geth export`
`geth copydb`
`geth dump`
`geth inspect`
Yes
- Fixes #1064
Yes
=> Remove Ethereum flags that don't apply to Celo

core/vm/contracts.go
Just fixes a typo, and updates a stale comment in passing
CI
=> Fix typo in precompile address variable name

accounts/abi/bind/backends/simulated.go, accounts/abi/bind/backends/simulated_test.go, console/bridge.go, graphql/graphql.go, internal/ethapi/api.go, rpc/client_test.go, rpc/errors.go, rpc/handler.go, rpc/json.go, rpc/server_test.go, rpc/testservice_test.go, rpc/types.go
This cherry-picks a PR from upstream that adds the revert reason to the error returned from `eth_call` if there was a revert.  
The `eth_call` behavior in case of a revert was as follows:
* go-ethereum v1.9.13 and earlier: the revert reason is in the return data.  web3 checks the return data and generates an error with the revert reason
* go-ethereum v1.9.14: the return data and error are both nil (which is a bug introduced in v1.9.14).  web3 thinks the call succeeded
* go-etherem v1.9.15: the return value is nil, and the error includes a `data` property with the revert reason.  web3 checks the error's data and generates and error with the revert reason
On celo-blockchain, v1.2.x and earlier have the pre-1.9.14 behavior,  master currently has the v1.9.14, and this PR pulls in the v1.9.15 …
=> Cherry pick upstream PR for revert reason in eth_call (upstream #21083)

mycelo/loadbot/bot.go
Refactors the load bot to reduce CPU Usage. This does it by having one thread that is on a ticker and firing off single run go-rountine transfers.
Previously there where `developer account` go routines being ran, and each was sleeping until it should send its transaction (through a couple of calculations to ensure that the TPS was correct). It appears to be a semi-known issue that ticker's (and fewer of them) seem to perform better than sleeping.
Tested on a gcp vm instance. At 5s block times, order 50-100 TPS, cpu usage dropped from a couple hundred percent (out of 400% b/c 4 core machine), to 10-15% sustained. (The old version actually does ok at ~25 TPS, but gets much worse as the load increases)
=> Refactor load bot to reduce CPU Usage

.circleci/config.yml, accounts/abi/bind/backends/simulated.go, cmd/geth/retesteth_copypaste.go, contract_comm/evm.go, core/error.go, core/state_processor.go, core/state_transition.go, core/tx_pool.go, core/tx_pool_test.go, core/types/gen_tx_json.go, core/types/transaction.go, core/types/transaction_signing.go, core/types/transaction_test.go, core/vm/context.go, core/vm/contracts_test.go, interfaces.go, internal/ethapi/api.go, les/odr_test.go, light/odr_test.go, light/txpool.go, rlp/decode.go, rlp/decode_test.go, rpc/types.go, signer/core/types.go, signer/fourbyte/validation.go, tests/state_test_util.go
This PR implements CIP35 as specified at https://github.com/celo-org/celo-proposals/blob/master/CIPs/cip-0035.md.
Summary of changes:
* `Transaction` type has a new field `EthCompatible` to distinguish between normal transactions (with the Celo-only fields) and ethereum-compatible ones (without those fields)
* When decoding transactions of RLP, it identifies the type based on the number of fields the RLP list has
* When encoding transactions to RLP, it encodes them to have either 9 or 12 fields depending on the value of `EthCompatible`
* When generating or verifying transaction signatures, the signing data used is determined by the value of `EthCompatible`
* When serializing to or deserializing from JSON, the `EthCompatible` field is encoded as `ethCompatible`.
* When validating …
=> Implement CIP35 for Donut hard fork

mycelo/cluster/cluster.go, mycelo/cluster/node.go, mycelo/env/accounts.go, mycelo/env/types.go
This PR updates mycelo to use the new `--miner.validator` and `--tx-fee-recipient` flags instead of `--etherbase` if the geth version supports it.
1. Add a new account type for tx fee recipient (a corresponding change should be made in celo-monorepo, to allow it to be used on GCP testnets and to be consistent)
2. Add the bootnode account type, which exists in celo-monorepo but was missing in mycelo, resulting in the subsequent account type values being off by one.
3. Enable the istanbul RPC on the validators nodes (e.g. to get the lookback window)
Confirmed to work with both master and v1.2.4
As some of the account type values have been shifted by one, you could get the wrong value when using `mycelo env account` to generate account information (for account types >= 3) for a mycelo …
=> mycelo: support new etherbase and tx-fee-recipient flags

params/config.go
Sets the Baklava Donut activation block number to 5002000, which will be April 13, 2021, in preparation for the v1.3.0-beta release intended for Baklava.
* Verified the activation block is reflected in the logging when a node start up.
* Verified the node successfully connects to peers and starts syncing.
* Donut hard-fork activation has been tested on a local testnet and a private cloud testnet (including testing of all the Donut CIPs)
* When Baklava block 5002000 arrives and Donut is activated, unupgraded nodes will not be able to establish connections with upgraded nodes, and will not be able to sync to the chain's head once a transaction has been mined which takes advantages of the new functionality in Donut.
* No effect on networks other than Baklava.
=> Set Baklava Donut activation (block 5002000, April 13, 2021)

contract_comm/currency/currency.go, contract_comm/currency/currency_test.go, miner/worker.go
Cherry picks the tx comparator commits from branch `mc/caching-tx-cmp` (which were included in v1.2.5) onto `release/1.3.x`, to then release v1.3.0-beta.2.
The changes themselves have been tested as part of the v1.2.5 release
=> Cherry pick 'caching tx cmp' (part of v1.2.5) onto branch release/1.3.x

params/version.go
Update version to `1.3.0-beta.2`, which includes the tx comparison caching from v1.2.5.
=> Release v1.3.0-beta.2

core/tx_pool.go
When preparing the earlier PR for v1.3.0-beta.2 (which adds the changes from v1.2.5), I missed including the change to the default transaction pool size.  This PR adds that change, and will used for the v1.3.0-beta.2 release.
=> Finalize v1.3.0-beta.2 release: set tx pool size to 2048

eth/handler.go, eth/peer.go
This PR cherry-picks from upstream a fix (https://github.com/ethereum/go-ethereum/pull/21255) for a bug introduced in the initial eth/65 (celo/66) implementation, new to our v1.3.x releases.  It also cherry picks a small prior commit (to not run `announceTransactions()` if the peer isn't running celo/66 or newer) since the code in question built on top of that change.
This bug was behind the problems seen on one of the Baklava Forno nodes, reported by @zviadm.  The short of it is that improper cleanup when the `announceTransactions()` goroutine exits with an error meant that one of the subscribers to the transaction pool's `txFeed` feed got stuck, which in turn blocked the transaction pool's `reorg()` goroutine (which prevented future reorgs from even happening again, meaning the …
=> Cherry-pick fix for eth/65 (celo/66) bug which can cause the tx pool to be blocked

mycelo/loadbot/bot.go
This PR makes load-bot capable of consistently handling heavy load. Prior to this change heavy loads would result in load-bot failing due to resubmitting transactions with the same nonce. This was happening because we were calling `PendingNonceAt` to get the nonce for each transaction before sending it. `PendingNonceAt` looks into the transaction pool to discover the next viable nonce but there is no guarantee that the transaction pool will have updated with the latest sent transactions. This resulted in attempting to submit subsequent transactions with the same nonce.
Also fixed some race conditions in the load-bot.
Was now able to successfully run the load-bot with heavy load (~100 tps)
- Fixes #1455 
These changes change no APIs or interfaces and so should be backwards compatible.
=> Fix load-bot failure with heavy load

consensus/istanbul/core/core.go, consensus/istanbul/core/final_committed.go
This creates a function called `core.startNewSequence` that is used in place of `core.startNewRound(common.Big0)`. This helps clean up the code and simplifies the logic of starting new rounds and sequences.
Unit tests
=> Split out startNewSequence from core.startNewRound

ethstats/ethstats.go
Improve reliability from the ethstats module
The connectionWrapper was cherrypicked from go-ethereum upstream:
https://github.com/ethereum/go-ethereum/commit/82a9e11058623e73ace50445b41a06ccf8fd888f (https://github.com/ethereum/go-ethereum/pull/21404)
Validator injecting its version to the proxy stats chunk
Manually in a local testnet
- Fixes #1395 
- Fixes #1397 
Yes
=> Celostats reliability

miner/worker.go
This PR implements an optimization to remove a large inefficiency in block creation.  The worker goes through, trying to add the transactions in order of decreasing gas price, until it .  If it encounters a transaction that requires more gas than is left in the block, it would try to process it and give an error `core.ErrGasLimitReached` which is then handled by skipping the transaction and continuing trying others (since there may be other transactions later on which require less gas and could fit).  The problem was that before this error is returned it does a bunch of work, including core contract calls.  This meant that going through transactions which aren't included was taking a long time when the transaction pool had 1000 or more pending transactions.
With this PR, we first check …
=> Skip GPM and other checks for transactions whose gas limit exceeds what's left it the block

core/tx_pool.go, ethstats/ethstats.go, miner/worker.go, params/version.go
Cherry pick a couple of PRs to the 1.3.x release branch:
* #1487 Celostats reliability
* #1490 Mining optimization for large tx pool size
Then update the version to v1.3.0-beta.3 which will be tagged as a release.
Revert the change in default tx pool `GlobalPending` value.  It was changed to 2048 in v1.3.0-beta.2 due to remaining inefficiencies with large tx pools.  However, this is resolved by #1490, so this PR also sets it back to its original value of 4096.
* PRs tested separately and approved for master.
=> Cherry-pick PRs to 1.3.x branch and release v1.3.0-beta.3

.circleci/config.yml
This fixes the error seen on the ios build in CI:
```
==> Downloading https://homebrew.bintray.com/go-1.16.3.catalina.bottle.tar.gz
##O#- #                                                                       
curl: (22) The requested URL returned error: 403 Forbidden
Trying a mirror...
==> Downloading https://ghcr.io/v2/homebrew/core/go-1.16.3.catalina.bottle.tar.g
==> Downloading from https://github.com/-/v2/packages/container/package/homebrew
#=#=#                                                                         
curl: (22) The requested URL returned error: 404 
Error: Failed to download resource "go"
Download failed: https://ghcr.io/v2/homebrew/core/go-1.16.3.catalina.bottle.tar.gz
Exited with code exit status 1
CircleCI received exit code 1
```
The fix comes recommended from …
=> Fix homebrew error in CI (due to outdated version).

core/state_transition.go
This gets rid of the infamous `Transaction failed provide intrinsic gas` error log statement which has often been taken to indicate a problem with gas estimation (e.g. returning an incorrect value) when in fact it was happening as a normal part of gas estimation's binary search.
This log statement was being hit as part of gas estimation if using non-Celo currencies for the fees.  However, this is a normal part of gas estimation's binary search, which sets the search's bottom at 21k gas and doesn't account for intrinsic gas being higher in some cases.  As such, it should not log an error message.  An alternative solution, if we wanted to keep this log statement, would be to calculate the intrinsic gas taking into account the fee currency and use that as the low end of the binary search. …
=> Remove error log when gas < intrinsic gas.

params/config.go
* Alfajores is set for May 4, 2021
* Mainnet is set for May 19, 2021
This PR sets the hard fork block activation numbers for Churrito and Donut (set to activate together) for the Alfajores testnet and mainnet.
* Local testing
No incompatibility until reaching the activation block.
=> Set activation blocks for Churrito and Donut on Alfajores and mainnet.

params/config.go
Cherry-picks #1509 to the `release/1.3.x` branch, for subsequent inclusion in v1.3.0-stable.
=> Cherry pick donut activation to 1.3.x release branch

cmd/utils/flags.go
Documentation implies this behavior is intended. For example,
https://docs.celo.org/validator-guide/proxy.
This facilitates running geth without initially configuring a proxy and adding
proxies later via RPCs. For example, like
https://github.com/mantalabs/proxy-informer.
Ad hoc testing locally.
This change is technically a breaking one because it changes the behavior of the
(deprecated) --proxy.proxyenodeurlpair option from required to
optional. This will break uses where --proxy.proxyenodeurlpair is elided and
there's an expectation that geth will fail to start.
=> Make --proxy.proxyenodeurlpairs optional if --proxy.proxied specified

consensus/istanbul/backend/pos.go, contract_comm/currency/currency.go, contract_comm/currency/currency_test.go, core/bench_test.go, core/block_context.go, core/state_transition.go, core/tx_list.go, core/tx_list_test.go, core/tx_pool.go, light/txpool.go, miner/worker.go, tests/transaction_test_util.go
This PR adds a caching layer to the txpool. It works as follows:
Cache has 2 parts:
* `BlockContext` which represents contract's information required to process a block. (gasPriceMinimum per currency, whitelistedCurrencies, gasForAlternativeCurrency)
* `CurrencyManager` object which is able to make currency conversion, and maintains al local cache of exchange rates
Both objects are part of the `txpoolContext`, and they are recreated with every `reset()`. This means they are recreated everytime the txpools learns about a new block.
1. txpool no longer checks for gas price minimum (see https://github.com/celo-org/celo-blockchain/pull/1499#issuecomment-819089144)
2. If `getCurrencyWhitelist()` fails, then assume no custom fee currency
is whitelisted (before: any fee currency was whitelisted) …
=> txpool: contract call caching & remove gpm check

contract_comm/currency/currency.go, core/state_transition.go, core/tx_pool.go
Everycall used the same maxGas parameter, so instead of passing it, we
use it directly. This is what every other call in the system does.
Also, usedGas was not really used as a return parameter, so removed
* unit tests, ci
=> Removes unnecessary arguments/returns to GetBalance

cmd/geth/main.go, cmd/utils/flags.go, consensus/istanbul/backend/backend.go, consensus/istanbul/backend/engine.go, consensus/istanbul/config.go, consensus/istanbul/core/commit.go, consensus/istanbul/core/core.go, consensus/istanbul/core/prepare.go, consensus/istanbul/core/preprepare.go, metrics/csv_metrics.go, metrics/metrics.go, miner/worker.go
Adds better metrics for load testing.
Also adds a command line option `--metrics.loadtestcsvfile` to specify a file to write out information about the block production and consensus cycle in a CSV format. This was previously on a separate branch that was cherry-picked onto the branch that we wanted to loadtest.
Local load test.
- Fixes #1511
=> Add block production and consensus cycle metrics

.circleci/config.yml
We previously added `brew update` in #1503.  However, since then `brew update` has started giving the following error:
```
Error: 
homebrew-core is a shallow clone.
homebrew-cask is a shallow clone.
To `brew update`, first run:
git -C /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core fetch --unshallow
git -C /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask fetch --unshallow
These commands may take a few minutes to run due to the large size of the repositories.
This restriction has been made on GitHub's request because updating shallow
clones is an extremely expensive operation due to the tree layout and traffic of
Homebrew/homebrew-core and Homebrew/homebrew-cask. We don't do this for you
automatically to avoid repeatedly performing an expensive unshallow operation in
CI …
```
=> Fix ios build in CI (again)

cmd/utils/flags.go, core/blockchain.go, core/blockchain_repair_test.go, core/blockchain_sethead_test.go, core/blockchain_snapshot_test.go, core/rawdb/accessors_snapshot.go, core/rawdb/schema.go, core/state/snapshot/conversion.go, core/state/snapshot/difflayer.go, core/state/snapshot/difflayer_test.go, core/state/snapshot/disklayer.go, core/state/snapshot/disklayer_test.go, core/state/snapshot/generate.go, core/state/snapshot/generate_test.go, core/state/snapshot/iterator.go, core/state/snapshot/iterator_binary.go, core/state/snapshot/iterator_fast.go, core/state/snapshot/journal.go, core/state/snapshot/snapshot.go, core/state/snapshot/snapshot_test.go, core/state/statedb.go, eth/config.go, ethdb/leveldb/leveldb.go, ethdb/memorydb/memorydb.go, tests/state_test_util.go, trie/database.go
Cherry pick bug fixes from upstream for snapshots, which will enable higher transaction throughput.  It also enables snapshots by default (which is one of the commits pulled from upstream).
Upstream commits included:
```
68754f393 cmd/utils: grant snapshot cache to trie if disabled (#21416)
3ee91b9f2 core/state/snapshot: reduce disk layer depth during generation
a15d71a25 core/state/snapshot: stop generator if it hits missing trie nodes (#21649)
43c278cdf core/state: disable snapshot iteration if it's not fully constructed (#21682)
b63e3c37a core: improve snapshot journal recovery (#21594)
e6402677c core/state/snapshot: fix journal recovery from generating old journal (#21775)
7b7b327ff core/state/snapshot: update generator marker in sync with flushes
167ff563d core/state/snapshot: …
```
=> Stabilize Snapshots

params/version.go
Set the version to 1.3.1-stable
=> Release celo-blockchain v1.3.1-stable

.circleci/config.yml, Dockerfile.android, Dockerfile.arm64, params/version.go
The `golang:alpine-1.16` docker image has not been updated yet, contrary to what it says on docker hub's website.  Once it's updated, I will amend commit and force push to trigger a new build which will use 1.16.4
Within less than an hour after we released v1.3.1, a Golang security patch was announced: https://groups.google.com/g/golang-announce/c/cu9SP4eSXMc/m/vBLImzQOAgAJ .  This PR updates celo-blockchain to use the new Golang release, and set the celo-blockchain version to v1.3.2.  
* CI
* Confirmed that the generated docker image uses go version 1.16.4:
```
❯ docker run -it us.gcr.io/celo-testnet/geth:2ea8e9c0f9f7483bb6cfb3ad8410791fb8bd6acc version
Celo
Version: 1.3.2-stable
Architecture: amd64
Protocol Versions: [66 65 64]
Go Version: go1.16.4
Operating System: linux
GOPATH= …
```
=> Use Go v1.16.4 and release celo-blockchain v1.3.2

.circleci/config.yml, Dockerfile.android, Dockerfile.arm64
Go v1.16.4 is a security release.  We've upgraded to it in celo-blockchain v1.3.1 (#1535).  This PR also upgrades on master.  Note that, as usual, the places where we use the `golang:1.16-alpine` image don't need to be modified as the newest 1.16 image will be used automatically.
* CI
No incompatibilities.
=> Use golang v1.16.4

consensus/istanbul/protocol.go, eth/handler.go, p2p/peer.go, p2p/protocol.go, p2p/server.go
Now that Donut has been activated on Alfajores, Baklava, and mainnet, all nodes which are still able to connect and sync are running v1.3.x and thus support celo/66.  Therefore, it is possible to remove support for celo/64 and celo/65 and with them the notion of a "primary" protocol.
See #1213 for more context.
* Automated testing
* A full node successfully starts syncing to mainnet.
- Closes #1213
This breaks compatibility with nodes running v1.2.x or older.
On Alfajores, Baklava, and mainnet we have already broken compatibility with such nodes when the Donut hard fork was activated, so this PR doesn't add any additional incompatibility.
However, on private testnets that might not be the case, and so for them this PR would constitute a breaking change requiring nodes to upgrade to v1.3.0 …
=> Remove support for celo/64 and celo/65 protocols.

mycelo/genesis/config.go
When I added these gencodec override types for the mycelo genesis config, I didn't realize you only need to include the fields that you want to override.  As a result, these types duplicate the other fields even though it's not necessary.  This PR removes that duplication, leaving only the fields to be overriden.
Fixed the use of `PascalCase` instead of `camelCase` in some of the governance contract's parameters' json names. 
* Verified that the monorepo e2e tests' use of mycelo to generate the genesis (which is why these overrides were needed in the first place) still works.
Due to the json name changes, this will not be compatible with `genesis-config.json` files generated using older versions.  However, the mycelo genesis config json is not intended to be long-lived (e.g. not intended …
=> Clean up mycelo genesis config type overrides

build/ci.go, common/task/task_test.go
Increase internal, to cope for resource contention when running tests
=> Fix RunTaskRepeteadly flakyness

consensus/istanbul/backend/announce.go, consensus/istanbul/backend/backend.go, consensus/istanbul/backend/gossip_cache.go, consensus/istanbul/backend/handler_test.go, consensus/istanbul/backend/message_senders.go
Small needed change which is a part of a work in progress to tidy & modularize the announce protocol.
The Istanbul Backend has a cache of processed messages to avoid re-processing them. It's implemented using two different cache instances for self & peer messages. This commit extracts them to a single type `GossipCache`.
=> Extract GossipCache from the istanbul.Backend

params/version.go
We have previously been setting versions only on release branches, leaving master permanently at v1.0.0-unstable.  Besides being confusing, this wouldn't work properly if we ever increase the minimum client version on the `BlockchainParameters` contract.
Instead, this PR sets it to v1.4.0-unstable, since the latest stable release was v1.3.2, so the next release branch will be v1.4.x.  It also adds a comment describing how the versioning should go.
Verified with `geth version`:
```
❯ geth version
Celo
Version: 1.4.0-unstable
Git Commit: 538d2f885984db4e0aff0bdaab22a562a8ad2d39
Git Commit Date: 20210616
[...]
```
- Fixes #1580
No incompatibility.
=> Set master version to be ahead of latest release, and add comment about versioning

.circleci/config.yml, .gitignore, Makefile, README.md, cmd/geth/accountcmd.go, cmd/mycelo/templates.go, crypto/celo_crypto.go, e2e_test/e2e_test.go, mycelo/genesis/genesis.go, node/config.go, params/config.go, test/node.go, test/transaction_tracker.go
This PR adds a package that enables writing tests of full networks within a singe go test process. It also adds an example test.
To try this out you will first need to run `make prepare-system-contracts` and then you can run the test (note you will need node v10 for the make command to succeed)
The commits for this PR are well separated and I think it would be easier to review commit by commit.
The test works most of the time on my machine and seems to work most of the time on CI, sometimes the network hangs, I believe this is a problem with the blockchain code not the test code. I'm wondering whether it would be better to skip the test, but at least for now it's useful to know that the test is able to be run in CI.
You can run the e2e test with `go test ./e2e_test -count 1` it should …
=> Run full network tests in under 1 second (pure go)

p2p/enode/iter_test.go
Run `go test -race ./p2p/enode`
Get:
```
==================
WARNING: DATA RACE
Write at 0x00c0001c6b18 by goroutine 13:
github.com/celo-org/celo-blockchain/p2p/enode.(*genIter).Close()
/Users/tong/celo/celo-blockchain/p2p/enode/iter_test.go:271 +0x3e
github.com/celo-org/celo-blockchain/p2p/enode.(*FairMix).Close()
/Users/tong/celo/celo-blockchain/p2p/enode/iter.go:193 +0x141
github.com/celo-org/celo-blockchain/p2p/enode.testMixerFairness()
/Users/tong/celo/celo-blockchain/p2p/enode/iter_test.go:118 +0x585
github.com/celo-org/celo-blockchain/p2p/enode.TestFairMix()
/Users/tong/celo/celo-blockchain/p2p/enode/iter_test.go:96 +0x44
testing.tRunner()
/usr/local/go/src/testing/testing.go:1193 +0x202
Previous read at 0x00c0001c6b18 by goroutine 14:
sync/atomic.LoadInt32() …
```
=> Fix race condition in p2p/enode

Makefile, README.md, scripts/check_imports.sh, scripts/hooks/pre-commit, scripts/rename_imports.sh
This PR fixes a couple of problems with the prepare-system-contracts make rule.
* The rule previously appeared first in the Makefile, which meant that running just `make` would now run `prepare-system-contracts` instead of `geth`.
* The rule also checked out celo-monorepo under the celo-blockchain dir and this slowed down gopls massively, because of the huge amount of files in celo-monorepo.
* The rule did not handle celo-monorepo commit version changes gracefully, now when updating the version the new version will be fetched, checked out and then built.
* The default checkout path clashed with some people's setup so that has been changed to be something less likely to clash.
* Some scripts were updated to ignore the monorepo symlink at the repo root.
I've tested it locally and it seems …
=> Piersy/update prepare-system-contracts make rule

cmd/geth/les_test.go, consensus/istanbul/backend/announce.go, consensus/istanbul/backend/backend.go, consensus/istanbul/backend/engine.go, consensus/istanbul/backend/handler_test.go, consensus/istanbul/backend/random.go, consensus/istanbul/backend/test_utils.go
Properties received in the `Authorize(...)` method of `istanbul.Backend` are guarded by a lock to avoid race conditions during  the setting of the values (golang reference assigmnent is not guaranteed to be atomic I believe).
I moved all of those into a type `AuthorizeInfo` and used an `atomic.Value` to be able to remove the lock. The `decryptFn` was not being guarded by the lock, as many other `address` fields, in what I believe it was a possible race condition bug during assignment and check. It's probably the case that it would have never been triggered in real world use though.
I also incremented a sleep in an unrelated test since the wait period for a geth instance to start was too low and it was making the test a bit flaky.
=> Move several sign&address properties from istanbul.Backend to its own type

cmd/mycelo/templates.go, mycelo/genesis/base_config.go
This is a companion PR to https://github.com/celo-org/celo-monorepo/pull/8086, with some changes which are needed to make the tests work:
1. Monorepo uses a single validator group, so we update the mycelo monorepo template to do so as well.
2. Make the DowntimeSlasher's slashable downtime small so it works with the small epoch sizes we use (if the slashable downtime is larger than the epoch size, you can't test out slashing)
3. Modify the monorepo template's config values for epoch rewards and initial reserve balance to match what is done in the monorepo for the 'testing' context (which is what the e2e tests use).  See https://github.com/celo-org/celo-monorepo/blob/c90edf1c938363e24746c90153d36263bb668aef/packages/protocol/migrationsConfig.js#L244-L281 .
* Tested in conjunction with the …
=> Update mycelo config values to work with monorepo e2e tests

core/vm/evm.go, eth/api.go, eth/api_tracer.go
This field was added in PR #317 but was never set in `vm.NewEVMContext()`.  As a result, it was always nil.  After the refactoring of contract calls to use the vm.EVMRunner types, we now don't use it outside of eth/api_tracer.go.  And the use there is now broken because the field is nil: when tracing a transaction you get a panic.  This fixes that by removing the field and updating the tracing code to not use it either.
Tested on an Alfajores node (also including the fix from #1611 so that it can sync properly), using:
```
debug.traceTransaction("0x6dadf6441d85903d5b4fa542eca8ff9e220f2940a1ba1bc63b3d90b5d0a2d642")
```
* With current master, you get a panic from creating the `vmRunner` using the context's `Header` field, because the method used (`api.eth.blockchain.NewEVMRunner()`) …
=> Remove 'Header' field from vm.Context.

contracts/reserve/tobin_tax.go, contracts/testutil/fail_runner.go, contracts/testutil/runner.go, core/vm/interface.go, core/vm/vmcontext/runner.go
Even though the Tobin tax calculation doesn't depend on the sender, the change (in PR #1465) of the sender from the transaction's sender to the zero account led to a bad block error (i.e. a hard fork change).  This was due to a conjunction of factors including the upstream implementation of EIP-161 not being quite correct for the case of Celo (because of the existence of system EVM calls made from celo-blockchain).  This commit reverts the change, by adding and using an `ExecuteFrom()` method on the EVMRunner type.
Confirmed that this fixes the bad block which previously appeared trying to sync to Alfajores (block 536) and that it now syncs successfully past that block.
This fixes a breaking change that is currently on master.  As such, it is incompatible with what is currently on master …
=> Go back to using the transfer's sender in Tobin tax calculation.

consensus/istanbul/backend/announce.go, consensus/istanbul/backend/announce_test.go, consensus/istanbul/backend/internal/enodes/version_certificate_db.go, consensus/istanbul/backend/internal/enodes/version_certificate_db_test.go, consensus/istanbul/core/backlog.go, consensus/istanbul/core/backlog_test.go, consensus/istanbul/core/commit.go, consensus/istanbul/core/commit_test.go, consensus/istanbul/core/core.go, consensus/istanbul/core/errors.go, consensus/istanbul/core/handler_test.go, consensus/istanbul/core/prepare.go, consensus/istanbul/core/prepare_test.go, consensus/istanbul/core/preprepare.go, consensus/istanbul/core/preprepare_test.go, consensus/istanbul/core/roundchange.go, consensus/istanbul/core/roundchange_test.go, consensus/istanbul/core/testbackend_test.go, consensus/istanbul/core/types_test.go, consensus/istanbul/proxy/forward_message.go, consensus/istanbul/proxy/proxy_engine_test.go, consensus/istanbul/proxy/types.go, consensus/istanbul/proxy/val_enodes_share.go, consensus/istanbul/types.go, consensus/istanbul/types_test.go
Message decoding and encoding, previously happened in 2 steps. This commit
makes decoding and encoding a message an atomic operation, either it
succeeds or it fails and the full result of decoding is now stored in the message.
It also enforces the mapping between message code and message type, reducing
burden on users who previously had to manage these mappings in multiple places.
This allows us to decode in just one place in the code, allowing us to
have a consistent approach to decode errors. By being able to respond to
decode errors at a higher level in the stack, we remove the need to pass
errors back up the stack to indicate invalid messages. It also helps
separate encoding and decoding logic from our domain logic. By storing
the result of the decoding we avoid repeating the decode …
=> Consolidate istanbul.Message encoding/decoding

miner/worker.go, miner/worker_test.go
Due to a logic bug in the `if`'s condition, the channel was only being sent to, never received from, causing it to hang on validators once enough transactions have been sent.  This PR fixes that and also ensures that if the channel is full we don't block the main loop.
* Automated testing
* Added regression tests for validator and non-validator cases which send lots of transactions to the channel and fail if deadlock results.  These tests would fail if the fix in this PR is undone.
=> Fix logic bug in worker, and protect against blocking.

core/genesis.go, core/genesis_test.go, params/protocol_params.go
Currently the Registry Proxy check in genesis is set to be a static number 2585, which may not make sense since there may be change in Proxy code & different compiler. Hence we want to reset the check so that any non-zero code size of RegistrySmartContractAddress will pass.
=> fix: Registry code size check

consensus/istanbul/backend/announce.go
This log line was incorrect, since the arguments after the log message (the first argument) have to come in key-value pairs.  This led to log lines such as:
```
{"":"\u003cnil\u003e","LOG15_ERROR":"Normalized odd number of arguments by adding nil","func":"announceThread","msg":"Error in checking if should announce","severity":"warning","timestamp":"2021-07-19T14:32:42.820625948Z"}
```
This PR fixes that.
=> Fix incorrect argument number in error logging

README.md
Improve code coverage and build analysis by surfacing the latest status and making deeper insights reachable in one click.
Currently, looking up code coverage and build status requires knowing where to find the information.
Markdown preview and https://shields.io.
N/A
N/A
=> Add Codecov and CircleCI status badges to the README

miner/worker.go
This metric was not being updated.  This PR updates it in such a way as to exclude the artificial inflation that can result on non-proposers due to the race condition described in https://github.com/celo-org/celo-blockchain/issues/1639#issuecomment-888611039
Ran locally with `--metrics` and some print statements, verified the metric gets set and that the times make sense (for both empty and full blocks)
=> Record values for the block construction metric

consensus/istanbul/backend/announce.go, consensus/istanbul/backend/engine.go
- Correct use of waitGroup, don't call Add in  a separate go-routine to the one in which the wait group was created.
- Declare announceThreadQuit before starting a go-routine that tries to read the variable.
None
CI
`go test ./e2e_tests -race` doesn't report on announce.go
- Fixes #1586 #1583 
Yes
=> Fix race conditions in announce.go

consensus/istanbul/core/core.go, mycelo/contract/gen_abis.go
Add Mu to deal with data race around roundChangeTimer.
None
`go test -race ./e2e_test` doesn't return data races on roundChangeTimer.
CI
- Fixes #1587 
Yes
=> Fix data race: roundChangeTimer

cmd/utils/flags.go, p2p/dial.go, p2p/dial_test.go, p2p/server.go
Fixes two behaviors in `p2p/Server` which cause it to get more dialed connections than it should based on the dial ratio (which in turn impairs the ability of new nodes joining the network to find peers with open incoming connection slots):
1. The bug described in #1669, which affects LES servers.
2. The fact that the dialer attempts two dials for every dialed peer connection it's missing: https://github.com/celo-org/celo-blockchain/blob/147571e5b5aab36b6de4d839a3ee9c1f85dbd94b/p2p/dial.go#L381
Initially I was planning to just fix #1669.  But then when I tested it out and saw that it still ends up with more dialed peers than it should, I remembered this `* 2` and realized that it would have to be removed in order to get the desired behavior.
This `* 2` was introduced upstream in …
=> Fix calculation and implementation of dial ratio and the max dialed connections limit

cmd/mycelo/main.go
I noticed this local variable, `buildpath` was misnamed as a result of copy/paste from this function: https://github.com/celo-org/celo-blockchain/blob/e8b674392d7c60c4e13cfc3a95d9f293fec5db57/cmd/mycelo/genesis_commands.go#L82-L93
This PR just renames it to `gethpath`, which is what it actually is
* CI tests
=> mycelo: change copy-pasted variable name to reflect what it is

.circleci/config.yml
As of today, the `lightest-sync-test` test in CircleCI started failing with the following error:
```
build/bin/geth: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by build/bin/geth)
```
It was using the `circleci/node:10` docker image, so presumably a new version of that image caused the change leading to this error.  However, the test doesn't use node.js, so there is no reason to use that image for it.  This PR modifies the test to use the golang executor we already have defined for other steps such as building geth.  That makes the error go away.
Trailing whitespace trimmed by my editor.
Verified as a draft PR that this fixes the problem and that the test now passes.
=> Fix broken circleci setup for lightest sync test

core/types/block.go, test/node.go
Currently, when unmarshalling `EpochSnarkData` structs from epoch blocks, the standard UnmarshalJSON function fails to convert a `hexutil.Bytes` value to `big.Int`.
This update adds a custom `UnmarshalJSON` function for `EpochSnarkData` in order to properly convert byte arrays into big.Int objects. 
I was not able to get the `gencodec` library to automatically generate an `UnmarshalJSON` function that properly handle conversions from `hexutil.Bytes` to `big.Int`, so I modified `gencodec` generated code and added it to `block.go` instead.
Also added a `MarshalJSON` function. Doesn't solve the bug, but added in case it was needed.
These changes were tested via the e2e test added on the …
=> add custom marshal function for epochsnarkdata

consensus/istanbul/backend/peer_handler.go
The validatorPeerHandler could not be closed because threadRunning
was never set to true so calling stopThread would exit early thinking the
validatorPeerHandler was already stopped and not actually stop anything.
CI is passing
Discovered while investigating #1657 
Yes
=> Fix failure to close in validatorPeerHandler

e2e_test/e2e_test.go, mycelo/genesis/base_config.go, mycelo/genesis/config.go, mycelo/genesis/genesis.go, mycelo/genesis/genesis_state.go, test/node.go
Because of the duplication of istanbul config in the codebase, (see #1693)
when using the test package it was difficult to understand which config
should be used, and possible to end up with conflicting istanbul config
in different parts of the system.
This commit makes it clear where the config should be set and enforces
consistent config across the two config objects.
Removes duplicated config field `UptiimeLookbackWindow` from mycelo config, mycelo now has one source of truth for this value.
Ran the following command:
```
make all && DIRNAME=mynew && rm -rf $DIRNAME && \
./build/bin/mycelo genesis --validators 3 --newenv $DIRNAME \
--buildpath ./monorepo/packages/protocol/build/contracts && \
./build/bin/mycelo validator-init $DIRNAME && ./build/bin/mycelo validator-run  $DIRNAME
``` …
=> Simplify e2e test configuration

.circleci/config.yml, tools/parsecov/main.go
Add a CI job to calculate coverage of the `istanbul` package achieved by the `e2e_test` tests and posts the result on the PR (see below).
Added tool to analyse coverage profiles and display per package coverage.
You can see it working on this PR
- Fixes #1641 
Yes, no existing system code was changed.
=> Add istanbul package e2e_test coverage job to CI

node/rpcstack.go, node/rpcstack_test.go
Cherry-picking from go-ethereum [this PR](https://github.com/ethereum/go-ethereum/pull/21646).
The fix from the PR is needed for Kong and the GCP LB to be able to redirect the websocket properly.
Tested in baklava forno env with and without Kong as proxy:
```
╰─ wscat -c wss://baklava-forno-k8s.celo-testnet.org/ws
Connected (press CTRL+C to quit)
> {"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":1}
< {"jsonrpc":"2.0","id":1,"result":"0x768513"}
```
```
╰─ geth attach wss://baklava-forno-k8s.celo-testnet.org/ws
Welcome to the Geth JavaScript console!
instance: celo/v1.4.0-unstable/linux-amd64/go1.16.8
at block: 7767331 (Wed Sep 22 2021 10:01:28 GMT+0200 (CEST))
modules: eth:1.0 net:1.0 rpc:1.0 web3:1.0
To exit, press ctrl-d
>
```
- Fixes #1683 
[This celo-monorepo …
=> Cherry-pick: node: relax websocket connection header check (#21646)

consensus/istanbul/backend/api.go, consensus/istanbul/backend/backend.go, consensus/istanbul/backend/engine.go, consensus/istanbul/backend/handler.go, test/node.go
`StartValidating` makes a call to `RefreshValPeers` while holding `coreMu` and
`RefreshValPeers` waits for all validator peers to be deleted and then reconnects
to known validators.
https://github.com/celo-org/celo-blockchain/blob/8b8e717689daaac8a854aa931df07009e7be0a34/consensus/istanbul/backend/engine.go#L664-L697
If any of those peers has called `IsValidating` before `RefreshValPeers` tries to
delete them the system gets stuck in a deadlock because `IsValidating` also tries
to acquire `coreMu` and the peer will never succeed because it is already held
by `StartValidating`, and `StartValidating` will never return because it is waiting for
all peers to disconnect.
This PR makes `coreStarted` into an atomic variable so that peers can make treadsafe
calls to `IsValidating` without needing …
=> Fix deadlock on engine start

.circleci/config.yml
This PR aims to make posting the the istanbul coverage comment summary on PRs less noisy.
* Rather than posting a new comment on every commit, (which can be pretty distracting for PRs that are undergoing lots of changes) we now update the coverage comment if it exists already.
* The coverage comment is now expandable and by default only shows overall coverage.
See it below, notice it has been edited several times.
#1692 
No system code was changed.
=> Reduce noise of e2e coverage comment

.circleci/config.yml, consensus/istanbul/backend/api.go, consensus/istanbul/backend/backend.go, consensus/istanbul/backend/engine.go, consensus/istanbul/backend/handler.go, params/version.go, test/node.go
This cherry-picks a set of commits from master that was a deadlock with StartValidating on 1.4.0.
This includes the minimal set of commits to test & fix the issue.
Commits
* Fix deadlock on engine start (#1685)
* Add more e2e tests to the celo-blockchain repo
* Remove coreMu read lock around rs.NewChainHead
- Fixes #1715
=> Release 1.4.1

.circleci/config.yml, consensus/istanbul/backend/engine.go, consensus/istanbul/backend/internal/replica/state.go
Fixes the deadlock in 1.4.0 by removing the read lock on `coreMu`.
* Adds a lock in the replica state & explains why one lock should not be held.
* Adds a replica E2E test
* Adds a CIP35 E2E test
CI (now with e2e replica test running.
- Fixes #1715
=> Fix Deadlock with StartValidating

.circleci/config.yml
Switches from node 10 to 12 to fix an issue with yarn using an unauthenticated git
protocol in the `monorepo-checkout` step
=> Switch to node12 for CI

accounts/abi/bind/backends/simulated.go, cmd/evm/internal/t8ntool/transition.go, cmd/utils/flags.go, consensus/istanbul/core/core.go, core/genesis.go, core/state_prefetcher.go, core/state_processor.go, core/state_processor_test.go, core/state_transition.go, core/tx_pool.go, core/tx_pool_test.go, core/types/transaction_signing.go, core/vm/contracts.go, core/vm/evm.go, core/vm/interpreter.go, core/vm/runtime/runtime.go, eth/state_accessor.go, eth/tracers/api.go, eth/tracers/tracer_test.go, internal/ethapi/api.go, internal/ethapi/transaction_args.go, les/state_accessor.go, light/txpool.go, miner/stress/1559/main.go, miner/worker.go, mycelo/genesis/config.go, mycelo/loadbot/bot.go, params/config.go, tests/init.go, tests/state_test_util.go
This enables mycelo and e2e tests to set the espresso block number.
This is was done to test celo typed transactions and espresso.
This commit also renames any reference of "E" hardfork or block
to "Espresso".
Also updates the mycelo load bot to use the latest signer instead of
the homestead signer.
Unit test, CI. Tested that e2e tests can activate the Espresso fork.
Yes
=> Fix espresso block config and rename E to espresso

core/vm/analysis.go, core/vm/analysis_test.go, core/vm/instructions.go, core/vm/interpreter.go
Depends on #1695 
Hotfix from upstream that fix an incorrect EVM execution bug.
As we have only one client and it was not something that could cost a balance withdraw, we left this fix for the Espresso HardFork.
- Fixes #1767 
No, but part of the Espresso HF
=> Upstream hotfix from 1.10.8

contracts/abis/abi_str.go, contracts/gasprice_minimum/gasprice_minimum.go, core/error.go, core/tx_list.go, core/tx_pool.go, core/tx_pool_test.go
This fixes the issue that adds txs with gasPrice zero, which will not be executed but we keep for at lest 3 hours (default expiration time), and fill the txpool with peding txs
Manually and add unit tests
- Fixes #1768 
Yes
=> [tx_pool] Invalidate txs with gasPrice < gasPriceMinimumFloor

accounts/abi/bind_v2/auth.go, accounts/external/backend.go, core/tx_pool.go, core/types/celo_dynamic_fee_tx.go, core/types/receipt.go, core/types/transaction.go, core/types/transaction_marshalling.go, core/types/transaction_signing.go
Implements a typed transaction that is specific to the Celo network.
To Do
I was able to send a dynamic fee transaction through the system. I have not tested more specific portions yet.
=> Celo Typed Transactions

core/state_processor.go, core/tx_pool.go, core/tx_pool_test.go, eth/api_backend.go, eth/backend.go, internal/ethapi/api.go, internal/ethapi/backend.go, les/api_backend.go, les/client.go, light/txpool.go, node/config.go
Depends on #1695
Implementation of the CIP 50, that makes the replay protection optional
No. Part of the Expresso hard fork
=> [CIP-50] optional replay protection

.circleci/config.yml
This was previously changed accidentally in #1731.
Also updated the cache key for the prepared system contracts to include
the executor image, so that any image change will cause
prepare-system-contracts to run, which should alert us to any problems
before we merge any changes.
=> Use node10 for prepare-system-contracts build step

consensus/istanbul/backend/backend.go, consensus/istanbul/backend/handler.go, consensus/istanbul/backend/peer_handler.go, consensus/istanbul/core/core.go, consensus/istanbul/core/handler.go, core/blockchain.go, core/blockchain_test.go, e2e_test/e2e_test.go, eth/backend.go, eth/downloader/downloader.go, eth/ethconfig/config.go, eth/handler.go, eth/sync.go, internal/syncx/mutex.go, miner/miner.go, miner/worker.go, p2p/dial.go, p2p/peer.go, p2p/server.go, test/node.go, test/tracker.go
This PR adds a test that starts and stops nodes in a small network and verifies that the network can continue to function correctly throughout the process.
A quick overview of what the test does:
1. Start 4 nodes
2. Verify they can confirm a tx
3. Stop one node
4. Verify the remaining 3 can confirm a tx
5. Stop another node
6. Verify the remaining 2 cannot confirm a tx
7. Start the last stopped node
8. Verify that the previously un-confirmable tx can now be confirmed by the 3 running nodes.
9. Verify that the 3 running nodes can confirm a further tx
10. Start the remaining node
11. Verify that the netowrk can process another tx and that all sent txs have been processed by all nodes.
This PR makes the minSyncPeers, dialHistoryExpiration and InboundThrottleTime configurable, in order for …
=> Add start stop e2e test

e2e_test/e2e_test.go, test/account.go, test/node.go
Previously each node owned a validator account and a 'dev' account and
nodes could execute txs using the dev account. Now transaction sending
has been moved to the account object and nodes simply hold the validator
account, this more closely represents the real world situation.
=> e2e_test: separate account from nodes

consensus/istanbul/backend/engine.go
Some tests were failing for example:
```
=== RUN   TestRecentMessageCaches
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xa07362]
goroutine 1070 [running]:
github.com/celo-org/celo-blockchain/consensus/istanbul/backend.(*Backend).newChainHeadLoop(0xc000881c00, 0xc005cd9400)
/home/circleci/repos/geth/consensus/istanbul/backend/engine.go:610 +0x82
created by github.com/celo-org/celo-blockchain/consensus/istanbul/backend.(*Backend).SetChain
/home/circleci/repos/geth/consensus/istanbul/backend/engine.go:599 +0x8c
FAIL	github.com/celo-org/celo-blockchain/consensus/istanbul/backend	79.150s
```
This Was because go routines started by SetChain were attempting to
subscribe to events on the blockchain event mux …
=> Fix race condition in backend tests

test/node.go
Previously the code panicked, now an error is returned with the command
required to build the contracts.
=> Better err output when no contracts dir in e2etest

.circleci/config.yml
Set git to re-write git urls to use https instead of git, we need to do this because github is phasing out the use of the git protocol -https://github.blog/2021-09-01-improving-git-protocol-security-github.
=> Fix checkout-monorepo ci job

consensus/consensustest/mockprotocol.go, consensus/istanbul/backend/engine.go, miner/worker.go
As a temporary measure to address low signature inclusion rates, this PR adds back a sleep in the
consensus engine before adding the parent seal to the block.
This sleep was removed in https://github.com/celo-org/celo-blockchain/pull/1545 as part of a
refactor and performance improvement, but was not implemented to account for adding time to
aggregate extra received commits to the parent seal. As a result, blocks produced by validators with
versions >= v1.4.0 include fewer signatures in the parent aggregated seal. This seal provides an
important signal to validators as to the performance of their nodes and is used by the protocol to
calculate rewards, although rewards will only be effected if the validators signature does not
appear in 13 or more consecutive blocks.
None
WIP
- Realted: …
=> Reinstate delay before signature aggregation in backend.Prepare

core/types/transaction.go
=> Fix tx DecodeRLP for rlp lists

core/tx_list.go, core/tx_pool.go, core/tx_pool_test.go
Cherry pick from upstream 067084fedab1d50e224e40e6442a7740fc53611a 
https://github.com/ethereum/go-ethereum/commit/067084fedab1d50e224e40e6442a7740fc53611a
Potentially fixing this issue seen in a different L1:
https://github.com/ethereum/go-ethereum/issues/23690
=> Fix race condition in tx pool (upstream cherry pick)

core/tx_list.go, core/tx_pool.go
This PR fixes a memory leak found while running v1.5.0 nodes before the Espresso fork.
`txPricedList` keeps both a list of all txs in the pool, and also a heap for fast access to the cheapest txs. These heaps are not always synchronized with the txs list: *they increment at the same time as the list, but they do not decrement at the same time*. To decrement, the txpool marks how many txs are 'stale', and after a critical point, a `Reheap()` is called, where the whole memory of the heaps is released and they are recreated.
The issue in the code was that the critical point was never reached, and the heaps grew indefinitely. Strangely, the behavior is different after Expresso HF activation, since then `Reheap()` is called periodically on changes for the base fee. But before the HF nothing …
=> Ensure txPricedList reheaps regularly (avoid tx memory leak)

core/tx_list.go
Fixes the multiCurrencyPriceHeap Pop function. It should return the minimum price tx, so it searches for the minumum across all price heaps (nil currency and non nil currencies). A missing assigment provokes erroneous comparisons.
=> Fix minimum search in multicurrencyprice heap Pop

params/config.go
Update Mainnet Espresso activation block number: 11873000 => March 8th, ~12:15 PST
=> Update Mainnet Espresso block number

eth/api.go, eth/api_backend.go, internal/ethapi/api.go
The `eth` RPC API after expreso required some amending.
On ethereum, `baseFee` ( called `gasPriceMinimun` on Celo) is present on the block header. For Celo, it's present on the `GasPriceMinimum` contract, and it also needs to be denominated in all different fee currencies. 
This difference poses a problem on the RPC, since whenever a `Transaction` or a `TransactionReceipt` is constructed, the `gasPrice` field is computed for new transaction. To do so, it uses the `baseFee`. Obtaining the `baseFee` for block X is easy on Ethereum and hard on Celo; since it's a smart contract call, the node needs to have the `state` available but that's not true for historical blocks on any node that it's not an archive node.
To solve this issue, this PR takes the following approach:
* If node has access to …
=> Eth api using baseFee only when needed

params/config.go
The previous calculation of the block number (`11873000`) did not contemplated that February have 28 days.
To avoid miscommunication, we keep the same date `March Tuesday 8th, 12:15 pm PST`, but the actual block for that date is the `11838440`
=> Fix mainnet espresso activation block number

consensus/istanbul/backend/backend.go, consensus/istanbul/backend/engine.go, params/version.go
The verification of a proposal should ignore the AggregatedSeal but verify the ParentAggregatedSeal. The code instead calls VerifyHeader which, if the AggregatedSeal is empty (which happens on every proposal) returns immediately and never checks for the ParentAggregatedSeal.
In this PR we instead call a new function `verifyHeaderFromProposal` which enforces that the AggregatedSeal signature is empty, and then checks for the ParentAggregatedSeal.
This PR is applied on top of the 1.4.x version branch
=> Enforce proper check of ParentAgregatedSeal during preprepare phase (1.4.x release)

internal/ethapi/api.go
Fixed wrong use of Go keyword `fallthrough`
=> Fix wrong use of fallthrough

miner/block.go, params/version.go
In the course of getting Baklava into condition to restart block production, I noticed that the
miner would fail to initialize on nodes that had replaced there chain data from backup. The observed
error was that the randomness commitment cache would fail to be populated, which is caused by
replacing the chain data on that node. This error is supposed to be recoverable, but no code
existed on the code path that was failing to do so. Recovery would only occur after syncing to the
network, which these nodes did not do.
This PR adds a conditional to try recovering the randomness cache once if there is a cache miss
during miner initialization.
None
Ran these changes on cLabs Baklava validators and got to a correctly initialized state
=> Improve miner to recover from randomness cache miss on initialization

.circleci/config.yml
Circle CI race test is taking too long and always flaky. Flakyness needs to be addressed later, but for the moment it's best not to run on every branch but on master and release branches.
=> Run race test only on master and release branches

e2e_test/e2e_test.go, eth/backend.go, eth/ethconfig/config.go, eth/handler.go, eth/sync.go, ethclient/ethclient.go, internal/ethapi/api.go, internal/ethapi/api_test.go, p2p/dial.go, p2p/server.go, test/account.go, test/node.go, test/tracker.go
Cherry pick #1837 to release/1.5.x
Also cherry picked a few commits related to the e2e test, required for the #1837 to run properly:
67e6a6aba Add start stop validators e2e test
35b3d7e43 Fix panic on StopTracking
f9dbb7f6d Use ephemeral key for validator p2p network
2cb021a42 Allow configuring the min peers needed to sync
727c3e54b Allow modification of dial and connection timeouts
704ec7dfa Remove unused debug function
7c463961f Add debug stack trace to help track down failures
1ab51ee37 Dont print expected errors on e2e test shutdown
636d59437 e2e_test: separate account from nodes (#1777)
2a0c6ef4e Better err output when no contracts dir for e2etest (#1793)
=> Cherry pick #1837 to 1.5.x

miner/block.go, params/version.go
_This PR cherry picks #1840 to `master`. A copy of the description is included here_
In the course of getting Baklava into condition to restart block production, I noticed that the
miner would fail to initialize on nodes that had replaced there chain data from backup. The observed
error was that the randomness commitment cache would fail to be populated, which is caused by
replacing the chain data on that node. This error is supposed to be recoverable, but no code
existed on the code path that was failing to do so. Recovery would only occur after syncing to the
network, which these nodes did not do.
This PR adds a conditional to try recovering the randomness cache once if there is a cache miss
during miner initialization.
* Changed the version number of 1.6.0-unstable to align with our …
=> Cherry pick #1840 to master

.circleci/config.yml, consensus/istanbul/backend/announce_test.go, e2e_test/e2e_bench_test.go, e2e_test/e2e_test.go, ethclient/ethclient_test.go, ethclient/gethclient/gethclient_test.go
This PR comments/skips tests, builds and benchmarks that are known to be flaky.
Unit tests:
- TestAnnounceGossipQueryMsg #1849
- TestEthClient/TestCallContract #1850
- TestGethClient/TestAccessList #1851
Benchmarks:
- BenchmarkNet1000Txs #1852
Circleci builds:
- end-to-end-cip35-eth-compatibility-test #1853
While creating this PR, the istanbul-e2e-coverage failed once, then worked when it was re-run. I'm not skipping this one right now since I'd like to test it a bit more. Most likely it is because the parent commit has flaky tests, which are run for coverage report.
codecov/project is failing because we are removing a few tests. It is expected.
=> Skipping flaky tests

e2e_test/e2e_test.go, eth/tracers/api.go, test/node.go
This PR fixes the concurrent map access error in the ticket linked below.
The problem was that `state.StateDB` instances were being accessed from multiple go-routines, and they are not safe for concurrent use.
Added an e2e test to ensure that the fix is working.
- Fixes #1799
=> Fix concurrent map access error when tracing blocks

e2e_test/e2e_test.go, eth/tracers/api.go, test/node.go
Fixes  https://github.com/celo-org/celo-blockchain/issues/1799
This commit ensures that state.StateDB instances are not
accessed concurrently when tracing blocks and also adds
an e2e test to verify the fix.
It also disables logging from the e2e tests, because the logs
slowed the tests down and cluttered the output of test runs.
It also updates test node instances to ensure that all rpc api
modules are enabled.
=> Fix concurrent map access error when tracing blocks (#1822)

miner/worker.go
What this PR does is better described [here](https://github.com/celo-org/celo-blockchain/pull/1858#issuecomment-1054159493)
Fixes #1856 
Before introducing this change gas estimations against the pending block on non validating nodes with the espresso fork enabled would sometimes be lower than they should be.
Its still not clear to me exactly how the lower gas estimates were being calculated but ensuring that the pending block is finalized and assembled seems to resolve this. Validating nodes were already finalizing and assembling their pending blocks and looking back it seems that prior to #1545 the pending block was always finalized and assembled (see permalink below). So this seems like this change is correcting a long running problem. …
=> Ensure pending state is ready for tx execution

miner/worker.go, params/version.go
This PR cheery picks https://github.com/celo-org/celo-blockchain/pull/1858 to the release branch,
1.5.x and additionally sets the version number to `1.5.4-stable` for release.
=> Cherry pick #1858 to release/1.5.x

e2e_test/e2e_transfer_test.go, mycelo/genesis/genesis.go, test/node.go, test/utils.go
Added e2e transfer test cases:
- LegacyTxType eth compatible
- LegacyTxType eth incompatible
- AccessListTxType
- DynamicFeeTxType with tip gas equal to `MaxFeePerGas - BaseFee`
- DynamicFeeTxType with tip gas equal to `MaxPriorityFeePerGas`
- CeloDynamicFeeTxType with tip gas equal to `MaxFeePerGas - BaseFee`
- CeloDynamicFeeTxType with tip gas equal to `MaxPriorityFeePerGas`
- Added Espressso Hardfork block in mycelo ChainConfig.
- Updated a usage of deprecated `eth.Config` to `ethconfig.Config`
`go test ./e2e_test -run TestTransferCELO`
- Fixes #1788 
Yes, only added tests
=> Add e2e transfer test

cmd/geth/main.go, cmd/geth/usage.go, cmd/utils/flags.go, eth/api_backend.go, eth/backend.go, eth/ethconfig/config.go, eth/ethconfig/gen_config.go, eth/tracers/api_test.go, graphql/graphql_test.go, internal/ethapi/api.go, internal/ethapi/backend.go, les/api_backend.go
Adding a gas inflation rate flag, to multiply the gas estimations from the rpc call.
This aims to mitigate the gas estimation bug until we found the actual fix for it
Run tests
Yes
=> Gas Inflation Rate flag

.circleci/config.yml
Ensure the deprecated git protocol is not used when preparing the system
contracts.
Indirectly tested, builds of our latest release branch were failing because the `checkout-monorepo` job was being executed without the git config provided here, on master the config exists for `checkout-monorepo` so that is not failing and the cache is currently being used for preparing the system contracts so that is also not failing. But I believe it would fail if the cache was not used.
=> Ensure CI doesn't use deprecated git protocol

params/config.go
The espresso activation blocks were not set on master, this was causing the lightest sync test to fail on CI and probably would have caused many other problems.
I think the process for making changes to release branches should be to merge the change first on master and only ever cherry pick to a release branch. That should help us avoid such situations in the future.
=> Set the espresso activation blocks

core/vm/vmcontext/runner.go
Removed two unused methods in the evmRunnerContext interface in order to implement it more easily. e.g. in `cmd/evm/execution.go`
None
N/A
Yes
=> Remove unused methods in evmRunnerContext interface

p2p/peer.go, p2p/peer_error.go
Cherry picking this [pr](https://github.com/ethereum/go-ethereum/pull/24507) from upstream.
All other implementations store disconnect reasons as a single byte,
so go-ethereum should do it too.
=> p2p: define DiscReason as uint8 (#24507)

p2p/peer.go, p2p/peer_error.go
Cherry picking this to `release/1.5.x` from  our master originally from
upstream PR (#24507) 
All other implementations store disconnect reasons as a single byte,
so go-ethereum should do it too.
Co-authored-by: Felix Lange <fjl@twurst.com>
=> p2p: define DiscReason as uint8 (#1886)

accounts/abi/bind/backends/simulated.go, core/state_prefetcher.go, core/state_processor.go, core/sys_context.go, core/tx_pool.go, eth/api_backend.go, eth/state_accessor.go, eth/tracers/api.go, eth/tracers/api_test.go, internal/ethapi/api.go, les/api_backend.go, les/state_accessor.go, miner/block.go
Instead of providing an `EVMRunner` to `core.NewSysContractCallCtx` we now provide the header, state and an evm runner factory. This allows us to ensure that the state is copied before passing it to the evm runner, thus ensuring that the given state is not modified. This also encapsulates that responsibility so that callers do not have to be aware of it.
This solves our gas estimation problem, that was being caused by executing multiple transactions/call with the same access list, specifically in this case executing all the calls for `core.NewSysContractCallCtx` and then estimating gas for a transaction without first clearing the access list.
We could have instead ensured that we called `StateDB.Prepare` on the state after calling `core.NewSysContractCallCtx` but copying the state seemed …
=> Ensure copy of state used to generate block context

.circleci/config.yml, Makefile, README.md, monorepo_commit
The tests under `./e2e_test` were running against the system
contracts at version `celo-core-contracts-v3.rc0`, this PR updates
that version to be `core-contracts.v6` (because that is the most recently deployed version) .
Please test this by running `make prepare-system-contracts` and checking that the monorepo checkout (normally under `../.celo-blockchain-monorepo-checkout` relative to the `celo-blockchain` root) is set to version `core-contracts.v6` and that the contracts under `./compiled-system-contracts` have been updated and then run the new e2e tests `go test ./e2e_test` and check that they pass.
You will need node v12 installed for this to work, which is a change from the previous requirement of v10.
The make rule `prepare-system-contracts` was broken and didn't
build new versions …
=> Update core system contracts for new e2e tests

consensus/istanbul/types.go, consensus/istanbul/types_test.go, eth/protocols/eth/handler.go, eth/protocols/eth/protocol.go, params/version.go
This PR modifies `RoundChangeCertificate` encoding so that we don't serialize `N` times the proposal, instead we do that only once.
Change is not backward compatible, requires 2/3 of validators to use the new version at that same time
=> Reduce Preprepare size

consensus/istanbul/backend/api.go, consensus/istanbul/core/commit.go, consensus/istanbul/core/core.go, consensus/istanbul/core/prepare.go, consensus/istanbul/core/preprepare.go, consensus/istanbul/core/types.go, internal/web3ext/web3ext.go
Adds the api methods `gossipPrepares`, `gossipCommits` and `resendPreprepare`.
=> Add manual force re-send and gossip of consensus messages

.circleci/config.yml
Starting with commit ba64ac2823be9cd80b5472967df7df1b6a50a918 the android test began failing, despite changing nothing related to the android build. Seemingly the failure is due to an infrastructure change outside of the main codebase. This PR comments out the android build CI test as a temporary deprioritization.
All other CI tests.
Only changes the CI config file.
=> Remove android CI test

consensus/consensustest/mockprotocol.go, consensus/istanbul/backend/backend.go, consensus/istanbul/backend/engine.go, consensus/istanbul/backend/engine_test.go, consensus/istanbul/backend/handler.go, consensus/istanbul/backend/snapshot.go, consensus/istanbul/uptime/monitor.go, core/types/block.go, core/types/celo_additions.go, core/types/istanbul.go, core/types/istanbul_test.go, core/vm/contracts.go, eth/downloader/queue.go, eth/downloader/resultstore.go
The race detector found a problem when running with `go test -race -count=1 ./eth/downloader`.
It turns out that
https://github.com/celo-org/celo-blockchain/blob/67b6239118b04abf329a8cafea533727603d0260/eth/downloader/queue.go#L505 emits a pointer to a value owned by the `resultstore`.
This value is later changed here (added in the [latest upstream pull](https://github.com/celo-org/celo-blockchain/pull/1593)):
https://github.com/celo-org/celo-blockchain/blob/620b5fca2b8eeec1a00c9246c9141264991cfda1/eth/downloader/queue.go#L531-L534 but also accessed here in `AllDone`:
https://github.com/celo-org/celo-blockchain/blob/67b6239118b04abf329a8cafea533727603d0260/eth/downloader/resultstore.go#L154
I guess this patch is the easy solution to avoid the race, but there might be a better way to avoid …
=> Fix data race in downloader

internal/ethapi/api.go
The tx.type field was not added to the marshaled json struct when requested via rpc.
=> Add missing tx.type field in the json marshal of a tx receipt

core/sys_context.go, eth/tracers/api.go
The tracer was not using the same block context for every tx (it was generating a new context for every tx)
- Fixes #1983 
Yes
=> Fix tracer block context

internal/ethapi/api.go
Cherry pick from 1.7.1 hotfix ( 86eb9876d3473806a7ca47da80ac9c6d59a1d5e9 )
=> Add missing tx.type field in the json marshal of a tx receipt (#1985)

.circleci/config.yml
Currently `E2E_TESTS_FORCE_USE_MYCELO` is set via the CircleCI project settings. Those settings are not forwarded to CI running for PRs from forked repositories. This leads to problems like in this [PR](https://github.com/celo-org/celo-blockchain/pull/1986) ([build](https://app.circleci.com/pipelines/github/celo-org/celo-blockchain/8617/workflows/60656f24-0e27-4801-aa0f-beda72c64dec/jobs/91074)).
Instead, we define the variable directly in the CI config.
I created this PR from my fork, so this should test it.
=> ci: Set `E2E_TESTS_FORCE_USE_MYCELO` in e2e tests

consensus/istanbul/core/core.go, consensus/istanbul/core/handler.go, e2e_test/e2e_test.go, miner/worker.go
Prior to this change the RoundStateDB was never closed. This could result in leaked goroutines from its internal leveldb instance.
This change caused the TestStartStopValidators e2e test to fail because changing the rsdb open to be in the startup code, slowed down the start method for core this caused the gossiping of the manually added peers (done in the test after starting each previously stopped node )to happen after the validator peer handler had removed all the peers resulting in gossiping certs to no one. Thus leaving the network in a disconnected state.
The fix was really hacky, but just to wait 250ms after starting a node and hoping that the validator peer handler will have removed nodes by that point and then add the peers and then wait a little for them to be registered and then …
=> Ensure RoundStateDB is closed when core is stopped

consensus/istanbul/celo-ibft-spec.md
The note explains why the protocol needs round change certificates and prepared certificates. Something that is not immediately obvious when reading the spec.
=> Add clarifying note to ibft spec

.github/ISSUE_TEMPLATE/chore.md, .github/ISSUE_TEMPLATE/design_task.md, .github/ISSUE_TEMPLATE/feature.md, .github/ISSUE_TEMPLATE/issue.md, .github/ISSUE_TEMPLATE/question.md
The `triage` label is automatically applied to all incoming issues so that we can use workflow automation.
Github allows some workflow automation based on labels. This label is automatically applied to all created issues so that we could implement the triage process. It removes the `blockchain` label as its usage seems to be inconsistent and doesn't carry any additional meaning.
No.
=> Auto apply triage label

test/node.go
There is no `compiled-system-contracts` make target, but `make prepare-system-contracts` creates the necessary files.
=> Update error msg when contracts are not made yet

.circleci/config.yml
Changes the PR_COMMENT_TOKEN used to authenticate to github, to be a github organization app token instead of a personal access token, but generated by akeyless for each run.
Now it should use the akeyless context in circle ci to access the accessid variable, which is a nonsensitive id to know which akeyless auth method to use for circle ci.  This should use oauth2 to authenticate to akeyless by the circle CI organization and project ID, and have access to generate a temporary secret that gives access to write to PRs for the the celo-blockchain  github repository.
Then using the akeyless command line utility to generate the new key, it saves it and persists it via workspaces to share with the necessary jobs.
Testing with this PR
Should be fully backwards compatible, leaving piersy's …
=> testing akeyless workflow

.circleci/config.yml
moving circle ci access id to file instead of env variable
should allow access
=> putting access id directly in file instead of env variable

cmd/uptime/report.go
`--datadir` cannot be passed in as a local flag for`uptime report`. Per #1914, `./build/bin/uptime report --epoch 786 --lookback 12 --valset 110 --datadir ~/chaindata/fastsync` would fail (though note that `./build/bin/uptime --datadir ~/chaindata/fastsync report --epoch 786 --lookback 12 --valset 110` worked). This adds `--datadir` as a local flag as well and migrates the flags to global context (so that the datadir is instantiated properly).
- Tested this locally against chaindata from a mycelo testnet
- Fixes #1914
Yes, just adds the ability to add the datadir param as a local flag (in addition to global).
=> Add local datadir flag and migrate flags

core/blockchain.go
Fixes https://github.com/celo-org/celo-blockchain/issues/1920
This just applies the change suggested in the issue. It seems reasonable and passed the tests, but I don't understand which situation would cause nil return values, yet.
=> More nil checking in InsertReceiptChain

.github/workflows/config.yml, Makefile, monorepo_commit
* Only allow tags or commit hashes to be specified in `monorepo_commit`
* Keep monorepo checkouts in a different dir per specified commit to allow fast switching
Closes https://github.com/celo-org/celo-blockchain/issues/1956
=> Stricter `make prepare-system-contracts`

cmd/utils/flags.go, console/console_test.go, core/genesis.go, core/genesis_test.go, docs/docs/_getting-started/dev-mode.md, docs/docs/_interface/Command-Line-Options.md, miner/miner_test.go
- Overwrites the developer block period flag (`--dev.period`), which wasn't happening before.
- Ensures that the validator & txFeeRecipient vals are set in the config for dev mode, which should (mostly) fix `--dev` mode
- Although this is a bit messy (in that we are re-setting this value after it has been set above), I think it strikes a balance of making dev mode work & not cluttering the rest of the code too much.
- Updates developer docs in `dev-mode.md` & parameter details to reflect the status quo
Note that the `geth --dev` command is still somewhat broken in terms of account configuration. For now, it runs as expected when using the hard-coded dev account (both in "ephemeral" mode & with a persistent data directory) but doesn't work properly for "general" accounts/data directories. …
=> Overwrite developer genesis block period with flag value

consensus/istanbul/core/message_set.go, consensus/istanbul/core/message_set_test.go, consensus/istanbul/core/roundstate.go, consensus/istanbul/core/roundstate_db.go, consensus/istanbul/core/roundstate_db_test.go, consensus/istanbul/core/roundstate_save_decorator.go, consensus/istanbul/core/testutils_test.go
Split the roundstate saving, allowing consensus message processing to be a bit faster.
=> Split roundstate saving in two

accounts/abi/bind/backends/simulated.go, eth/filters/api.go, eth/filters/filter.go, eth/filters/filter_system_test.go, mycelo/cluster/node.go
Adding the `baseFeePerGas` to blocks returned by `EthSubscribe` makes the results more consistent with the data returned on Ethereum and via other RPC-Endpoints on Celo. And it is useful!
Once we add the `baseFeePerGas` to the header, this implementation is not needed anymore. So this change is only temporary.
I did not check for `RPCEthCompatibility` since this is not done for `baseFeePerGas` in the normal JSON-RPC responses, either.
* Enabled websockets for mycelo
Tested against mycelo with the following code
```json
{
"name": "subs",
"version": "1.0.0",
"main": "index.js",
"license": "MIT",
"dependencies": {
"web3": "^1.9.0",
"web3-providers-http": "^1.9.0"
}
}
```
```js
const Web3WsProvider = require('web3-providers-ws');
var provider = new Web3WsProvider('ws://localhost:9545');
const …
```
=> Add baseFeePerGas to headers sent via EthSubscribe

.github/workflows/config.yml, .golangci.yml
- Switches CI to use the committed version of `golangci-lint`
- Use smaller runners for small jobs
- Disable `unused` lint for now
- Has been enabled upstream later: https://github.com/ethereum/go-ethereum/pull/24783
=> ci: Fix lint job

core/vm/contracts.go, core/vm/contracts_test.go, e2e_test/e2e_test.go, eth/tracers/api_test.go, test/account.go, test/node.go
This PR fixes a bug in transfer precompile length checking and adds a few tests for CELO transfers made via the transfer precompile (i.e. `GoldToken.transfer`). Specific test changes (and associated changes):
- e2e:
- `TestTraceSendCeloViaGoldToken`
- sends CELO via `GoldToken.transfer`
- added some helper functions to the `test` package to make it easier to send transfers via `GoldToken.transfer` in future tests
- made the function `ValueTransferTransaction` more general (making it possible to pass in tx data)
- tracers/api_test: 
- `TestCallTraceTransactionPrecompileTransfer`: more directly invokes the transfer precompile by sending the tx from a registered GoldToken address. Does more in-depth checking of the expected traces (from `callTracer`) with some documentation (in comments) …
=> Add test cases for native and precompile transfers and tracing

internal/ethapi/api.go
For compatibilty with ethers 6, which fails with `Error: invalid value for value.difficulty`, otherwise.
The regression test is included in https://github.com/celo-org/celo-blockchain/pull/2081. This PR is provided separately, in case the other PR takes long to merge due to a potentially required node version update for recent ethers versions (node>=14).
- Fixes https://github.com/celo-org/celo-monorepo/discussions/9922#discussioncomment-5818085
Adding a field to the JSON object should be harmless for reasonably implemented users. I also don't know a way to fix the problem in an even safer way.
=> Add difficulty to JSON-RPC blocks

.github/workflows/config.yml
This runs CI on both
- PRs that target `feature-split`
- new commits to `feature-split`
=> Enable CI on `feature-split`

e2e_test/ethersjs-api-check/package-lock.json, e2e_test/ethersjs-api-check/package.json, e2e_test/ethersjs-api-check/test/test.ts
Ethers 6 requires the `difficulty` field in blocks returned via JSON-RPC. To verify compatibility, we need to update our ethers compatibility test to a recent ethers version. That in turn requires updates of typescript (easy since it is local to the test.
The tests run fine with our current node version in CI ([node 12](https://github.com/celo-org/celo-blockchain/blob/7d8fd1b8c8bf35c809f7328854af9554ae894c64/.github/workflows/config.yml#L30)). However, node 12 is not officially supported with ethers 6:
```
npm WARN notsup Unsupported engine for ethers@6.3.0: wanted: {"node":">=14.0.0"} (current: {"node":"12.22.12","npm":"6.14.16"})
npm WARN notsup Not compatible with your version of node/npm: ethers@6.3.0
npm WARN notsup Unsupported engine for mocha@10.2.0: wanted: {"node":">= 14.0.0"} …
```
=> Update test for ethers compatibility to ethers 6

cmd/evm/internal/t8ntool/transition.go, crypto/bls12377/arithmetic_decl.go, crypto/bls12377/arithmetic_fallback.go, crypto/bls12381/arithmetic_decl.go, crypto/bls12381/arithmetic_fallback.go, crypto/bls12381/fp_fallback.go, mycelo/contract/gen_abis.go
Having all code formatted by the same tools helps with consistency and reduced diffs. Why go 1.18?
* Geth v1.10.9 shows no formatting differences when that version is used for formatting
* Later versions do
* Geth v1.10.9 uses go1.15 in its go mod. But that go version is so old that using it causes a large amount of additional errors during compilation and I want to avoid using different versions for compilation and formatting.
* Formatting with go 1.18 and 1.15 yields the same results (at least for geth and celo-blockchain)
Problems not solved which would be solved by moving to golint1.51.1 and go1.19 formatting (which have to go together):
* Linting fails locally
* Linting in CI did not catch that our formatting diverged from the gofmt output
Replaces …
=> Apply `go1.18.10 fmt ./...`

internal/ethapi/api.go
We add the value to a map, so our usual struct encoding steps do not apply and we have to explicitly ensure that it is hex encoded (as should be the case for all [quantities returned in JSON RPC](https://ethereum.org/en/developers/docs/apis/json-rpc/#quantities-encoding)).
We missed this because the RPC is only e2e tested using Ethers and that
consumed the plain number without complaint.
=> Hex-encode difficulty in RPC

accounts/abi/bind/backends/simulated.go, cmd/evm/internal/t8ntool/transition.go, core/state_transition.go, core/tx_pool.go, core/vm/evm.go, core/vm/runtime/runtime.go, internal/ethapi/api.go, params/config.go
This links the `berlin` and `london` hardfork flags to the espresso hardfork. Using them removes abiguity in the code and reduces the diff to upstream.
=> Bring back ethereum hardfork flags

.github/workflows/config.yml
Force to fail the CI job if there is any failed unit test
=> Force failure if there is any unit test failed

params/config.go
Enable the G hardfork in the tests by default.
=> Enable G fork by default in `TestChainConfig`

consensus/istanbul/backend/pos.go
Required changes to implement [CIP 54](https://github.com/celo-org/celo-proposals/pull/320)
TODO
Fixes https://github.com/celo-org/celo-blockchain-planning/issues/22
Changes consensus rules and will therefor be enabled with the next hardfork.
=> CIP 54: Don't send community rewards to reserve

core/vm/vmcontext/context.go
Remove tobin tax deduction with next hardfork.
I tested this manually by running the `TestTransferCELO` test first without changes. This showed deduction of tobin tax. Then I changed the hardfork flag to always return true and made sure that the tobin tax deduction code is not run anymore.
- Fixes https://github.com/celo-org/celo-blockchain-planning/issues/18
Changes consensus rules and will therefor be enabled with the next hardfork.
=> CIP 55: Remove Tobin Tax

.github/workflows/config.yml
We had a recent CI run where jobs got stuck for >4h: https://github.com/celo-org/celo-blockchain/actions/runs/5265057793
To prevent this add a timeout to all e2e jobs.
=> CI: Add timeouts to e2e jobs

.github/workflows/config.yml
CI runs on master fail because the `github.head_ref` is only set for PRs, not normal commits.
It is solved by using a fallback as recommended in https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-using-a-fallback-value
=> Fix CI runs on `master`

core/bench_test.go, core/state_transition.go, core/tx_pool.go, eth/tracers/js/tracer.go, light/txpool.go, tests/transaction_test_util.go
This reverts commit c8843c1c80910494dba8d7075213fa2933ccd91e. #2102 made a change in the state_transition that ended up forking mainnet blocks. We can re-create the cleanup in smaller chunks afterwards, to avoid this problem.
=> Revert "Cleanup/tx processing (#2102)"

cmd/geth/usage.go
But the `--disablerpcethcompatibility` under the deprecated options section:
```
ALIASED (deprecated) OPTIONS:
[...]
--graphql.port value                GraphQL server listening port (deprecated, graphql can only be enabled on the HTTP-RPC server endpoint, use --graphql) (default: 8545)
--light.gatewayfee value            Minimum value of gateway fee to serve a light client transaction (default: 0)
--disablerpcethcompatibility        If set, blocks returned from the RPC api will not contain the 'gasLimit' and 'baseFeePerGas' fields, which were added to the RPC block representation in order to improve compatibility with ethereum tooling. Note these fields do not currently exist on the internal block representation so they should be disregarded for the purposes of hashing or signing
=> Add eth compat flag to deprecated section

cmd/geth/main.go, cmd/geth/usage.go, cmd/utils/flags.go, contracts/gasprice_minimum/gasprice_minimum.go, contracts/gasprice_minimum/gasprice_minimum_test.go, eth/api_backend.go, eth/ethconfig/config.go, eth/ethconfig/gen_config.go, les/api_backend.go, test/node.go
This add command line option to adjust the
multiplier in the gas price suggestion RPC
endpoint.
Example:
```
geth --rpc.gaspricemultiplier 1.456
```
Resolves #2136
Further improvements are tracked in #2153
=> Add `--rpc.gaspricemultiplier` option

contracts/currency/currency.go, miner/block.go
This might help us debug
https://github.com/celo-org/celo-blockchain/issues/2134 if it happens again.
=> Improve error logging in toCeloFn

consensus/istanbul/backend/pos.go
Implementation of the CIP-56 (https://github.com/celo-org/celo-proposals/blob/master/CIPs/cip-0056.md)
Run tests
Part of the Gingerbread Hard Fork
=> [cip-56] Remove freezable check on epoch rewards

core/types/block_compatibility.go
Checking Difficulty breaks Rosetta since it seems that the Difficulty is 0x0 instead of nil.
Tests passed locally and fixed the block hash issue seen in Rosetta.
(Will wait until CI is green but if we run into issues will add back the `|| Difficulty == nil` condition)
=> Use UncleHash instead of Difficulty in EncodeRLP check

mycelo/genesis/genesis_state.go
Allow mycelo to have more than 100 validators. Keep it as max(100, numValidatorsFromEnv) which is useful for adding validators elected via test, for smaller testnets
=> Mycelo election's validators max, at least env validators

core/vm/contracts.go
Remove the CIP-25 as part of the CIP: https://github.com/celo-org/celo-proposals/discussions/392
Part of the Gingerbread P2 Hard Fork
=> Remove ed25519 precompile

params/config.go, params/version.go
Gingerbread Activation blocks:
Mainnet:
P1 & P2: `21616000` -> ~ 26/Sept/2023 17:15 UTC
Alfajores:
P1 & P2: `9814000` -> ~ 11/Sept/2023 17:30 UTC
Baklava:
P1: `18785000` -> 10/Aug/2023, 3:07:54 PM UTC
P2: `19157000` -> 01/Sept/2023, 2:08:22 PM UTC
=> Gingerbread Activation blocks

consensus/consensustest/mockprotocol.go, consensus/istanbul/announce/vc_gossiper.go, consensus/istanbul/backend/handler.go, consensus/istanbul/backend/handler_test.go, consensus/istanbul/backend/message_senders.go, consensus/istanbul/core/handler.go, consensus/istanbul/proxy/val_enodes_share.go, consensus/protocol.go, eth/protocols/eth/celo_peer.go, eth/protocols/eth/peer.go
Istanbul consensus is currently rlp encoding messages twice, and decoding them twice upon receiving one. The second encoding is done per peer, so if the same message is multicasted to 110 peers, it is encoded once, then 110 times more. This commit ensures the double encoding is done just once, reducing from 111 to 2 the calls to rlp.EncodeToBytes. A better way to handle this (but more disruptive) is completely drop the double encoding and double decoding, but would imply a protocol change.
* Also removed an expensive log line.
=> Remove per-peer rlp.Encode calls of istanbul messages

consensus/istanbul/core/roundstate_db.go, ethdb/leveldb/celo_leveldb.go, ethdb/leveldb/leveldb.go
Reuses the existing LevelDB implementation from the ethdb/leveldb module to collect LevelDB metrics for Roundstate DB as well and introduces additional metrics related to RLP-encoding.
- Changes default configuration for the Roundstate DB to reduce the amount of non-level0 compactions and improve performance, this change significantly reduces CPU usage and positively affects block construction times.
- Changes configuration settings of the state db to make compactions happen less often.
Tested on the testnet.
No breaking changes.
=> RSDB: metrics and performance improvements

core/state_processor.go, eth/api_backend.go, eth/celo_state_accessor.go, eth/state_accessor.go, eth/tracers/api.go, eth/tracers/api_test.go, les/api_backend.go
Fixes transaction tracing bug where the tracer did not include the block randomness for block whose transaction was being traced. For `(tx_i, block_n)`, it would fetch the state for `block_n-1` and then reexecute all txs up until `tx_i`, but would omit the random commitment at the very start of `block_n`.
This affects the following endpoints:
- `TraceTransaction`
- `TraceBlock*`
- `StandardTraceBlock*`
- `IntermediateRoots`
- `TraceChain`
Note:
- `TraceCall` performs correctly since this applies the tx _at the end_ of the requested block, so the block randomness of the next block is irrelevant.
- Initially attempted to limit scope of the changes to the API (`eth/tracers/api.go`) but this results in even more messiness because the `eth/state_accessor/stateAtTransaction` function needs to …
=> Fix tracing for transactions using on-chain randomness in latest block

light/txpool.go
Currently the light tx pool is missing the `pool.gingerbreadP2` property definition, causing light clients to incorrectly throw an error on receiving `0x7b` (`CeloDynamicFeeTxV2Type`) transactions.
Manually checked that this allows `CeloDynamicFeeTxV2Type` txs to be submitted afterwards.
Not a consensus-level change so shouldn't require a hardfork.
=> Fix gingerbreadP2 check for light tx pool

core/types/transaction.go, core/types/transaction_test.go, miner/block.go
https://github.com/celo-org/celo-blockchain/issues/2134 leads us to
believe that there are failures happening in production. This change
* Handles error cases by skipping processing of respective txs instead
of segfaulting
* Logs tx information in these cases to better understand why this is
happening
Skipping transactions where conversion is not possible is analogous to
handling other cases of bad transactions. But since the linked issue
only happens for some nodes, I am not sure if this is the right thing to
do or if we should intentionally panic in that case to avoid harder to
debug consensus failures due to having different nodes process a
different set of transactions.
I would not recommend merging this PR before Gingerbread unless we are very confident that we are doing the right …
=> Handle failing fee conversion

eth/protocols/eth/handler_test.go, eth/protocols/eth/handlers.go, rlp/celo_raw.go, rlp/celo_raw_test.go
Avoid decoding and re-encoding of the block body by using available RLP-encoded block body from the database, combine it with the RLP-encoded block hash to avoid unnecessary processing and extra memory allocations.
Benchmarks:
```
Original Ethereum version (highly efficient as block body is taken either from the cache or database directly).
BenchmarkAnswerGetBlockBodiesQuery/GetBlockBodies-1-8         	14819121	        92.65 ns/op	      24 B/op	       1 allocs/op
BenchmarkAnswerGetBlockBodiesQuery/GetBlockBodies-10-8        	 1318404	       896.9 ns/op	     744 B/op	       5 allocs/op
BenchmarkAnswerGetBlockBodiesQuery/GetBlockBodies-100-8       	  153598	      7907 ns/op	    6120 B/op	       8 allocs/op
Current Celo-version
BenchmarkAnswerGetBlockBodiesQuery/GetBlockBodies-1-8 …
```
=> Improve performance of answerGetBlockBodiesQuery

.github/workflows/blockchain.yml
Follow-up for https://github.com/celo-org/celo-blockchain/pull/2189, upgrade CI as well.
=> Upgrade CI to go 1.19

.github/workflows/blockchain.yml, core/blockchain.go
Add chain_head_gasprice gauge metric. This metric represents the baseFee (gasPriceMinimum) for last block.
Pinned Node version to 18.18. Node 18.19 breaks the tests ([changelog](https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V18.md#2023-11-29-version-18190-hydrogen-lts-targos))
=> Add chain_head_gasprice gauge metric. Fix e2e tests

.github/workflows/pages.yaml
In https://github.com/celo-org/celo-blockchain/actions/runs/7260906287/job/19781026224 the forkdiff job fails because of an old go version. This upgrade to version to fix the build.
=> CI: Fix forkdiff build

Dockerfile
As pointed by @carterqw2 (🙏 ), [celo-bls-go is not compatible with musl for amd64](https://github.com/celo-org/celo-bls-go/blob/master/bls/bls_linux.go#L1).
This PR aims to use glibc for amd64 image, and musl for arm64 images.
=> Using glibc for amd64 and muslc for arm64

contracts/currency/currency.go, core/tx_list.go, core/tx_multicurrency_priceheap.go, core/tx_multicurrency_priceheap_test.go
Previous underprice implementation would provoke different currency comparisons, erroneously calculate the underprice flag, and ignore basefee in underprice comparisons.
=> Fix underpriced check for multi currency

internal/ethapi/api.go, params/config.go, params/gas_limts.go
Ensures that for mainnet, alfajores and baklava, nodes will return the correct block gas limit up to the gingerbread fork even if they are not archive nodes when running in eth compatibility mode (I.E. `--disablerpcethcompatibility` is not set).
A small re-factor of GetBlockByNumber and GetBlockByHash to reduce the depth of nesting.
This change is not backwards compatible with the previous implementations on mainnet, alfajores or baklava which would have returned a zero gas limit for a block if there was no state for that block.
=> Hardcode pre gingerbread block gas limits for existing chains

eth/filters/api.go, eth/filters/filter_system.go, eth/filters/filter_system_test.go, ethclient/gethclient/gethclient.go, ethclient/gethclient/gethclient_test.go
Porting https://github.com/ethereum/go-ethereum/pull/25186/files to Celo.
There were some trivial merge conflicts in `eth/filters/api.go` that needed to be resolved before this could apply.
Would like this to be merged in and deployed to Forno so that websocket streams from the pub RPC TX pool includes the body, otherwise, there's just extra load doing round trip to fetch via pending tx header.
=> eth/filter, ethclient/gethclient: added fullTx-flag to NewPendingTransactions

core/types/celo_additions.go, e2e_test/e2e_bench_test.go, e2e_test/e2e_test.go, e2e_test/e2e_transfer_test.go, eth/api_backend.go, les/api_backend.go, mycelo/genesis/genesis.go
This PR fixes the way the the gasLimit and gasPriceMinimum are retrieved from state such that for all non genesis blocks the value returned is the value present in the state of the parent block, and for the genesis block the value returned is the value present in the state of the genesis block (because the genesis has no parent). Prior to this fix requesting the gasLimit or gasPrice minimum for the genesis block would result in an error because we would try to get the state for the genesis block's parent which of course did not exist.
It also removes a restriction in the mycelo genesis package (used by e2e tests) that prevented us from setting the gingerbread activation block to zero. This restriction was in place because originally it was not possible to set the …
=> Fix genesis block gingerbread fields

internal/ethapi/api.go, params/config.go, params/gas_limts.go
Note that this duplicates #2216 because we force reverted master after #2216 was merged.
Ensures that for mainnet, alfajores and baklava, nodes will return the correct block gas limit up to the gingerbread fork even if they are not archive nodes when running in eth compatibility mode (I.E. `--disablerpcethcompatibility` is not set). More detail can be found here:
* #2214
A small re-factor of GetBlockByNumber and GetBlockByHash to reduce the depth of nesting.
CI is passing
This change is not backwards compatible with the previous implementations on mainnet, alfajores or baklava which would have returned a zero gas limit for a block if there was no state for that block.
=> Hardcode pre gingerbread block gas limits for existing chains #2

.github/renovate.json
Those updates take a lot of time of time to merge and provide little actual benefit. So lets disable non-security updates.
=> renovate: ignore non-security npm updates

eth/tracers/api.go, eth/tracers/api_test.go
This PR modifies the interface for the results of `debug_traceBlock` and `debug_traceCall` by adding the `txHash`, allowing users to identify which transaction's trace result corresponds to.
Cherry picked https://github.com/ethereum/go-ethereum/pull/27183 to make block tracing work (see details [here](https://github.com/celo-org/blockscout/pull/1016)).
No.
Updated unit test.
- Related to https://github.com/celo-org/blockscout/pull/1016
=> eth/tracers: add `txHash` field on txTraceResult

accounts/abi/bind/backends/simulated.go, eth/filters/api.go, eth/filters/filter.go, eth/filters/filter_system.go, eth/filters/filter_system_test.go, internal/ethapi/api.go
Porting https://github.com/ethereum/go-ethereum/pull/26126 to Celo so that the pending subscription TX has consistent JSON.
This was fixed upstream by always using the `ethapi.NewRPCPendingTransaction` function
=> eh/filters: send rpctransactions in pending-subscription

internal/ethapi/api.go
Properly create `sysCtx` on Espresso Hardfork.
Locally.
=> Properly create SysCtx in AccessList RPC

.github/workflows/build-sign-release-images.yaml
The release build wasn't triggered for the latest RC: https://github.com/celo-org/celo-blockchain/releases/tag/v1.8.1-rc.1
Not also matches tags including `beta` or `rc` suffixes.
=> ci: Fix release tag regex

graphql/graphql.go, internal/ethapi/api.go
Through an oversight `debit`/`credit` were skipped for all calls, not just calls from gas estimation. This commit fixes that.
=> fix: Only skip debit/credit on gas estimation

core/tx_pool_test.go
Without the use of sync calls there is no guarantee that txpoool reorg will run between adding txs and chekcking some condition, this causes tests to fail randomly.
This PR ensures the use of sync calls.
To verify my suspicion that the lack of reorg running was the cause of the error I was seeing in `TestTransactionPoolUnderpricing` i used the following patch to reliably recreate the error.
```diff
diff --git a/core/tx_pool.go b/core/tx_pool.go
index 9a3003d6f..0a35c8a76 100644
--- a/core/tx_pool.go
+++ b/core/tx_pool.go
@@ -263,6 +263,8 @@ type txPoolContext struct {
// current state) and future transactions. Transactions move between those
// two states over time as they are received and processed.
type TxPool struct {
+	reorgSkip   int32
+	skipLock    sync.Mutex
config …
```
=> Use sync calls to add txs to pool in tests

params/config.go
This fixes a typo in the hardcoded historical gas limits
Relates to #2229 #2214
=> Correct hardcoded gas limit for mainnet

contracts/erc20gas/erc20gas.go
This is now done by the `SkipDebitCredit` flag.
Resolves #2267
=> Remove special handling for gas estimation

contracts/erc20gas/erc20gas.go, contracts/testutil/fail_runner.go, contracts/testutil/runner.go, core/tx_pool.go, core/tx_pool_test.go, core/vm/interface.go, core/vm/vmcontext/runner.go
Txs must not fail during `debitGasFees` execution during the state transition, so we must remove problematic txs during the tx pool validation. We do this by executing `debitGasFees` inside the tx pool validation and discarding the resulting state changes. This is not overly efficient, but still better than the alternatives that have been considered so far.
* Added `ExecuteAndDiscardChanges` to `vm.EVMRunner`. I would have liked to avoid this change, but `StaticCall` does not allow (even temporary) changes and I didn't see a better way.
* extracted `debitGasFeesSelector` and `creditGasFeesSelector` and updated comment to show how to generate the selector with `cast` instead of python.
* removed old check for sufficient ERC20 balance, since that is implicitly checked by executing …
=> Validate debitGasFees execution in tx pool

.golangci.yml, common/types.go, contracts/abis/abi_str.go, contracts/abis/parsed_abi.go, contracts/currency/currency.go, contracts/testutil/blockchain_parameters.go, contracts/testutil/celo.go, contracts/testutil/contract_mocks.go, core/tx_list.go, core/tx_pool_test.go
This PR adds tests for replacing celo transactions in the txpool.
Adding this required extending the mocked contracts. It also found two issues:
1. A comparison of fee currencies only checked the pointers, not the underlying addresses.
2. There is the problem of rounding errors happening when calculating the required replacement fee values. For example if a 10% increase is required and a fee of 2 wei is offered by the old transaction, the calculation also rounded the new required fee down to 2 (2 * 110 / 100). I solved this by removing the division by 100. This might cause overflow, but I believe that this won't cause problems in reality as the fee amounts will never be this high. But please have a special look at this during the review.
=> Test celo transaction replacement

p2p/peer.go
Moving the response sending there allows tracking all peer goroutines in the peer WaitGroup.
=> p2p: move ping handling into pingLoop goroutine

.github/workflows/add-docker-tag.yaml
=> MV regctl to /usr/local/sbin

core/types/celo_denominated_tx.go
Fixes two issues with the current cip66 implementation, firstly `FeeCurrency` was in the wrong position in the struct and secondly the `copy` method was not copying `MaxFeeInFeeCurrency`
Manually: Serialized a transaction and inspected it with rlpdump
```
0x7af8ce82a4ec01843b9aca00850342770c0083030d409443d72ff17701b2da814620735c39c620ce0ea4a180b844a9059cbb000000000000000000000000bd8be21f6883569ad7d15cc55c87137fcef308c300000000000000000000000000000000000000000000000001605eba271024d6c094765de816845861e75a25fca122bb6898b8b1282a8501a13b860080a02a015905a494549d8a1da26ce769309963e43f407936bbce1ea8276072b08416a072fd12d24c44bc79648bd88f4d8c158f2f0778694557868b3dc7d80e3aa6b539
```
=> cip66 fixes

cmd/devp2p/nodesetcmd.go, docs/docs/_developers/dns-discovery-setup.md, eth/handler.go, signer/core/signed_data.go
=> chore: remove repetitive words

consensus/istanbul/core/handler.go, e2e_test/e2e_test.go, ethclient/ethclient.go, test/account.go, test/node.go
Adds a test to verify that the tx pool is executing concurrent fee currency checks safely.
I created this to see if I could reproduce https://github.com/celo-org/celo-blockchain/issues/2318 but I was unable to reproduce that issue. It did however uncover a different race condition, which was that `core.current` was being set in one goroutine and accessed from others without synchronisation. This was easy to fix by just locking around the point where it is set.
=> Test concurrent feecurrency tx handling in tx pool

params/config.go
Adds the L2 migration config for Alfajores and Baklava testnets.
=> config: Add L2 migration config for testnets

params/config.go
We need to reschedule the Baklava L2 migration. Until that, we have to remove the activation block from the client
=> Remove Baklava L2 migration config

.github/workflows/build-sign-release-images.yaml, params/config.go
Adds the Baklava migration block.
Resolves https://github.com/celo-org/celo-blockchain-planning/issues/884
=> Add Baklava migration block

rpc/errors.go, rpc/handler.go, rpc/server_test.go
This PR adds limitations of number of batch items and response size in JSON-RPC request for avoiding an excessive memory usage.
After this change, a batch request can contain up to a maximum of 1000 requests, and the total size of all result data is limited to 25 MB.
The hardcoded boundary values are based on the default values in the current implementation of go-ethereum.
I added unit tests for each change
=> Add batch request limit and response size limit in a RPC batch request

params/config.go
See https://forum.celo.org/t/returning-home-to-ethereum-the-launch-of-celo-l2-mainnet/10466
Part of https://github.com/celo-org/celo-blockchain-planning/issues/903
=> Add Mainnet L2 migration block
