celo-org/celo-blockchain

- .circleci/config.yml
Access git+https to access the celo-monorepo
This will be tested on CircleCI
> Circle CI cleanup

- contract_comm/currency/currency.go
> Fix comment date

- .circleci/config.yml
Don't wait for bls-zexe to checkout celo-monorepo or geth linting
Partially addresses  https://github.com/celo-org/celo-monorepo/issues/616
> Don't wait for bls-zexe to checkout celo-monorepo or geth linting

- README.md
Updates the README.
N/A
N/A
N/A
N/A
> Update README with info about CI tests and automerge

- consensus/istanbul/backend/engine.go
- params/protocol_params.go
Companion to https://github.com/celo-org/celo-monorepo/pull/653
On a testnet
NOT backwards compatible
> Change ref BondedDeposits->LockedGold

- .circleci/config.yml
Points end-to-end tests back to the master branch after merging https://github.com/celo-org/celo-monorepo/pull/853
End to end tests
None
> Point end-to-end tests back to the master branch

- .circleci/config.yml
- contract_comm/evm.go
- core/vm/dynamic_params.go
- params/protocol_params.go
Hashes registry ID before making EVM call to `Registry.getAddressFor`.
No tests added.
- Sister PR of https://github.com/celo-org/celo-monorepo/pull/657
> Hash registry id

- .circleci/config.yml
Repointing the CirleCI config back to master after merging #418.
> Repoint CI to master

- .circleci/config.yml
Repointing e2e tests on circle after #374 got merged.
> Repoint Circle to master

- .circleci/config.yml
- Dockerfile.alltools
- cmd/bootnode/main.go
- cmd/geth/main.go
- cmd/geth/usage.go
- cmd/utils/flags.go
- consensus/istanbul/backend/announce.go
- consensus/istanbul/backend/engine.go
- consensus/istanbul/config.go
- consensus/istanbul/core/core.go
- consensus/istanbul/core/handler.go
- consensus/istanbul/core/testbackend_test.go
- consensus/istanbul/core/types_test.go
- consensus/istanbul/errors.go
- consensus/istanbul/types.go
- contract_comm/evm.go
- contract_comm/random/random.go
- core/state_transition.go
- core/tx_list.go
- core/vm/contracts.go
- core/vm/contracts_test.go
- core/vm/errors.go
- core/vm/evm.go
- node/config.go
- p2p/discv5/udp.go
- p2p/server.go
- params/bootnodes.go
> merge master

- contract_comm/gasprice_minimum/gasprice_minimum.go
Should fix ignored error in GetGasPriceMinimum
Didn't notice other places where errors would be ignored.
- Fixes #505
> Handling errors in gas_price_minimum package

- .circleci/config.yml
> Point CI to master

- consensus/istanbul/backend/backend.go
- consensus/istanbul/backend/engine.go
- contract_comm/election/election.go
- contract_comm/validators/validators.go
- params/protocol_params.go
This PR updates celo-blockchain to reflect the changes in https://github.com/celo-org/celo-monorepo/pull/1177.
End to end tests.
Move some parameters to protocol_params.go
No
> Implement proof-of-stake changes

- cloudbuild.yaml
Build docker images and tag them with the branch
- Relates to https://github.com/celo-org/celo-monorepo/issues/1427
> Build docker images and tag them with the branch

- core/vm/contracts.go
Fixes a wee little bug in https://github.com/celo-org/celo-blockchain/pull/545
End-to-end tests
> Fix "Fix precompiles"

- cloudbuild.yaml
My previous PR did not allow for images build on branches with slashes in them
> Support slashes in branch names for docker builds

- cloudbuild.yaml
In my quest for https://github.com/celo-org/celo-blockchain/pull/552, I accidentally removed tagging with the commit
> Readd commit sha

- cloudbuild-branchname.yaml
- cloudbuild.yaml
Hopefully this is the last PR in this saga, but I decided to just create a separate cloudbuild file that we can manually set the trigger for, for compliant branch names
> Add separate cloudbuild config for branch name

- .circleci/config.yml
Point CI back to master after #560
> Point CI back to master

- Dockerfile.celo-node
Realized I forgot to update the geth commit on GitHub to reflect what's pushed to GCR
n/a
n/a
n/a
n/a
> Update celo-node dockerfile to reflect what's on GCR

- .circleci/config.yml
- consensus/istanbul/backend.go
- consensus/istanbul/backend/backend.go
- consensus/istanbul/core/backlog_test.go
- consensus/istanbul/core/core.go
- consensus/istanbul/core/request_test.go
- consensus/istanbul/core/roundstate.go
- consensus/istanbul/core/testbackend_test.go
- consensus/istanbul/core/testutils_test.go
Make it private where it was actually used.
test
> Remove unused code HasBadProposal

- consensus/istanbul/core/message_set.go
Removes unncessary code
unit tests
> Cleanup MessageSet

- CeloBlockchain.podspec
- package.json
This is required to build the final app using the podspec.
Tested the wallet compiles with it.
N/A
Yes
> Fix iOS podspec to include bls snark lib

- eth/handler.go
PR into master for this Baklava PR:  https://github.com/celo-org/celo-blockchain/pull/694
See https://github.com/celo-org/celo-blockchain/pull/694
None
- Fixes https://github.com/celo-org/celo-blockchain/issues/691
> Proxy SNBAT disconnect proxied validator from a max peers limit

- consensus/istanbul/backend/pos.go
This PR fixes a bug in which gold should have been sent to the reserve to collateralize the dollars rewarded to validators.
Updated the end-to-end tests in the monorepo to check the reserve balance.
https://github.com/celo-org/celo-monorepo/pull/2103
Return an error if we can't fetch the locked gold address
- Fixes #https://github.com/celo-org/celo-blockchain/issues/701
Not backwards compatible
> Send gold to the reserve when rewarding validators with celo dollars

- consensus/istanbul/backend/pos.go
- consensus/istanbul/core/core.go
- consensus/istanbul/core/handler.go
- consensus/istanbul/core/prepare.go
- consensus/istanbul/core/roundchange.go
This PR improves logging for IBFT, adding missing information and adjusting verbosity.
Not tested
None
> Improve IBFT logging

- mobile/geth.go
Patch crashes on mobile from rounded state db write access denial
Synced on mobile
Yes
> Patch crashes on mobile from rounded state db

- cmd/utils/flags.go
- consensus/istanbul/backend/engine.go
- consensus/istanbul/backend/handler.go
- consensus/istanbul/core/core.go
- consensus/istanbul/core/roundchange.go
- consensus/istanbul/errors.go
- eth/handler.go
- p2p/enode/urlv4.go
- p2p/enode/urlv4_test.go
This PR checks that proxied validators do not gossip internal IP addresses.
New unit tests, and by various command line tests. 
- Improve readability of IBFT logs
> Check that announced IP address is not an internal IP

- .github/ISSUE_TEMPLATE.md
- README.md
- cmd/geth/bugcmd.go
- cmd/geth/misccmd.go
Made some changes to help us deal with reported issues in the future.
* Asks for reproduction steps, logs, & system info when creating issues
* Updates `geth bug` command to open an issue with the correct system info
* Updates `geth version` to have more system information
Ran `geth version`, `geth bug`
n/a
n/a
> Make issue reporting better

- cmd/geth/main.go
- cmd/geth/usage.go
- cmd/utils/flags.go
- consensus/istanbul/backend/announce.go
- consensus/istanbul/backend/backend.go
- consensus/istanbul/backend/internal/enodes/val_enode_db.go
- consensus/istanbul/backend/internal/enodes/val_enode_db_test.go
- consensus/istanbul/backend/val_enodes_share.go
- consensus/istanbul/backend/val_enodes_share_test.go
Reverts celo-org/celo-blockchain#749
> Revert "validators SBAT handle clock drift for announce messages"

- consensus/istanbul/core/roundstate_db.go
Add log messages on UpdateLastRoundState() errors
CI
> Add log messages on UpdateLastRoundState() errors

- consensus/istanbul/core/core.go
Add log messages on commit() errors
CI
> Add log messages on commit() errors

- consensus/istanbul/backend/api.go
- consensus/istanbul/core/core.go
- consensus/istanbul/core/handler.go
- consensus/istanbul/core/types.go
Add RPC to force round timeout
CI
> Add RPC to force round timeout

- .circleci/config.yml
Changed the circleci monorepo branch back to master
> changed circleci celo-monorepo branch back to master

- ethstats/ethstats.go
This was a gnarly one.
**Problem**.
I have a testnet with 3 validators, validator0 is proxied. Due to 1 second block times, when validator0 is just behind, it wouldn't be able to participate in consensus unless it imports blocks that brings it back to the most recent sequence. Eventually however, it would stall and be stuck at a block. Sometimes it would recover only to stop again.
**Investigation**:
I first tried to figure out why I would no longer import blocks. Turns out that I eventually hit [this line](https://github.com/celo-org/celo-blockchain/blob/master/eth/fetcher/fetcher.go#L599) that prevents DOS from our peers.
It turns out that something prevented the completion of an insert which let the queue accumulate. After a lot of log lines, it turns out that sending …
> Prevent ethstats from blocking ChainHead publishing

- .circleci/config.yml
As title. Can occur b/c the sister PR is merged.
n/a
nope
> Points CI back to monorepo master

- core/chain_indexer_test.go
Is basically https://github.com/ethereum/go-ethereum/pull/20506/files
> Fix chain indexer unit test

- .golangci.yml
- accounts/usbwallet/ledger.go
- cmd/geth/retesteth.go
- consensus/istanbul/backend/backend.go
- consensus/istanbul/core/roundchange.go
- consensus/istanbul/validator/default_test.go
- core/rawdb/database.go
- core/tx_pool.go
- crypto/bn256/cloudflare/optate.go
Add staticcheck linter and fix the issues.
CI
- Relates to #848 
Yes
> Add staticcheck linter

- core/blockchain.go
- core/blockchain_test.go
> Revert "Higher trie limit (#845)" on master

- core/types/gen_header_json.go
- core/types/gen_tx_json.go
- core/types/transaction.go
Fixes tx serialization.
Not tested.
None
None
Yes
> Fix transaction serialization

- consensus/istanbul/backend/pos.go
- contract_comm/epoch_rewards/epoch_rewards.go
Fixing bad merge.
Checked manually that error messages caused by this went away.
> Fixing checking if epoch rewards are frozen

- accounts/abi/bind/base.go
- accounts/abi/bind/template.go
- go.sum
New methods to parse event Logs, and expose the ABI object
In use in rosetta
> Add methods to BoundContract & abigen wrappers

- .circleci/config.yml
_A few sentences describing the overall effects and goals of the pull request's commits.
What is the current behavior, and what is the updated/expected behavior with this PR?_
_Brief explanation of why these changes are/are not backwards compatible. Feel free to remove for trivial, backwards compatible changes._
> Restore master as circle-ci branch

- .github/CODEOWNERS
- .github/CONTRIBUTING.md
Clarify code owners and PR review policy to reduce the barrier to entry for contributions.
> Small changes to codeowners and contribution policy

- .circleci/config.yml
- cmd/utils/flags.go
- eth/backend.go
- params/config.go
Read block period and request timeout from genesis file. Still probably have to be able to override from cmd line, that isn't implemented yet.
> Read block period from genesis file

- accounts/hd.go
- accounts/scwallet/README.md
- signer/core/uiapi.go
Documentations fixes
- Fixes #896
> Minor changes in comments for celo Derivation Path

- core/vm/evm.go
Print error messages from solidity when contract_comm errors.
Only manual testing.
Yes.
> Contract comm errors

- CeloBlockchain.podspec
- mobile/geth.go
- package.json
- scripts/publish-mobile-client.sh
_A few sentences describing the overall effects and goals of the pull request's commits.
What is the current behavior, and what is the updated/expected behavior with this PR?_
> Allow zero max peers in config for no sync signing mode in wallet

- consensus/istanbul/backend/backend.go
- consensus/istanbul/backend/handler.go
Added two new gauge metrics for tracking the number of transactions in the last block, and the gas used in the last block.
> Adds new metrics for transactions and gas used

- .circleci/config.yml
- scripts/sync_test.sh
Adds a sync test to mainnet in the lightest mode to the circleci config
> Lightest sync test

- miner/worker.go
This reverts commit 968d089f639cabecc072568186c6e33a29545078.
> Revert "Add metrics: blockFinalizationTime (#1150)"

- consensus/istanbul/backend/announce.go
- consensus/istanbul/backend/api.go
- consensus/istanbul/backend/backend.go
- consensus/istanbul/backend/engine.go
- consensus/istanbul/backend/handler.go
- consensus/istanbul/backend/handler_test.go
- consensus/istanbul/backend/message_senders.go
- consensus/istanbul/proxy/proxy_engine.go
- consensus/istanbul/proxy/proxy_set.go
- consensus/istanbul/proxy/types.go
- consensus/istanbul/proxy/val_enodes_share.go
Here is a PR of minor suggestions for the Multiproxy PR. Feel free to push to this branch to change any of it and take what you want to merge.
> [Review comments] Review suggestions for Multiproxy PR

- params/version.go
_A few sentences describing the overall effects and goals of the pull request's commits.
What is the current behavior, and what is the updated/expected behavior with this PR?_
> Release 1.1.1

- params/version.go
Includes two changes cherry-picked from master:
1. Fix for the LES server panic
2. Churrito and Donut configs, Churrito activation block number for Baklava.
> Release 1.1.2

- consensus/istanbul/backend/internal/replica/state.go
Log message should be a Trace, not a Warn.
> Reduce logging level

- core/blockchain.go
_A few sentences describing the overall effects and goals of the pull request's commits.
What is the current behavior, and what is the updated/expected behavior with this PR?_
Not yet
> Stop proxies from trying to generate randomness

- core/blockchain.go
- params/version.go
Fixes crashes on proxies due to a randomness beacon cache change.
> 1.2.2-beta.1

- .circleci/config.yml
- Makefile
- README.md
- patches/mobileLibsForBuild.patch
Adds a patch that will be applied for the mobile building, adding the required libs to build successfully the client
Manually
> Add patch for mobile libs

- README.md
Update Readme with rename tooling usage.
> Update Readme with rename tooling

- cmd/mycelo/genesis_commands.go
- cmd/mycelo/main.go
- mycelo/cluster/cluster.go
- mycelo/cluster/node.go
1. Fixes help flag nil pointer panic
2. Internal code cleanup
3. Adds pass through flags to geth. This can be used to activate profiling the validator.
> Adds passthrough flag to mycelo

- consensus/istanbul/backend/api.go
- internal/web3ext/web3ext.go
Now we are able to obtain the current or a block's lookback window from
the node's perspective.
Fixes web3ext mappings, to properly parse block numbers
> Adds istanbul.getLookbackWindow rpc

- consensus/istanbul/core/commit.go
- consensus/istanbul/core/commit_test.go
One case has not been tested, fixed it.
> Fix unit tests

- contract_comm/currency/currency.go
- contract_comm/errors/errors.go
- core/tx_list.go
- core/tx_pool.go
- core/types/transaction.go
Cherry-pick to master the security fixes from v1.2.3 and v1.2.4.
* The changes themselves have already been tested and deployed in v1.2.4.
* Verified that this diff is like the diff between 1.2.2 and 1.2.4 except for line number differences and the versions.
No incompatibility.
> Cherry pick tx pool fixes from v1.2.3 and v1.2.4

- cmd/mycelo/README.md
Updates mycelo's README to change a part that's out of date.  I noticed this while preparing the v1.3.0-beta release notes.
No testing needed as this is just a documentation change.
> Update mycelo README

- cmd/geth/main.go
- cmd/geth/usage.go
- cmd/utils/flags.go
- contract_comm/currency/currency.go
- contract_comm/evm.go
- core/state/database.go
- core/state/statedb.go
- core/vm/dynamic_params.go
- core/vm/evm.go
- core/vm/interface.go
- core/vm/interpreter.go
- eth/backend.go
- eth/config.go
- light/trie.go
- trie/secure_trie.go
- trie/trie.go
Reverts celo-org/celo-blockchain#1477
We are using https://github.com/celo-org/celo-blockchain/pull/1467 for now
> Revert "Caches currency.Cmp"

- contract_comm/currency/currency.go
- contract_comm/currency/currency_test.go
- miner/worker.go
Adds a CurrencyComparator that caches exchange rates.
> Cache exchange rates when creating a block 

- consensus/istanbul/core/core.go
- consensus/istanbul/core/final_committed.go
> Cherry-pick Split out startNewSequence from core.startNewRound (#1470)

- core/tx_pool.go
Added a gauge metric for gasPriceMinimum at path `txpool/gaspriceminimum`
Used in development testnets
> GasPriceMinimum value metric

- cmd/geth/config.go
- ethstats/ethstats.go
Cherry pick PR #1508 to the 1.3.x release branch, for inclusion in v1.3.0-stable.  For more details, see that PR.
> Cherry-pick to 1.3.x branch: Only active validator signs stats (#1508)

- build/ci.go
Codecov upload was broken. This PR fixes that
> Reenable code coverage upload to codecov

- params/version.go
Promoted v1.4.0-beta to v1.4.0.
> Release v1.4.0

- eth/api_backend.go
- params/version.go
Cherry pick #1769 to `release/1.5.x`
> Cherry pick #1769 to release/1.5.x

- consensus/consensustest/mockprotocol.go
- consensus/istanbul/backend/engine.go
- miner/worker.go
Cherry pick #1798 to `release/1.5.x`
> Cherry pick #1798 to 1.5.x

- consensus/consensustest/mockprotocol.go
- consensus/istanbul/backend/engine.go
- miner/worker.go
Cherry pick #1798 to `release/1.4.x`
> Cherry pick #1798 to 1.4.x

- core/types/transaction.go
Cherry pick #1801 to `release/1.5.x`
> Cherry pick #1801 to 1.5.x

- contracts/abis/abi_str.go
- contracts/gasprice_minimum/gasprice_minimum.go
- core/error.go
- core/tx_list.go
- core/tx_pool.go
- core/tx_pool_test.go
Cherry pick #1749 to `release/1.4.x`
> Cherry pick #1749 to 1.4.x

- core/tx_list.go
- core/tx_pool.go
- core/tx_pool_test.go
Cherry pick #1800 to `release/1.5.x`
> Cherry pick #1800 to 1.5.x

- core/tx_list.go
- core/tx_pool.go
Cherry pick #1816 to `release/1.5.x`
> Cherry pick #1816 to 1.5.x

- core/tx_list.go
Cherry pick #1817 to `release/1.5.x`
> Cherry pick #1817 to 1.5.x

- eth/api.go
- eth/api_backend.go
- internal/ethapi/api.go
Cherry pick #1818 to `release/1.5.x`
> Cherry pick #1818 to 1.5.x

- internal/ethapi/api.go
If the state is not available to calculate the effectiveGasPrice then
don't return the field.
> Return no effectiveGasPrice instead of 0

- internal/ethapi/api.go
Cherry pick #1825 to `release/1.5.x`
> Cherry pick #1825 to 1.5.x

- params/version.go
Update version to 1.4.2-stable
> Release v1.4.2

- params/version.go
Update version to 1.5.1-stable
> Release v1.5.1

- params/version.go
Update version to 1.5.3-stable
> Release v1.5.3

- .circleci/config.yml
- consensus/istanbul/announce/manager.go
- consensus/istanbul/announce/network.go
- consensus/istanbul/announce/util.go
- consensus/istanbul/backend/announce_test.go
- consensus/istanbul/types.go
> Minor modifications to the announce protocol code

- e2e_test/e2e_test.go
Rename rounds to iterations and reduce iterations (changes runtime from 5s to <1s).
> Small adjustments to test

- cmd/geth/main.go
- cmd/geth/usage.go
- cmd/utils/flags.go
- eth/api_backend.go
- eth/backend.go
- eth/ethconfig/config.go
- eth/ethconfig/gen_config.go
- eth/tracers/api_test.go
- graphql/graphql_test.go
- internal/ethapi/api.go
- internal/ethapi/backend.go
- les/api_backend.go
- params/version.go
Cherry pick #1865 to release/1.5.x
> Cherry pick #1865 to 1.5.x

- .circleci/config.yml
Cherry picking 3 commits from our master to `release/v1.5.x` to allow CI to pass on that branch.
> Piersy/fix ci for 1.5.x release branch

- ethclient/gethclient/gethclient_test.go
Comment flaky test. Was restored before, but the flakiness remains
> Comment flaky test (testAccessList)

- internal/ethapi/api.go
- internal/ethapi/api_test.go
Fix pending block txs serialization
Yes
> Fix ethapi for pending blocks

- consensus/istanbul/celo-ibft-spec.md
Just some minor spelling fixes.
> docs: Fix some misspelling in IBFT docs

- .circleci/config.yml
- cmd/mycelo/genesis_commands.go
- core/vm/operations_acl.go
- internal/ethapi/api.go
- monorepo_commit
- mycelo/genesis/genesis.go
- params/protocol_params.go
Add flags for hardfork configuration on mycelo
Also, restore cip35/50 test that was flagged as flaky (but is not)
> mycelo hardforks config

- consensus/istanbul/core/commit_v2_test.go
- consensus/istanbul/core/prepare_v2_test.go
This allows for easy removal of v1 tests and easy comparison of v1 and v2 tests via diffing.
The following command can be used to aid in locally reviewing these changes:
```
for x in commit prepare preprepare roundchange; do git diff --no-index consensus/istanbul/core/${x}_test.go  consensus/istanbul/core/${x}_v2_test.go; done
```
> Move v2 tests to own file

- cmd/utils/flags.go
- eth/backend.go
- eth/downloader/modes.go
- eth/peerset.go
- les/downloader/modes.go
Enable Snap Sync
Unit tests, and local cluster of nodes
- Fixes #1735 
Yes
> Enable Snap Sync

- params/config.go
Picked from the already release 1.7.0
- Mainnet: November 8th, 16:30 - 17:30 UTC
> Consensus V2 validator fork activation dates

- .circleci/config.yml
We have some forked PRs that are not building in CI because the checkout is not working, this PR is an attempt to solve that. 
We'll need to merge this to master to see if it really works but as long as this PR is building in CI then this change shouldn't break our normal PR flow.
Yes, its just a CI change.
> Update circleci checkout to support forked PRs

- scripts/sync_test.sh
> ci: Fix typo in sync test script

- consensus/istanbul/backend/handler.go
- consensus/istanbul/protocol.go
Updates some outdated comments I found while checking the celo protocol code.
> chore: Update some dated comments

- .github/workflows/config.yml
Using larger runners 4 cores
should be backwards compatible
> upgrading to larger runners 4 cores

- cmd/evm/internal/t8ntool/transition.go
- common/fdlimit/fdlimit_test.go
- core/vm/contracts_test.go
- internal/build/util.go
- trie/proof.go
- trie/stacktrie.go
Fix warnings reported in https://github.com/celo-org/celo-blockchain/actions/runs/4701151690
> lint: Fix linter warnings

- cmd/mycelo/genesis_commands.go
- core/state_processor_test.go
- core/vm/interpreter.go
- core/vm/jump_table.go
- core/vm/runtime/runtime.go
- mycelo/genesis/config.go
- params/config.go
- tests/init.go
Add the basic infrastructure for the G* hardfork.
> Add G-Fork infrastructure

- core/vm/celo_contracts_test.go
> Fix getValidators precompile test

- eth/tracers/api_test.go
> Fix tracer's precompile flaky test

- core/vm/celo_contracts.go
- core/vm/contracts.go
- core/vm/contracts_test.go
Fix a small oversight in #2103
> Simplify interface of proofOfPossession precompile

- consensus/istanbul/backend/backend.go
- consensus/istanbul/backend/engine.go
- consensus/istanbul/backend/test_utils.go
- consensus/misc/eip1559.go
- consensus/misc/gasLimit.go
- core/chain_makers.go
- core/state_processor.go
- core/state_processor_test.go
- miner/block.go
Verify that the actual baseFee of a proposal is correct
Run e2e tests
Part of the Gingerbread fork
> Verify baseFee and gasLimit of proposal

- core/blockchain_test.go
- eth/tracers/api_test.go
> tests: Remove unused storage maps

- cmd/geth/config.go
- cmd/geth/main.go
- cmd/mycelo/genesis_commands.go
- cmd/utils/flags.go
- core/genesis.go
- core/state_processor_test.go
- core/vm/interpreter.go
- core/vm/runtime/runtime.go
- eth/backend.go
- eth/ethconfig/config.go
- eth/ethconfig/gen_config.go
- les/client.go
- miner/stress/1559/main.go
- mycelo/genesis/config.go
- mycelo/genesis/genesis.go
- params/config.go
- tests/init.go
Flags and block activation for the second part of the gingerbread hard fork
> Gingerbread P2

- .github/workflows/build-sign-binaries.yaml
- .github/workflows/build-sign-commit-images.yaml
- .github/workflows/build-sign-release-images.yaml
need to add trivy scanning to the workflows for containers
Fully backwards compatible
> adding trivy scanning to the existing container build workflows

- README.md
Tried to build with go1.16 but it didn't work
> Update minimal required version on readme README.md

- .github/workflows/build-sign-binaries.yaml
Update xgo builder reference to match during building process.
> Update xgo builder reference

- e2e_test/e2e_transfer_test.go
Adds an E2E test for transaction with fee currency usage.
> Test fee currency event emission

- .github/workflows/build-sign-commit-images.yaml
Update the github action variables to fix building process
> Update github action var reference

- .dockerignore
- .gitignore
Updating the ignore files to include gha-credentials that are generated by workload identity federation
> updating ignore files to include gha-credentials

- params/version.go
> chore: Prepare v1.8.1-rc.1

- params/version.go
> Prepare v1.8.1

- params/version.go
> Prepare v1.8.2

- .github/workflows/add-docker-tag.yaml
- .github/workflows/build-sign-commit-images.yaml
- .github/workflows/build-sign-release-images.yaml
Copy GH Actions from master to release/1.8.4
> Copy GH Actions from master to release/1.8.4

- params/config.go
> Log l2 migration block in config
